//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó mediante una herramienta.
//     Los cambios del archivo se perderán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------
using System;
using System.Collections.Generic;
using System.Linq;
using System.Text;

public class Almacen
{
	public virtual int idAlmacen
	{
		get;
		set;
	}

	public virtual string nombre
	{
		get;
		set;
	}

	public virtual List<Almacen> getAlmacen(string idCliente)
	{
		throw new System.NotImplementedException();
	}

}

