//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó mediante una herramienta.
//     Los cambios del archivo se perderán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------
using System;
using System.Collections.Generic;
using System.Linq;
using System.Text;

public class Contacto
{
	public virtual int idContacto
	{
		get;
		set;
	}

	public virtual string nombre
	{
		get;
		set;
	}

	public virtual int telefono
	{
		get;
		set;
	}

	public virtual string cargo
	{
		get;
		set;
	}

	public virtual string email
	{
		get;
		set;
	}

	public virtual List<Contacto> getContacto(string idCliente)
	{
		throw new System.NotImplementedException();
	}

	public virtual int newContacto(Contacto Contacto)
	{
		throw new System.NotImplementedException();
	}

	public virtual bool updateContacto(Contacto Contacto)
	{
		throw new System.NotImplementedException();
	}

}

