//------------------------------------------------------------------------------
// <auto-generated>
//     Este código fue generado por una herramienta.
//     Versión de runtime:4.0.30319.42000
//
//     Los cambios en este archivo podrían causar un comportamiento incorrecto y se perderán si
//     se vuelve a generar el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace RepositoryWebServiceTRH.DatosEntreEmpresasContext {
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(Namespace="urn:microsoft-dynamics-schemas/codeunit/DatosEntreEmpresas", ConfigurationName="DatosEntreEmpresasContext.DatosEntreEmpresas_Port")]
    public interface DatosEntreEmpresas_Port {
        
        [System.ServiceModel.OperationContractAttribute(Action="urn:microsoft-dynamics-schemas/codeunit/DatosEntreEmpresas:GetInventarioCosteUnit" +
            "ario", ReplyAction="*")]
        RepositoryWebServiceTRH.DatosEntreEmpresasContext.GetInventarioCosteUnitario_Result GetInventarioCosteUnitario(RepositoryWebServiceTRH.DatosEntreEmpresasContext.GetInventarioCosteUnitario request);
        
        [System.ServiceModel.OperationContractAttribute(Action="urn:microsoft-dynamics-schemas/codeunit/DatosEntreEmpresas:GetInventarioCosteUnit" +
            "ario", ReplyAction="*")]
        System.Threading.Tasks.Task<RepositoryWebServiceTRH.DatosEntreEmpresasContext.GetInventarioCosteUnitario_Result> GetInventarioCosteUnitarioAsync(RepositoryWebServiceTRH.DatosEntreEmpresasContext.GetInventarioCosteUnitario request);
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class GetInventarioCosteUnitario {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="GetInventarioCosteUnitario", Namespace="urn:microsoft-dynamics-schemas/codeunit/DatosEntreEmpresas", Order=0)]
        public RepositoryWebServiceTRH.DatosEntreEmpresasContext.GetInventarioCosteUnitarioBody Body;
        
        public GetInventarioCosteUnitario() {
        }
        
        public GetInventarioCosteUnitario(RepositoryWebServiceTRH.DatosEntreEmpresasContext.GetInventarioCosteUnitarioBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="urn:microsoft-dynamics-schemas/codeunit/DatosEntreEmpresas")]
    public partial class GetInventarioCosteUnitarioBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string noProducto;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=1)]
        public string almacen;
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=2)]
        public decimal costeUnitario;
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=3)]
        public decimal inventario;
        
        public GetInventarioCosteUnitarioBody() {
        }
        
        public GetInventarioCosteUnitarioBody(string noProducto, string almacen, decimal costeUnitario, decimal inventario) {
            this.noProducto = noProducto;
            this.almacen = almacen;
            this.costeUnitario = costeUnitario;
            this.inventario = inventario;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class GetInventarioCosteUnitario_Result {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="GetInventarioCosteUnitario_Result", Namespace="urn:microsoft-dynamics-schemas/codeunit/DatosEntreEmpresas", Order=0)]
        public RepositoryWebServiceTRH.DatosEntreEmpresasContext.GetInventarioCosteUnitario_ResultBody Body;
        
        public GetInventarioCosteUnitario_Result() {
        }
        
        public GetInventarioCosteUnitario_Result(RepositoryWebServiceTRH.DatosEntreEmpresasContext.GetInventarioCosteUnitario_ResultBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="urn:microsoft-dynamics-schemas/codeunit/DatosEntreEmpresas")]
    public partial class GetInventarioCosteUnitario_ResultBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=0)]
        public bool return_value;
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=1)]
        public decimal costeUnitario;
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=2)]
        public decimal inventario;
        
        public GetInventarioCosteUnitario_ResultBody() {
        }
        
        public GetInventarioCosteUnitario_ResultBody(bool return_value, decimal costeUnitario, decimal inventario) {
            this.return_value = return_value;
            this.costeUnitario = costeUnitario;
            this.inventario = inventario;
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface DatosEntreEmpresas_PortChannel : RepositoryWebServiceTRH.DatosEntreEmpresasContext.DatosEntreEmpresas_Port, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class DatosEntreEmpresas_PortClient : System.ServiceModel.ClientBase<RepositoryWebServiceTRH.DatosEntreEmpresasContext.DatosEntreEmpresas_Port>, RepositoryWebServiceTRH.DatosEntreEmpresasContext.DatosEntreEmpresas_Port {
        
        public DatosEntreEmpresas_PortClient() {
        }
        
        public DatosEntreEmpresas_PortClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public DatosEntreEmpresas_PortClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public DatosEntreEmpresas_PortClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public DatosEntreEmpresas_PortClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        RepositoryWebServiceTRH.DatosEntreEmpresasContext.GetInventarioCosteUnitario_Result RepositoryWebServiceTRH.DatosEntreEmpresasContext.DatosEntreEmpresas_Port.GetInventarioCosteUnitario(RepositoryWebServiceTRH.DatosEntreEmpresasContext.GetInventarioCosteUnitario request) {
            return base.Channel.GetInventarioCosteUnitario(request);
        }
        
        public bool GetInventarioCosteUnitario(string noProducto, string almacen, ref decimal costeUnitario, ref decimal inventario) {
            RepositoryWebServiceTRH.DatosEntreEmpresasContext.GetInventarioCosteUnitario inValue = new RepositoryWebServiceTRH.DatosEntreEmpresasContext.GetInventarioCosteUnitario();
            inValue.Body = new RepositoryWebServiceTRH.DatosEntreEmpresasContext.GetInventarioCosteUnitarioBody();
            inValue.Body.noProducto = noProducto;
            inValue.Body.almacen = almacen;
            inValue.Body.costeUnitario = costeUnitario;
            inValue.Body.inventario = inventario;
            RepositoryWebServiceTRH.DatosEntreEmpresasContext.GetInventarioCosteUnitario_Result retVal = ((RepositoryWebServiceTRH.DatosEntreEmpresasContext.DatosEntreEmpresas_Port)(this)).GetInventarioCosteUnitario(inValue);
            costeUnitario = retVal.Body.costeUnitario;
            inventario = retVal.Body.inventario;
            return retVal.Body.return_value;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<RepositoryWebServiceTRH.DatosEntreEmpresasContext.GetInventarioCosteUnitario_Result> RepositoryWebServiceTRH.DatosEntreEmpresasContext.DatosEntreEmpresas_Port.GetInventarioCosteUnitarioAsync(RepositoryWebServiceTRH.DatosEntreEmpresasContext.GetInventarioCosteUnitario request) {
            return base.Channel.GetInventarioCosteUnitarioAsync(request);
        }
        
        public System.Threading.Tasks.Task<RepositoryWebServiceTRH.DatosEntreEmpresasContext.GetInventarioCosteUnitario_Result> GetInventarioCosteUnitarioAsync(string noProducto, string almacen, decimal costeUnitario, decimal inventario) {
            RepositoryWebServiceTRH.DatosEntreEmpresasContext.GetInventarioCosteUnitario inValue = new RepositoryWebServiceTRH.DatosEntreEmpresasContext.GetInventarioCosteUnitario();
            inValue.Body = new RepositoryWebServiceTRH.DatosEntreEmpresasContext.GetInventarioCosteUnitarioBody();
            inValue.Body.noProducto = noProducto;
            inValue.Body.almacen = almacen;
            inValue.Body.costeUnitario = costeUnitario;
            inValue.Body.inventario = inventario;
            return ((RepositoryWebServiceTRH.DatosEntreEmpresasContext.DatosEntreEmpresas_Port)(this)).GetInventarioCosteUnitarioAsync(inValue);
        }
    }
}
