//------------------------------------------------------------------------------
// <auto-generated>
//     Este código fue generado por una herramienta.
//     Versión de runtime:4.0.30319.42000
//
//     Los cambios en este archivo podrían causar un comportamiento incorrecto y se perderán si
//     se vuelve a generar el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace wsTRH.pAlmacenes {
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(Namespace="urn:microsoft-dynamics-schemas/page/almacenesclientes", ConfigurationName="pAlmacenes.AlmacenesClientes_Port")]
    public interface AlmacenesClientes_Port {
        
        // CODEGEN: Se está generando un contrato de mensaje, ya que el nombre de contenedor (Read_Result) del mensaje Read_Result no coincide con el valor predeterminado (Read)
        [System.ServiceModel.OperationContractAttribute(Action="urn:microsoft-dynamics-schemas/page/almacenesclientes:Read", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        wsTRH.pAlmacenes.Read_Result Read(wsTRH.pAlmacenes.Read request);
        
        [System.ServiceModel.OperationContractAttribute(Action="urn:microsoft-dynamics-schemas/page/almacenesclientes:Read", ReplyAction="*")]
        System.Threading.Tasks.Task<wsTRH.pAlmacenes.Read_Result> ReadAsync(wsTRH.pAlmacenes.Read request);
        
        // CODEGEN: Se está generando un contrato de mensaje, ya que el nombre de contenedor (ReadByRecId_Result) del mensaje ReadByRecId_Result no coincide con el valor predeterminado (ReadByRecId)
        [System.ServiceModel.OperationContractAttribute(Action="urn:microsoft-dynamics-schemas/page/almacenesclientes:ReadByRecId", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        wsTRH.pAlmacenes.ReadByRecId_Result ReadByRecId(wsTRH.pAlmacenes.ReadByRecId request);
        
        [System.ServiceModel.OperationContractAttribute(Action="urn:microsoft-dynamics-schemas/page/almacenesclientes:ReadByRecId", ReplyAction="*")]
        System.Threading.Tasks.Task<wsTRH.pAlmacenes.ReadByRecId_Result> ReadByRecIdAsync(wsTRH.pAlmacenes.ReadByRecId request);
        
        // CODEGEN: Se está generando un contrato de mensaje, ya que el nombre de contenedor (ReadMultiple_Result) del mensaje ReadMultiple_Result no coincide con el valor predeterminado (ReadMultiple)
        [System.ServiceModel.OperationContractAttribute(Action="urn:microsoft-dynamics-schemas/page/almacenesclientes:ReadMultiple", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        wsTRH.pAlmacenes.ReadMultiple_Result ReadMultiple(wsTRH.pAlmacenes.ReadMultiple request);
        
        [System.ServiceModel.OperationContractAttribute(Action="urn:microsoft-dynamics-schemas/page/almacenesclientes:ReadMultiple", ReplyAction="*")]
        System.Threading.Tasks.Task<wsTRH.pAlmacenes.ReadMultiple_Result> ReadMultipleAsync(wsTRH.pAlmacenes.ReadMultiple request);
        
        // CODEGEN: Se está generando un contrato de mensaje, ya que el nombre de contenedor (IsUpdated_Result) del mensaje IsUpdated_Result no coincide con el valor predeterminado (IsUpdated)
        [System.ServiceModel.OperationContractAttribute(Action="urn:microsoft-dynamics-schemas/page/almacenesclientes:IsUpdated", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        wsTRH.pAlmacenes.IsUpdated_Result IsUpdated(wsTRH.pAlmacenes.IsUpdated request);
        
        [System.ServiceModel.OperationContractAttribute(Action="urn:microsoft-dynamics-schemas/page/almacenesclientes:IsUpdated", ReplyAction="*")]
        System.Threading.Tasks.Task<wsTRH.pAlmacenes.IsUpdated_Result> IsUpdatedAsync(wsTRH.pAlmacenes.IsUpdated request);
        
        // CODEGEN: Se está generando un contrato de mensaje, ya que el nombre de contenedor (GetRecIdFromKey_Result) del mensaje GetRecIdFromKey_Result no coincide con el valor predeterminado (GetRecIdFromKey)
        [System.ServiceModel.OperationContractAttribute(Action="urn:microsoft-dynamics-schemas/page/almacenesclientes:GetRecIdFromKey", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        wsTRH.pAlmacenes.GetRecIdFromKey_Result GetRecIdFromKey(wsTRH.pAlmacenes.GetRecIdFromKey request);
        
        [System.ServiceModel.OperationContractAttribute(Action="urn:microsoft-dynamics-schemas/page/almacenesclientes:GetRecIdFromKey", ReplyAction="*")]
        System.Threading.Tasks.Task<wsTRH.pAlmacenes.GetRecIdFromKey_Result> GetRecIdFromKeyAsync(wsTRH.pAlmacenes.GetRecIdFromKey request);
        
        [System.ServiceModel.OperationContractAttribute(Action="urn:microsoft-dynamics-schemas/page/almacenesclientes:Create", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        wsTRH.pAlmacenes.Create_Result Create(wsTRH.pAlmacenes.Create request);
        
        // CODEGEN: Generando contrato de mensaje, ya que la operación tiene múltiples valores de devolución.
        [System.ServiceModel.OperationContractAttribute(Action="urn:microsoft-dynamics-schemas/page/almacenesclientes:Create", ReplyAction="*")]
        System.Threading.Tasks.Task<wsTRH.pAlmacenes.Create_Result> CreateAsync(wsTRH.pAlmacenes.Create request);
        
        [System.ServiceModel.OperationContractAttribute(Action="urn:microsoft-dynamics-schemas/page/almacenesclientes:CreateMultiple", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        wsTRH.pAlmacenes.CreateMultiple_Result CreateMultiple(wsTRH.pAlmacenes.CreateMultiple request);
        
        // CODEGEN: Generando contrato de mensaje, ya que la operación tiene múltiples valores de devolución.
        [System.ServiceModel.OperationContractAttribute(Action="urn:microsoft-dynamics-schemas/page/almacenesclientes:CreateMultiple", ReplyAction="*")]
        System.Threading.Tasks.Task<wsTRH.pAlmacenes.CreateMultiple_Result> CreateMultipleAsync(wsTRH.pAlmacenes.CreateMultiple request);
        
        [System.ServiceModel.OperationContractAttribute(Action="urn:microsoft-dynamics-schemas/page/almacenesclientes:Update", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        wsTRH.pAlmacenes.Update_Result Update(wsTRH.pAlmacenes.Update request);
        
        // CODEGEN: Generando contrato de mensaje, ya que la operación tiene múltiples valores de devolución.
        [System.ServiceModel.OperationContractAttribute(Action="urn:microsoft-dynamics-schemas/page/almacenesclientes:Update", ReplyAction="*")]
        System.Threading.Tasks.Task<wsTRH.pAlmacenes.Update_Result> UpdateAsync(wsTRH.pAlmacenes.Update request);
        
        [System.ServiceModel.OperationContractAttribute(Action="urn:microsoft-dynamics-schemas/page/almacenesclientes:UpdateMultiple", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        wsTRH.pAlmacenes.UpdateMultiple_Result UpdateMultiple(wsTRH.pAlmacenes.UpdateMultiple request);
        
        // CODEGEN: Generando contrato de mensaje, ya que la operación tiene múltiples valores de devolución.
        [System.ServiceModel.OperationContractAttribute(Action="urn:microsoft-dynamics-schemas/page/almacenesclientes:UpdateMultiple", ReplyAction="*")]
        System.Threading.Tasks.Task<wsTRH.pAlmacenes.UpdateMultiple_Result> UpdateMultipleAsync(wsTRH.pAlmacenes.UpdateMultiple request);
        
        // CODEGEN: Se está generando un contrato de mensaje, ya que el nombre de contenedor (Delete_Result) del mensaje Delete_Result no coincide con el valor predeterminado (Delete)
        [System.ServiceModel.OperationContractAttribute(Action="urn:microsoft-dynamics-schemas/page/almacenesclientes:Delete", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        wsTRH.pAlmacenes.Delete_Result Delete(wsTRH.pAlmacenes.Delete request);
        
        [System.ServiceModel.OperationContractAttribute(Action="urn:microsoft-dynamics-schemas/page/almacenesclientes:Delete", ReplyAction="*")]
        System.Threading.Tasks.Task<wsTRH.pAlmacenes.Delete_Result> DeleteAsync(wsTRH.pAlmacenes.Delete request);
    }
    
    /// <comentarios/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.6.1064.2")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="urn:microsoft-dynamics-schemas/page/almacenesclientes")]
    public partial class AlmacenesClientes : object, System.ComponentModel.INotifyPropertyChanged {
        
        private string keyField;
        
        private int idAlmacenField;
        
        private bool idAlmacenFieldSpecified;
        
        private string nombreAlmacenField;
        
        private string idClienteField;
        
        private string idComercialField;
        
        /// <comentarios/>
        [System.Xml.Serialization.XmlElementAttribute(Order=0)]
        public string Key {
            get {
                return this.keyField;
            }
            set {
                this.keyField = value;
                this.RaisePropertyChanged("Key");
            }
        }
        
        /// <comentarios/>
        [System.Xml.Serialization.XmlElementAttribute(Order=1)]
        public int IdAlmacen {
            get {
                return this.idAlmacenField;
            }
            set {
                this.idAlmacenField = value;
                this.RaisePropertyChanged("IdAlmacen");
            }
        }
        
        /// <comentarios/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool IdAlmacenSpecified {
            get {
                return this.idAlmacenFieldSpecified;
            }
            set {
                this.idAlmacenFieldSpecified = value;
                this.RaisePropertyChanged("IdAlmacenSpecified");
            }
        }
        
        /// <comentarios/>
        [System.Xml.Serialization.XmlElementAttribute(Order=2)]
        public string NombreAlmacen {
            get {
                return this.nombreAlmacenField;
            }
            set {
                this.nombreAlmacenField = value;
                this.RaisePropertyChanged("NombreAlmacen");
            }
        }
        
        /// <comentarios/>
        [System.Xml.Serialization.XmlElementAttribute(Order=3)]
        public string IdCliente {
            get {
                return this.idClienteField;
            }
            set {
                this.idClienteField = value;
                this.RaisePropertyChanged("IdCliente");
            }
        }
        
        /// <comentarios/>
        [System.Xml.Serialization.XmlElementAttribute(Order=4)]
        public string IdComercial {
            get {
                return this.idComercialField;
            }
            set {
                this.idComercialField = value;
                this.RaisePropertyChanged("IdComercial");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    /// <comentarios/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.6.1064.2")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="urn:microsoft-dynamics-schemas/page/almacenesclientes")]
    public partial class AlmacenesClientes_Filter : object, System.ComponentModel.INotifyPropertyChanged {
        
        private AlmacenesClientes_Fields fieldField;
        
        private string criteriaField;
        
        /// <comentarios/>
        [System.Xml.Serialization.XmlElementAttribute(Order=0)]
        public AlmacenesClientes_Fields Field {
            get {
                return this.fieldField;
            }
            set {
                this.fieldField = value;
                this.RaisePropertyChanged("Field");
            }
        }
        
        /// <comentarios/>
        [System.Xml.Serialization.XmlElementAttribute(Order=1)]
        public string Criteria {
            get {
                return this.criteriaField;
            }
            set {
                this.criteriaField = value;
                this.RaisePropertyChanged("Criteria");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    /// <comentarios/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.6.1064.2")]
    [System.SerializableAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="urn:microsoft-dynamics-schemas/page/almacenesclientes")]
    public enum AlmacenesClientes_Fields {
        
        /// <comentarios/>
        IdAlmacen,
        
        /// <comentarios/>
        NombreAlmacen,
        
        /// <comentarios/>
        IdCliente,
        
        /// <comentarios/>
        IdComercial,
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="Read", WrapperNamespace="urn:microsoft-dynamics-schemas/page/almacenesclientes", IsWrapped=true)]
    public partial class Read {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="urn:microsoft-dynamics-schemas/page/almacenesclientes", Order=0)]
        public int IdAlmacen;
        
        public Read() {
        }
        
        public Read(int IdAlmacen) {
            this.IdAlmacen = IdAlmacen;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="Read_Result", WrapperNamespace="urn:microsoft-dynamics-schemas/page/almacenesclientes", IsWrapped=true)]
    public partial class Read_Result {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="urn:microsoft-dynamics-schemas/page/almacenesclientes", Order=0)]
        public wsTRH.pAlmacenes.AlmacenesClientes AlmacenesClientes;
        
        public Read_Result() {
        }
        
        public Read_Result(wsTRH.pAlmacenes.AlmacenesClientes AlmacenesClientes) {
            this.AlmacenesClientes = AlmacenesClientes;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="ReadByRecId", WrapperNamespace="urn:microsoft-dynamics-schemas/page/almacenesclientes", IsWrapped=true)]
    public partial class ReadByRecId {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="urn:microsoft-dynamics-schemas/page/almacenesclientes", Order=0)]
        public string recId;
        
        public ReadByRecId() {
        }
        
        public ReadByRecId(string recId) {
            this.recId = recId;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="ReadByRecId_Result", WrapperNamespace="urn:microsoft-dynamics-schemas/page/almacenesclientes", IsWrapped=true)]
    public partial class ReadByRecId_Result {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="urn:microsoft-dynamics-schemas/page/almacenesclientes", Order=0)]
        public wsTRH.pAlmacenes.AlmacenesClientes AlmacenesClientes;
        
        public ReadByRecId_Result() {
        }
        
        public ReadByRecId_Result(wsTRH.pAlmacenes.AlmacenesClientes AlmacenesClientes) {
            this.AlmacenesClientes = AlmacenesClientes;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="ReadMultiple", WrapperNamespace="urn:microsoft-dynamics-schemas/page/almacenesclientes", IsWrapped=true)]
    public partial class ReadMultiple {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="urn:microsoft-dynamics-schemas/page/almacenesclientes", Order=0)]
        [System.Xml.Serialization.XmlElementAttribute("filter")]
        public wsTRH.pAlmacenes.AlmacenesClientes_Filter[] filter;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="urn:microsoft-dynamics-schemas/page/almacenesclientes", Order=1)]
        public string bookmarkKey;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="urn:microsoft-dynamics-schemas/page/almacenesclientes", Order=2)]
        public int setSize;
        
        public ReadMultiple() {
        }
        
        public ReadMultiple(wsTRH.pAlmacenes.AlmacenesClientes_Filter[] filter, string bookmarkKey, int setSize) {
            this.filter = filter;
            this.bookmarkKey = bookmarkKey;
            this.setSize = setSize;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="ReadMultiple_Result", WrapperNamespace="urn:microsoft-dynamics-schemas/page/almacenesclientes", IsWrapped=true)]
    public partial class ReadMultiple_Result {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="ReadMultiple_Result", Namespace="urn:microsoft-dynamics-schemas/page/almacenesclientes", Order=0)]
        [System.Xml.Serialization.XmlArrayItemAttribute(IsNullable=false)]
        public wsTRH.pAlmacenes.AlmacenesClientes[] ReadMultiple_Result1;
        
        public ReadMultiple_Result() {
        }
        
        public ReadMultiple_Result(wsTRH.pAlmacenes.AlmacenesClientes[] ReadMultiple_Result1) {
            this.ReadMultiple_Result1 = ReadMultiple_Result1;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="IsUpdated", WrapperNamespace="urn:microsoft-dynamics-schemas/page/almacenesclientes", IsWrapped=true)]
    public partial class IsUpdated {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="urn:microsoft-dynamics-schemas/page/almacenesclientes", Order=0)]
        public string Key;
        
        public IsUpdated() {
        }
        
        public IsUpdated(string Key) {
            this.Key = Key;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="IsUpdated_Result", WrapperNamespace="urn:microsoft-dynamics-schemas/page/almacenesclientes", IsWrapped=true)]
    public partial class IsUpdated_Result {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="IsUpdated_Result", Namespace="urn:microsoft-dynamics-schemas/page/almacenesclientes", Order=0)]
        public bool IsUpdated_Result1;
        
        public IsUpdated_Result() {
        }
        
        public IsUpdated_Result(bool IsUpdated_Result1) {
            this.IsUpdated_Result1 = IsUpdated_Result1;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="GetRecIdFromKey", WrapperNamespace="urn:microsoft-dynamics-schemas/page/almacenesclientes", IsWrapped=true)]
    public partial class GetRecIdFromKey {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="urn:microsoft-dynamics-schemas/page/almacenesclientes", Order=0)]
        public string Key;
        
        public GetRecIdFromKey() {
        }
        
        public GetRecIdFromKey(string Key) {
            this.Key = Key;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="GetRecIdFromKey_Result", WrapperNamespace="urn:microsoft-dynamics-schemas/page/almacenesclientes", IsWrapped=true)]
    public partial class GetRecIdFromKey_Result {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="GetRecIdFromKey_Result", Namespace="urn:microsoft-dynamics-schemas/page/almacenesclientes", Order=0)]
        public string GetRecIdFromKey_Result1;
        
        public GetRecIdFromKey_Result() {
        }
        
        public GetRecIdFromKey_Result(string GetRecIdFromKey_Result1) {
            this.GetRecIdFromKey_Result1 = GetRecIdFromKey_Result1;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.MessageContractAttribute(WrapperName="Create", WrapperNamespace="urn:microsoft-dynamics-schemas/page/almacenesclientes", IsWrapped=true)]
    public partial class Create {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="urn:microsoft-dynamics-schemas/page/almacenesclientes", Order=0)]
        public wsTRH.pAlmacenes.AlmacenesClientes AlmacenesClientes;
        
        public Create() {
        }
        
        public Create(wsTRH.pAlmacenes.AlmacenesClientes AlmacenesClientes) {
            this.AlmacenesClientes = AlmacenesClientes;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.MessageContractAttribute(WrapperName="Create_Result", WrapperNamespace="urn:microsoft-dynamics-schemas/page/almacenesclientes", IsWrapped=true)]
    public partial class Create_Result {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="urn:microsoft-dynamics-schemas/page/almacenesclientes", Order=0)]
        public wsTRH.pAlmacenes.AlmacenesClientes AlmacenesClientes;
        
        public Create_Result() {
        }
        
        public Create_Result(wsTRH.pAlmacenes.AlmacenesClientes AlmacenesClientes) {
            this.AlmacenesClientes = AlmacenesClientes;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.MessageContractAttribute(WrapperName="CreateMultiple", WrapperNamespace="urn:microsoft-dynamics-schemas/page/almacenesclientes", IsWrapped=true)]
    public partial class CreateMultiple {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="urn:microsoft-dynamics-schemas/page/almacenesclientes", Order=0)]
        [System.Xml.Serialization.XmlArrayItemAttribute(IsNullable=false)]
        public wsTRH.pAlmacenes.AlmacenesClientes[] AlmacenesClientes_List;
        
        public CreateMultiple() {
        }
        
        public CreateMultiple(wsTRH.pAlmacenes.AlmacenesClientes[] AlmacenesClientes_List) {
            this.AlmacenesClientes_List = AlmacenesClientes_List;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.MessageContractAttribute(WrapperName="CreateMultiple_Result", WrapperNamespace="urn:microsoft-dynamics-schemas/page/almacenesclientes", IsWrapped=true)]
    public partial class CreateMultiple_Result {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="urn:microsoft-dynamics-schemas/page/almacenesclientes", Order=0)]
        [System.Xml.Serialization.XmlArrayItemAttribute(IsNullable=false)]
        public wsTRH.pAlmacenes.AlmacenesClientes[] AlmacenesClientes_List;
        
        public CreateMultiple_Result() {
        }
        
        public CreateMultiple_Result(wsTRH.pAlmacenes.AlmacenesClientes[] AlmacenesClientes_List) {
            this.AlmacenesClientes_List = AlmacenesClientes_List;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.MessageContractAttribute(WrapperName="Update", WrapperNamespace="urn:microsoft-dynamics-schemas/page/almacenesclientes", IsWrapped=true)]
    public partial class Update {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="urn:microsoft-dynamics-schemas/page/almacenesclientes", Order=0)]
        public wsTRH.pAlmacenes.AlmacenesClientes AlmacenesClientes;
        
        public Update() {
        }
        
        public Update(wsTRH.pAlmacenes.AlmacenesClientes AlmacenesClientes) {
            this.AlmacenesClientes = AlmacenesClientes;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.MessageContractAttribute(WrapperName="Update_Result", WrapperNamespace="urn:microsoft-dynamics-schemas/page/almacenesclientes", IsWrapped=true)]
    public partial class Update_Result {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="urn:microsoft-dynamics-schemas/page/almacenesclientes", Order=0)]
        public wsTRH.pAlmacenes.AlmacenesClientes AlmacenesClientes;
        
        public Update_Result() {
        }
        
        public Update_Result(wsTRH.pAlmacenes.AlmacenesClientes AlmacenesClientes) {
            this.AlmacenesClientes = AlmacenesClientes;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.MessageContractAttribute(WrapperName="UpdateMultiple", WrapperNamespace="urn:microsoft-dynamics-schemas/page/almacenesclientes", IsWrapped=true)]
    public partial class UpdateMultiple {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="urn:microsoft-dynamics-schemas/page/almacenesclientes", Order=0)]
        [System.Xml.Serialization.XmlArrayItemAttribute(IsNullable=false)]
        public wsTRH.pAlmacenes.AlmacenesClientes[] AlmacenesClientes_List;
        
        public UpdateMultiple() {
        }
        
        public UpdateMultiple(wsTRH.pAlmacenes.AlmacenesClientes[] AlmacenesClientes_List) {
            this.AlmacenesClientes_List = AlmacenesClientes_List;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.MessageContractAttribute(WrapperName="UpdateMultiple_Result", WrapperNamespace="urn:microsoft-dynamics-schemas/page/almacenesclientes", IsWrapped=true)]
    public partial class UpdateMultiple_Result {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="urn:microsoft-dynamics-schemas/page/almacenesclientes", Order=0)]
        [System.Xml.Serialization.XmlArrayItemAttribute(IsNullable=false)]
        public wsTRH.pAlmacenes.AlmacenesClientes[] AlmacenesClientes_List;
        
        public UpdateMultiple_Result() {
        }
        
        public UpdateMultiple_Result(wsTRH.pAlmacenes.AlmacenesClientes[] AlmacenesClientes_List) {
            this.AlmacenesClientes_List = AlmacenesClientes_List;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="Delete", WrapperNamespace="urn:microsoft-dynamics-schemas/page/almacenesclientes", IsWrapped=true)]
    public partial class Delete {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="urn:microsoft-dynamics-schemas/page/almacenesclientes", Order=0)]
        public string Key;
        
        public Delete() {
        }
        
        public Delete(string Key) {
            this.Key = Key;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="Delete_Result", WrapperNamespace="urn:microsoft-dynamics-schemas/page/almacenesclientes", IsWrapped=true)]
    public partial class Delete_Result {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="Delete_Result", Namespace="urn:microsoft-dynamics-schemas/page/almacenesclientes", Order=0)]
        public bool Delete_Result1;
        
        public Delete_Result() {
        }
        
        public Delete_Result(bool Delete_Result1) {
            this.Delete_Result1 = Delete_Result1;
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface AlmacenesClientes_PortChannel : wsTRH.pAlmacenes.AlmacenesClientes_Port, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class AlmacenesClientes_PortClient : System.ServiceModel.ClientBase<wsTRH.pAlmacenes.AlmacenesClientes_Port>, wsTRH.pAlmacenes.AlmacenesClientes_Port {
        
        public AlmacenesClientes_PortClient() {
        }
        
        public AlmacenesClientes_PortClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public AlmacenesClientes_PortClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public AlmacenesClientes_PortClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public AlmacenesClientes_PortClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        wsTRH.pAlmacenes.Read_Result wsTRH.pAlmacenes.AlmacenesClientes_Port.Read(wsTRH.pAlmacenes.Read request) {
            return base.Channel.Read(request);
        }
        
        public wsTRH.pAlmacenes.AlmacenesClientes Read(int IdAlmacen) {
            wsTRH.pAlmacenes.Read inValue = new wsTRH.pAlmacenes.Read();
            inValue.IdAlmacen = IdAlmacen;
            wsTRH.pAlmacenes.Read_Result retVal = ((wsTRH.pAlmacenes.AlmacenesClientes_Port)(this)).Read(inValue);
            return retVal.AlmacenesClientes;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<wsTRH.pAlmacenes.Read_Result> wsTRH.pAlmacenes.AlmacenesClientes_Port.ReadAsync(wsTRH.pAlmacenes.Read request) {
            return base.Channel.ReadAsync(request);
        }
        
        public System.Threading.Tasks.Task<wsTRH.pAlmacenes.Read_Result> ReadAsync(int IdAlmacen) {
            wsTRH.pAlmacenes.Read inValue = new wsTRH.pAlmacenes.Read();
            inValue.IdAlmacen = IdAlmacen;
            return ((wsTRH.pAlmacenes.AlmacenesClientes_Port)(this)).ReadAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        wsTRH.pAlmacenes.ReadByRecId_Result wsTRH.pAlmacenes.AlmacenesClientes_Port.ReadByRecId(wsTRH.pAlmacenes.ReadByRecId request) {
            return base.Channel.ReadByRecId(request);
        }
        
        public wsTRH.pAlmacenes.AlmacenesClientes ReadByRecId(string recId) {
            wsTRH.pAlmacenes.ReadByRecId inValue = new wsTRH.pAlmacenes.ReadByRecId();
            inValue.recId = recId;
            wsTRH.pAlmacenes.ReadByRecId_Result retVal = ((wsTRH.pAlmacenes.AlmacenesClientes_Port)(this)).ReadByRecId(inValue);
            return retVal.AlmacenesClientes;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<wsTRH.pAlmacenes.ReadByRecId_Result> wsTRH.pAlmacenes.AlmacenesClientes_Port.ReadByRecIdAsync(wsTRH.pAlmacenes.ReadByRecId request) {
            return base.Channel.ReadByRecIdAsync(request);
        }
        
        public System.Threading.Tasks.Task<wsTRH.pAlmacenes.ReadByRecId_Result> ReadByRecIdAsync(string recId) {
            wsTRH.pAlmacenes.ReadByRecId inValue = new wsTRH.pAlmacenes.ReadByRecId();
            inValue.recId = recId;
            return ((wsTRH.pAlmacenes.AlmacenesClientes_Port)(this)).ReadByRecIdAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        wsTRH.pAlmacenes.ReadMultiple_Result wsTRH.pAlmacenes.AlmacenesClientes_Port.ReadMultiple(wsTRH.pAlmacenes.ReadMultiple request) {
            return base.Channel.ReadMultiple(request);
        }
        
        public wsTRH.pAlmacenes.AlmacenesClientes[] ReadMultiple(wsTRH.pAlmacenes.AlmacenesClientes_Filter[] filter, string bookmarkKey, int setSize) {
            wsTRH.pAlmacenes.ReadMultiple inValue = new wsTRH.pAlmacenes.ReadMultiple();
            inValue.filter = filter;
            inValue.bookmarkKey = bookmarkKey;
            inValue.setSize = setSize;
            wsTRH.pAlmacenes.ReadMultiple_Result retVal = ((wsTRH.pAlmacenes.AlmacenesClientes_Port)(this)).ReadMultiple(inValue);
            return retVal.ReadMultiple_Result1;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<wsTRH.pAlmacenes.ReadMultiple_Result> wsTRH.pAlmacenes.AlmacenesClientes_Port.ReadMultipleAsync(wsTRH.pAlmacenes.ReadMultiple request) {
            return base.Channel.ReadMultipleAsync(request);
        }
        
        public System.Threading.Tasks.Task<wsTRH.pAlmacenes.ReadMultiple_Result> ReadMultipleAsync(wsTRH.pAlmacenes.AlmacenesClientes_Filter[] filter, string bookmarkKey, int setSize) {
            wsTRH.pAlmacenes.ReadMultiple inValue = new wsTRH.pAlmacenes.ReadMultiple();
            inValue.filter = filter;
            inValue.bookmarkKey = bookmarkKey;
            inValue.setSize = setSize;
            return ((wsTRH.pAlmacenes.AlmacenesClientes_Port)(this)).ReadMultipleAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        wsTRH.pAlmacenes.IsUpdated_Result wsTRH.pAlmacenes.AlmacenesClientes_Port.IsUpdated(wsTRH.pAlmacenes.IsUpdated request) {
            return base.Channel.IsUpdated(request);
        }
        
        public bool IsUpdated(string Key) {
            wsTRH.pAlmacenes.IsUpdated inValue = new wsTRH.pAlmacenes.IsUpdated();
            inValue.Key = Key;
            wsTRH.pAlmacenes.IsUpdated_Result retVal = ((wsTRH.pAlmacenes.AlmacenesClientes_Port)(this)).IsUpdated(inValue);
            return retVal.IsUpdated_Result1;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<wsTRH.pAlmacenes.IsUpdated_Result> wsTRH.pAlmacenes.AlmacenesClientes_Port.IsUpdatedAsync(wsTRH.pAlmacenes.IsUpdated request) {
            return base.Channel.IsUpdatedAsync(request);
        }
        
        public System.Threading.Tasks.Task<wsTRH.pAlmacenes.IsUpdated_Result> IsUpdatedAsync(string Key) {
            wsTRH.pAlmacenes.IsUpdated inValue = new wsTRH.pAlmacenes.IsUpdated();
            inValue.Key = Key;
            return ((wsTRH.pAlmacenes.AlmacenesClientes_Port)(this)).IsUpdatedAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        wsTRH.pAlmacenes.GetRecIdFromKey_Result wsTRH.pAlmacenes.AlmacenesClientes_Port.GetRecIdFromKey(wsTRH.pAlmacenes.GetRecIdFromKey request) {
            return base.Channel.GetRecIdFromKey(request);
        }
        
        public string GetRecIdFromKey(string Key) {
            wsTRH.pAlmacenes.GetRecIdFromKey inValue = new wsTRH.pAlmacenes.GetRecIdFromKey();
            inValue.Key = Key;
            wsTRH.pAlmacenes.GetRecIdFromKey_Result retVal = ((wsTRH.pAlmacenes.AlmacenesClientes_Port)(this)).GetRecIdFromKey(inValue);
            return retVal.GetRecIdFromKey_Result1;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<wsTRH.pAlmacenes.GetRecIdFromKey_Result> wsTRH.pAlmacenes.AlmacenesClientes_Port.GetRecIdFromKeyAsync(wsTRH.pAlmacenes.GetRecIdFromKey request) {
            return base.Channel.GetRecIdFromKeyAsync(request);
        }
        
        public System.Threading.Tasks.Task<wsTRH.pAlmacenes.GetRecIdFromKey_Result> GetRecIdFromKeyAsync(string Key) {
            wsTRH.pAlmacenes.GetRecIdFromKey inValue = new wsTRH.pAlmacenes.GetRecIdFromKey();
            inValue.Key = Key;
            return ((wsTRH.pAlmacenes.AlmacenesClientes_Port)(this)).GetRecIdFromKeyAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        wsTRH.pAlmacenes.Create_Result wsTRH.pAlmacenes.AlmacenesClientes_Port.Create(wsTRH.pAlmacenes.Create request) {
            return base.Channel.Create(request);
        }
        
        public void Create(ref wsTRH.pAlmacenes.AlmacenesClientes AlmacenesClientes) {
            wsTRH.pAlmacenes.Create inValue = new wsTRH.pAlmacenes.Create();
            inValue.AlmacenesClientes = AlmacenesClientes;
            wsTRH.pAlmacenes.Create_Result retVal = ((wsTRH.pAlmacenes.AlmacenesClientes_Port)(this)).Create(inValue);
            AlmacenesClientes = retVal.AlmacenesClientes;
        }
        
        public System.Threading.Tasks.Task<wsTRH.pAlmacenes.Create_Result> CreateAsync(wsTRH.pAlmacenes.Create request) {
            return base.Channel.CreateAsync(request);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        wsTRH.pAlmacenes.CreateMultiple_Result wsTRH.pAlmacenes.AlmacenesClientes_Port.CreateMultiple(wsTRH.pAlmacenes.CreateMultiple request) {
            return base.Channel.CreateMultiple(request);
        }
        
        public void CreateMultiple(ref wsTRH.pAlmacenes.AlmacenesClientes[] AlmacenesClientes_List) {
            wsTRH.pAlmacenes.CreateMultiple inValue = new wsTRH.pAlmacenes.CreateMultiple();
            inValue.AlmacenesClientes_List = AlmacenesClientes_List;
            wsTRH.pAlmacenes.CreateMultiple_Result retVal = ((wsTRH.pAlmacenes.AlmacenesClientes_Port)(this)).CreateMultiple(inValue);
            AlmacenesClientes_List = retVal.AlmacenesClientes_List;
        }
        
        public System.Threading.Tasks.Task<wsTRH.pAlmacenes.CreateMultiple_Result> CreateMultipleAsync(wsTRH.pAlmacenes.CreateMultiple request) {
            return base.Channel.CreateMultipleAsync(request);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        wsTRH.pAlmacenes.Update_Result wsTRH.pAlmacenes.AlmacenesClientes_Port.Update(wsTRH.pAlmacenes.Update request) {
            return base.Channel.Update(request);
        }
        
        public void Update(ref wsTRH.pAlmacenes.AlmacenesClientes AlmacenesClientes) {
            wsTRH.pAlmacenes.Update inValue = new wsTRH.pAlmacenes.Update();
            inValue.AlmacenesClientes = AlmacenesClientes;
            wsTRH.pAlmacenes.Update_Result retVal = ((wsTRH.pAlmacenes.AlmacenesClientes_Port)(this)).Update(inValue);
            AlmacenesClientes = retVal.AlmacenesClientes;
        }
        
        public System.Threading.Tasks.Task<wsTRH.pAlmacenes.Update_Result> UpdateAsync(wsTRH.pAlmacenes.Update request) {
            return base.Channel.UpdateAsync(request);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        wsTRH.pAlmacenes.UpdateMultiple_Result wsTRH.pAlmacenes.AlmacenesClientes_Port.UpdateMultiple(wsTRH.pAlmacenes.UpdateMultiple request) {
            return base.Channel.UpdateMultiple(request);
        }
        
        public void UpdateMultiple(ref wsTRH.pAlmacenes.AlmacenesClientes[] AlmacenesClientes_List) {
            wsTRH.pAlmacenes.UpdateMultiple inValue = new wsTRH.pAlmacenes.UpdateMultiple();
            inValue.AlmacenesClientes_List = AlmacenesClientes_List;
            wsTRH.pAlmacenes.UpdateMultiple_Result retVal = ((wsTRH.pAlmacenes.AlmacenesClientes_Port)(this)).UpdateMultiple(inValue);
            AlmacenesClientes_List = retVal.AlmacenesClientes_List;
        }
        
        public System.Threading.Tasks.Task<wsTRH.pAlmacenes.UpdateMultiple_Result> UpdateMultipleAsync(wsTRH.pAlmacenes.UpdateMultiple request) {
            return base.Channel.UpdateMultipleAsync(request);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        wsTRH.pAlmacenes.Delete_Result wsTRH.pAlmacenes.AlmacenesClientes_Port.Delete(wsTRH.pAlmacenes.Delete request) {
            return base.Channel.Delete(request);
        }
        
        public bool Delete(string Key) {
            wsTRH.pAlmacenes.Delete inValue = new wsTRH.pAlmacenes.Delete();
            inValue.Key = Key;
            wsTRH.pAlmacenes.Delete_Result retVal = ((wsTRH.pAlmacenes.AlmacenesClientes_Port)(this)).Delete(inValue);
            return retVal.Delete_Result1;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<wsTRH.pAlmacenes.Delete_Result> wsTRH.pAlmacenes.AlmacenesClientes_Port.DeleteAsync(wsTRH.pAlmacenes.Delete request) {
            return base.Channel.DeleteAsync(request);
        }
        
        public System.Threading.Tasks.Task<wsTRH.pAlmacenes.Delete_Result> DeleteAsync(string Key) {
            wsTRH.pAlmacenes.Delete inValue = new wsTRH.pAlmacenes.Delete();
            inValue.Key = Key;
            return ((wsTRH.pAlmacenes.AlmacenesClientes_Port)(this)).DeleteAsync(inValue);
        }
    }
}
