//------------------------------------------------------------------------------
// <auto-generated>
//     Este código fue generado por una herramienta.
//     Versión de runtime:4.0.30319.42000
//
//     Los cambios en este archivo podrían causar un comportamiento incorrecto y se perderán si
//     se vuelve a generar el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace RepositoryWebServiceTRH.PedidoListadoContext {
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(Namespace="urn:microsoft-dynamics-schemas/page/pedidolistado", ConfigurationName="PedidoListadoContext.PedidoListado_Port")]
    public interface PedidoListado_Port {
        
        // CODEGEN: Se está generando un contrato de mensaje, ya que el nombre de contenedor (Read_Result) del mensaje Read_Result no coincide con el valor predeterminado (Read)
        [System.ServiceModel.OperationContractAttribute(Action="urn:microsoft-dynamics-schemas/page/pedidolistado:Read", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        RepositoryWebServiceTRH.PedidoListadoContext.Read_Result Read(RepositoryWebServiceTRH.PedidoListadoContext.Read request);
        
        [System.ServiceModel.OperationContractAttribute(Action="urn:microsoft-dynamics-schemas/page/pedidolistado:Read", ReplyAction="*")]
        System.Threading.Tasks.Task<RepositoryWebServiceTRH.PedidoListadoContext.Read_Result> ReadAsync(RepositoryWebServiceTRH.PedidoListadoContext.Read request);
        
        // CODEGEN: Se está generando un contrato de mensaje, ya que el nombre de contenedor (ReadByRecId_Result) del mensaje ReadByRecId_Result no coincide con el valor predeterminado (ReadByRecId)
        [System.ServiceModel.OperationContractAttribute(Action="urn:microsoft-dynamics-schemas/page/pedidolistado:ReadByRecId", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        RepositoryWebServiceTRH.PedidoListadoContext.ReadByRecId_Result ReadByRecId(RepositoryWebServiceTRH.PedidoListadoContext.ReadByRecId request);
        
        [System.ServiceModel.OperationContractAttribute(Action="urn:microsoft-dynamics-schemas/page/pedidolistado:ReadByRecId", ReplyAction="*")]
        System.Threading.Tasks.Task<RepositoryWebServiceTRH.PedidoListadoContext.ReadByRecId_Result> ReadByRecIdAsync(RepositoryWebServiceTRH.PedidoListadoContext.ReadByRecId request);
        
        // CODEGEN: Se está generando un contrato de mensaje, ya que el nombre de contenedor (ReadMultiple_Result) del mensaje ReadMultiple_Result no coincide con el valor predeterminado (ReadMultiple)
        [System.ServiceModel.OperationContractAttribute(Action="urn:microsoft-dynamics-schemas/page/pedidolistado:ReadMultiple", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        RepositoryWebServiceTRH.PedidoListadoContext.ReadMultiple_Result ReadMultiple(RepositoryWebServiceTRH.PedidoListadoContext.ReadMultiple request);
        
        [System.ServiceModel.OperationContractAttribute(Action="urn:microsoft-dynamics-schemas/page/pedidolistado:ReadMultiple", ReplyAction="*")]
        System.Threading.Tasks.Task<RepositoryWebServiceTRH.PedidoListadoContext.ReadMultiple_Result> ReadMultipleAsync(RepositoryWebServiceTRH.PedidoListadoContext.ReadMultiple request);
        
        // CODEGEN: Se está generando un contrato de mensaje, ya que el nombre de contenedor (IsUpdated_Result) del mensaje IsUpdated_Result no coincide con el valor predeterminado (IsUpdated)
        [System.ServiceModel.OperationContractAttribute(Action="urn:microsoft-dynamics-schemas/page/pedidolistado:IsUpdated", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        RepositoryWebServiceTRH.PedidoListadoContext.IsUpdated_Result IsUpdated(RepositoryWebServiceTRH.PedidoListadoContext.IsUpdated request);
        
        [System.ServiceModel.OperationContractAttribute(Action="urn:microsoft-dynamics-schemas/page/pedidolistado:IsUpdated", ReplyAction="*")]
        System.Threading.Tasks.Task<RepositoryWebServiceTRH.PedidoListadoContext.IsUpdated_Result> IsUpdatedAsync(RepositoryWebServiceTRH.PedidoListadoContext.IsUpdated request);
        
        // CODEGEN: Se está generando un contrato de mensaje, ya que el nombre de contenedor (GetRecIdFromKey_Result) del mensaje GetRecIdFromKey_Result no coincide con el valor predeterminado (GetRecIdFromKey)
        [System.ServiceModel.OperationContractAttribute(Action="urn:microsoft-dynamics-schemas/page/pedidolistado:GetRecIdFromKey", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        RepositoryWebServiceTRH.PedidoListadoContext.GetRecIdFromKey_Result GetRecIdFromKey(RepositoryWebServiceTRH.PedidoListadoContext.GetRecIdFromKey request);
        
        [System.ServiceModel.OperationContractAttribute(Action="urn:microsoft-dynamics-schemas/page/pedidolistado:GetRecIdFromKey", ReplyAction="*")]
        System.Threading.Tasks.Task<RepositoryWebServiceTRH.PedidoListadoContext.GetRecIdFromKey_Result> GetRecIdFromKeyAsync(RepositoryWebServiceTRH.PedidoListadoContext.GetRecIdFromKey request);
    }
    
    /// <comentarios/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.6.1064.2")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="urn:microsoft-dynamics-schemas/page/pedidolistado")]
    public partial class PedidoListado : object, System.ComponentModel.INotifyPropertyChanged {
        
        private string keyField;
        
        private string noField;
        
        private string sell_to_Customer_NoField;
        
        private string sell_to_Customer_NameField;
        
        private string external_Document_NoField;
        
        private string sell_to_Post_CodeField;
        
        private string sell_to_Country_Region_CodeField;
        
        private string sell_to_ContactField;
        
        private string bill_to_Customer_NoField;
        
        private string bill_to_NameField;
        
        private string bill_to_Post_CodeField;
        
        private string bill_to_Country_Region_CodeField;
        
        private string bill_to_ContactField;
        
        private string ship_to_CodeField;
        
        private string ship_to_NameField;
        
        private string ship_to_Post_CodeField;
        
        private string ship_to_Country_Region_CodeField;
        
        private string ship_to_ContactField;
        
        private System.DateTime posting_DateField;
        
        private bool posting_DateFieldSpecified;
        
        private string location_CodeField;
        
        private string salesperson_CodeField;
        
        private System.DateTime document_DateField;
        
        private bool document_DateFieldSpecified;
        
        private string campaign_NoField;
        
        private string opportunity_NoField;
        
        private Status statusField;
        
        private bool statusFieldSpecified;
        
        /// <comentarios/>
        [System.Xml.Serialization.XmlElementAttribute(Order=0)]
        public string Key {
            get {
                return this.keyField;
            }
            set {
                this.keyField = value;
                this.RaisePropertyChanged("Key");
            }
        }
        
        /// <comentarios/>
        [System.Xml.Serialization.XmlElementAttribute(Order=1)]
        public string No {
            get {
                return this.noField;
            }
            set {
                this.noField = value;
                this.RaisePropertyChanged("No");
            }
        }
        
        /// <comentarios/>
        [System.Xml.Serialization.XmlElementAttribute(Order=2)]
        public string Sell_to_Customer_No {
            get {
                return this.sell_to_Customer_NoField;
            }
            set {
                this.sell_to_Customer_NoField = value;
                this.RaisePropertyChanged("Sell_to_Customer_No");
            }
        }
        
        /// <comentarios/>
        [System.Xml.Serialization.XmlElementAttribute(Order=3)]
        public string Sell_to_Customer_Name {
            get {
                return this.sell_to_Customer_NameField;
            }
            set {
                this.sell_to_Customer_NameField = value;
                this.RaisePropertyChanged("Sell_to_Customer_Name");
            }
        }
        
        /// <comentarios/>
        [System.Xml.Serialization.XmlElementAttribute(Order=4)]
        public string External_Document_No {
            get {
                return this.external_Document_NoField;
            }
            set {
                this.external_Document_NoField = value;
                this.RaisePropertyChanged("External_Document_No");
            }
        }
        
        /// <comentarios/>
        [System.Xml.Serialization.XmlElementAttribute(Order=5)]
        public string Sell_to_Post_Code {
            get {
                return this.sell_to_Post_CodeField;
            }
            set {
                this.sell_to_Post_CodeField = value;
                this.RaisePropertyChanged("Sell_to_Post_Code");
            }
        }
        
        /// <comentarios/>
        [System.Xml.Serialization.XmlElementAttribute(Order=6)]
        public string Sell_to_Country_Region_Code {
            get {
                return this.sell_to_Country_Region_CodeField;
            }
            set {
                this.sell_to_Country_Region_CodeField = value;
                this.RaisePropertyChanged("Sell_to_Country_Region_Code");
            }
        }
        
        /// <comentarios/>
        [System.Xml.Serialization.XmlElementAttribute(Order=7)]
        public string Sell_to_Contact {
            get {
                return this.sell_to_ContactField;
            }
            set {
                this.sell_to_ContactField = value;
                this.RaisePropertyChanged("Sell_to_Contact");
            }
        }
        
        /// <comentarios/>
        [System.Xml.Serialization.XmlElementAttribute(Order=8)]
        public string Bill_to_Customer_No {
            get {
                return this.bill_to_Customer_NoField;
            }
            set {
                this.bill_to_Customer_NoField = value;
                this.RaisePropertyChanged("Bill_to_Customer_No");
            }
        }
        
        /// <comentarios/>
        [System.Xml.Serialization.XmlElementAttribute(Order=9)]
        public string Bill_to_Name {
            get {
                return this.bill_to_NameField;
            }
            set {
                this.bill_to_NameField = value;
                this.RaisePropertyChanged("Bill_to_Name");
            }
        }
        
        /// <comentarios/>
        [System.Xml.Serialization.XmlElementAttribute(Order=10)]
        public string Bill_to_Post_Code {
            get {
                return this.bill_to_Post_CodeField;
            }
            set {
                this.bill_to_Post_CodeField = value;
                this.RaisePropertyChanged("Bill_to_Post_Code");
            }
        }
        
        /// <comentarios/>
        [System.Xml.Serialization.XmlElementAttribute(Order=11)]
        public string Bill_to_Country_Region_Code {
            get {
                return this.bill_to_Country_Region_CodeField;
            }
            set {
                this.bill_to_Country_Region_CodeField = value;
                this.RaisePropertyChanged("Bill_to_Country_Region_Code");
            }
        }
        
        /// <comentarios/>
        [System.Xml.Serialization.XmlElementAttribute(Order=12)]
        public string Bill_to_Contact {
            get {
                return this.bill_to_ContactField;
            }
            set {
                this.bill_to_ContactField = value;
                this.RaisePropertyChanged("Bill_to_Contact");
            }
        }
        
        /// <comentarios/>
        [System.Xml.Serialization.XmlElementAttribute(Order=13)]
        public string Ship_to_Code {
            get {
                return this.ship_to_CodeField;
            }
            set {
                this.ship_to_CodeField = value;
                this.RaisePropertyChanged("Ship_to_Code");
            }
        }
        
        /// <comentarios/>
        [System.Xml.Serialization.XmlElementAttribute(Order=14)]
        public string Ship_to_Name {
            get {
                return this.ship_to_NameField;
            }
            set {
                this.ship_to_NameField = value;
                this.RaisePropertyChanged("Ship_to_Name");
            }
        }
        
        /// <comentarios/>
        [System.Xml.Serialization.XmlElementAttribute(Order=15)]
        public string Ship_to_Post_Code {
            get {
                return this.ship_to_Post_CodeField;
            }
            set {
                this.ship_to_Post_CodeField = value;
                this.RaisePropertyChanged("Ship_to_Post_Code");
            }
        }
        
        /// <comentarios/>
        [System.Xml.Serialization.XmlElementAttribute(Order=16)]
        public string Ship_to_Country_Region_Code {
            get {
                return this.ship_to_Country_Region_CodeField;
            }
            set {
                this.ship_to_Country_Region_CodeField = value;
                this.RaisePropertyChanged("Ship_to_Country_Region_Code");
            }
        }
        
        /// <comentarios/>
        [System.Xml.Serialization.XmlElementAttribute(Order=17)]
        public string Ship_to_Contact {
            get {
                return this.ship_to_ContactField;
            }
            set {
                this.ship_to_ContactField = value;
                this.RaisePropertyChanged("Ship_to_Contact");
            }
        }
        
        /// <comentarios/>
        [System.Xml.Serialization.XmlElementAttribute(DataType="date", Order=18)]
        public System.DateTime Posting_Date {
            get {
                return this.posting_DateField;
            }
            set {
                this.posting_DateField = value;
                this.RaisePropertyChanged("Posting_Date");
            }
        }
        
        /// <comentarios/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool Posting_DateSpecified {
            get {
                return this.posting_DateFieldSpecified;
            }
            set {
                this.posting_DateFieldSpecified = value;
                this.RaisePropertyChanged("Posting_DateSpecified");
            }
        }
        
        /// <comentarios/>
        [System.Xml.Serialization.XmlElementAttribute(Order=19)]
        public string Location_Code {
            get {
                return this.location_CodeField;
            }
            set {
                this.location_CodeField = value;
                this.RaisePropertyChanged("Location_Code");
            }
        }
        
        /// <comentarios/>
        [System.Xml.Serialization.XmlElementAttribute(Order=20)]
        public string Salesperson_Code {
            get {
                return this.salesperson_CodeField;
            }
            set {
                this.salesperson_CodeField = value;
                this.RaisePropertyChanged("Salesperson_Code");
            }
        }
        
        /// <comentarios/>
        [System.Xml.Serialization.XmlElementAttribute(DataType="date", Order=21)]
        public System.DateTime Document_Date {
            get {
                return this.document_DateField;
            }
            set {
                this.document_DateField = value;
                this.RaisePropertyChanged("Document_Date");
            }
        }
        
        /// <comentarios/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool Document_DateSpecified {
            get {
                return this.document_DateFieldSpecified;
            }
            set {
                this.document_DateFieldSpecified = value;
                this.RaisePropertyChanged("Document_DateSpecified");
            }
        }
        
        /// <comentarios/>
        [System.Xml.Serialization.XmlElementAttribute(Order=22)]
        public string Campaign_No {
            get {
                return this.campaign_NoField;
            }
            set {
                this.campaign_NoField = value;
                this.RaisePropertyChanged("Campaign_No");
            }
        }
        
        /// <comentarios/>
        [System.Xml.Serialization.XmlElementAttribute(Order=23)]
        public string Opportunity_No {
            get {
                return this.opportunity_NoField;
            }
            set {
                this.opportunity_NoField = value;
                this.RaisePropertyChanged("Opportunity_No");
            }
        }
        
        /// <comentarios/>
        [System.Xml.Serialization.XmlElementAttribute(Order=24)]
        public Status Status {
            get {
                return this.statusField;
            }
            set {
                this.statusField = value;
                this.RaisePropertyChanged("Status");
            }
        }
        
        /// <comentarios/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool StatusSpecified {
            get {
                return this.statusFieldSpecified;
            }
            set {
                this.statusFieldSpecified = value;
                this.RaisePropertyChanged("StatusSpecified");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    /// <comentarios/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.6.1064.2")]
    [System.SerializableAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="urn:microsoft-dynamics-schemas/page/pedidolistado")]
    public enum Status {
        
        /// <comentarios/>
        Open,
        
        /// <comentarios/>
        Released,
        
        /// <comentarios/>
        Pending_Approval,
        
        /// <comentarios/>
        Pending_Prepayment,
    }
    
    /// <comentarios/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.6.1064.2")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="urn:microsoft-dynamics-schemas/page/pedidolistado")]
    public partial class PedidoListado_Filter : object, System.ComponentModel.INotifyPropertyChanged {
        
        private PedidoListado_Fields fieldField;
        
        private string criteriaField;
        
        /// <comentarios/>
        [System.Xml.Serialization.XmlElementAttribute(Order=0)]
        public PedidoListado_Fields Field {
            get {
                return this.fieldField;
            }
            set {
                this.fieldField = value;
                this.RaisePropertyChanged("Field");
            }
        }
        
        /// <comentarios/>
        [System.Xml.Serialization.XmlElementAttribute(Order=1)]
        public string Criteria {
            get {
                return this.criteriaField;
            }
            set {
                this.criteriaField = value;
                this.RaisePropertyChanged("Criteria");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    /// <comentarios/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.6.1064.2")]
    [System.SerializableAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="urn:microsoft-dynamics-schemas/page/pedidolistado")]
    public enum PedidoListado_Fields {
        
        /// <comentarios/>
        No,
        
        /// <comentarios/>
        Sell_to_Customer_No,
        
        /// <comentarios/>
        Sell_to_Customer_Name,
        
        /// <comentarios/>
        External_Document_No,
        
        /// <comentarios/>
        Sell_to_Post_Code,
        
        /// <comentarios/>
        Sell_to_Country_Region_Code,
        
        /// <comentarios/>
        Sell_to_Contact,
        
        /// <comentarios/>
        Bill_to_Customer_No,
        
        /// <comentarios/>
        Bill_to_Name,
        
        /// <comentarios/>
        Bill_to_Post_Code,
        
        /// <comentarios/>
        Bill_to_Country_Region_Code,
        
        /// <comentarios/>
        Bill_to_Contact,
        
        /// <comentarios/>
        Ship_to_Code,
        
        /// <comentarios/>
        Ship_to_Name,
        
        /// <comentarios/>
        Ship_to_Post_Code,
        
        /// <comentarios/>
        Ship_to_Country_Region_Code,
        
        /// <comentarios/>
        Ship_to_Contact,
        
        /// <comentarios/>
        Posting_Date,
        
        /// <comentarios/>
        Location_Code,
        
        /// <comentarios/>
        Salesperson_Code,
        
        /// <comentarios/>
        Document_Date,
        
        /// <comentarios/>
        Campaign_No,
        
        /// <comentarios/>
        Opportunity_No,
        
        /// <comentarios/>
        Status,
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="Read", WrapperNamespace="urn:microsoft-dynamics-schemas/page/pedidolistado", IsWrapped=true)]
    public partial class Read {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="urn:microsoft-dynamics-schemas/page/pedidolistado", Order=0)]
        public string No;
        
        public Read() {
        }
        
        public Read(string No) {
            this.No = No;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="Read_Result", WrapperNamespace="urn:microsoft-dynamics-schemas/page/pedidolistado", IsWrapped=true)]
    public partial class Read_Result {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="urn:microsoft-dynamics-schemas/page/pedidolistado", Order=0)]
        public RepositoryWebServiceTRH.PedidoListadoContext.PedidoListado PedidoListado;
        
        public Read_Result() {
        }
        
        public Read_Result(RepositoryWebServiceTRH.PedidoListadoContext.PedidoListado PedidoListado) {
            this.PedidoListado = PedidoListado;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="ReadByRecId", WrapperNamespace="urn:microsoft-dynamics-schemas/page/pedidolistado", IsWrapped=true)]
    public partial class ReadByRecId {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="urn:microsoft-dynamics-schemas/page/pedidolistado", Order=0)]
        public string recId;
        
        public ReadByRecId() {
        }
        
        public ReadByRecId(string recId) {
            this.recId = recId;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="ReadByRecId_Result", WrapperNamespace="urn:microsoft-dynamics-schemas/page/pedidolistado", IsWrapped=true)]
    public partial class ReadByRecId_Result {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="urn:microsoft-dynamics-schemas/page/pedidolistado", Order=0)]
        public RepositoryWebServiceTRH.PedidoListadoContext.PedidoListado PedidoListado;
        
        public ReadByRecId_Result() {
        }
        
        public ReadByRecId_Result(RepositoryWebServiceTRH.PedidoListadoContext.PedidoListado PedidoListado) {
            this.PedidoListado = PedidoListado;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="ReadMultiple", WrapperNamespace="urn:microsoft-dynamics-schemas/page/pedidolistado", IsWrapped=true)]
    public partial class ReadMultiple {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="urn:microsoft-dynamics-schemas/page/pedidolistado", Order=0)]
        [System.Xml.Serialization.XmlElementAttribute("filter")]
        public RepositoryWebServiceTRH.PedidoListadoContext.PedidoListado_Filter[] filter;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="urn:microsoft-dynamics-schemas/page/pedidolistado", Order=1)]
        public string bookmarkKey;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="urn:microsoft-dynamics-schemas/page/pedidolistado", Order=2)]
        public int setSize;
        
        public ReadMultiple() {
        }
        
        public ReadMultiple(RepositoryWebServiceTRH.PedidoListadoContext.PedidoListado_Filter[] filter, string bookmarkKey, int setSize) {
            this.filter = filter;
            this.bookmarkKey = bookmarkKey;
            this.setSize = setSize;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="ReadMultiple_Result", WrapperNamespace="urn:microsoft-dynamics-schemas/page/pedidolistado", IsWrapped=true)]
    public partial class ReadMultiple_Result {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="ReadMultiple_Result", Namespace="urn:microsoft-dynamics-schemas/page/pedidolistado", Order=0)]
        [System.Xml.Serialization.XmlArrayItemAttribute(IsNullable=false)]
        public RepositoryWebServiceTRH.PedidoListadoContext.PedidoListado[] ReadMultiple_Result1;
        
        public ReadMultiple_Result() {
        }
        
        public ReadMultiple_Result(RepositoryWebServiceTRH.PedidoListadoContext.PedidoListado[] ReadMultiple_Result1) {
            this.ReadMultiple_Result1 = ReadMultiple_Result1;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="IsUpdated", WrapperNamespace="urn:microsoft-dynamics-schemas/page/pedidolistado", IsWrapped=true)]
    public partial class IsUpdated {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="urn:microsoft-dynamics-schemas/page/pedidolistado", Order=0)]
        public string Key;
        
        public IsUpdated() {
        }
        
        public IsUpdated(string Key) {
            this.Key = Key;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="IsUpdated_Result", WrapperNamespace="urn:microsoft-dynamics-schemas/page/pedidolistado", IsWrapped=true)]
    public partial class IsUpdated_Result {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="IsUpdated_Result", Namespace="urn:microsoft-dynamics-schemas/page/pedidolistado", Order=0)]
        public bool IsUpdated_Result1;
        
        public IsUpdated_Result() {
        }
        
        public IsUpdated_Result(bool IsUpdated_Result1) {
            this.IsUpdated_Result1 = IsUpdated_Result1;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="GetRecIdFromKey", WrapperNamespace="urn:microsoft-dynamics-schemas/page/pedidolistado", IsWrapped=true)]
    public partial class GetRecIdFromKey {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="urn:microsoft-dynamics-schemas/page/pedidolistado", Order=0)]
        public string Key;
        
        public GetRecIdFromKey() {
        }
        
        public GetRecIdFromKey(string Key) {
            this.Key = Key;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="GetRecIdFromKey_Result", WrapperNamespace="urn:microsoft-dynamics-schemas/page/pedidolistado", IsWrapped=true)]
    public partial class GetRecIdFromKey_Result {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="GetRecIdFromKey_Result", Namespace="urn:microsoft-dynamics-schemas/page/pedidolistado", Order=0)]
        public string GetRecIdFromKey_Result1;
        
        public GetRecIdFromKey_Result() {
        }
        
        public GetRecIdFromKey_Result(string GetRecIdFromKey_Result1) {
            this.GetRecIdFromKey_Result1 = GetRecIdFromKey_Result1;
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface PedidoListado_PortChannel : RepositoryWebServiceTRH.PedidoListadoContext.PedidoListado_Port, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class PedidoListado_PortClient : System.ServiceModel.ClientBase<RepositoryWebServiceTRH.PedidoListadoContext.PedidoListado_Port>, RepositoryWebServiceTRH.PedidoListadoContext.PedidoListado_Port {
        
        public PedidoListado_PortClient() {
        }
        
        public PedidoListado_PortClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public PedidoListado_PortClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public PedidoListado_PortClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public PedidoListado_PortClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        RepositoryWebServiceTRH.PedidoListadoContext.Read_Result RepositoryWebServiceTRH.PedidoListadoContext.PedidoListado_Port.Read(RepositoryWebServiceTRH.PedidoListadoContext.Read request) {
            return base.Channel.Read(request);
        }
        
        public RepositoryWebServiceTRH.PedidoListadoContext.PedidoListado Read(string No) {
            RepositoryWebServiceTRH.PedidoListadoContext.Read inValue = new RepositoryWebServiceTRH.PedidoListadoContext.Read();
            inValue.No = No;
            RepositoryWebServiceTRH.PedidoListadoContext.Read_Result retVal = ((RepositoryWebServiceTRH.PedidoListadoContext.PedidoListado_Port)(this)).Read(inValue);
            return retVal.PedidoListado;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<RepositoryWebServiceTRH.PedidoListadoContext.Read_Result> RepositoryWebServiceTRH.PedidoListadoContext.PedidoListado_Port.ReadAsync(RepositoryWebServiceTRH.PedidoListadoContext.Read request) {
            return base.Channel.ReadAsync(request);
        }
        
        public System.Threading.Tasks.Task<RepositoryWebServiceTRH.PedidoListadoContext.Read_Result> ReadAsync(string No) {
            RepositoryWebServiceTRH.PedidoListadoContext.Read inValue = new RepositoryWebServiceTRH.PedidoListadoContext.Read();
            inValue.No = No;
            return ((RepositoryWebServiceTRH.PedidoListadoContext.PedidoListado_Port)(this)).ReadAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        RepositoryWebServiceTRH.PedidoListadoContext.ReadByRecId_Result RepositoryWebServiceTRH.PedidoListadoContext.PedidoListado_Port.ReadByRecId(RepositoryWebServiceTRH.PedidoListadoContext.ReadByRecId request) {
            return base.Channel.ReadByRecId(request);
        }
        
        public RepositoryWebServiceTRH.PedidoListadoContext.PedidoListado ReadByRecId(string recId) {
            RepositoryWebServiceTRH.PedidoListadoContext.ReadByRecId inValue = new RepositoryWebServiceTRH.PedidoListadoContext.ReadByRecId();
            inValue.recId = recId;
            RepositoryWebServiceTRH.PedidoListadoContext.ReadByRecId_Result retVal = ((RepositoryWebServiceTRH.PedidoListadoContext.PedidoListado_Port)(this)).ReadByRecId(inValue);
            return retVal.PedidoListado;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<RepositoryWebServiceTRH.PedidoListadoContext.ReadByRecId_Result> RepositoryWebServiceTRH.PedidoListadoContext.PedidoListado_Port.ReadByRecIdAsync(RepositoryWebServiceTRH.PedidoListadoContext.ReadByRecId request) {
            return base.Channel.ReadByRecIdAsync(request);
        }
        
        public System.Threading.Tasks.Task<RepositoryWebServiceTRH.PedidoListadoContext.ReadByRecId_Result> ReadByRecIdAsync(string recId) {
            RepositoryWebServiceTRH.PedidoListadoContext.ReadByRecId inValue = new RepositoryWebServiceTRH.PedidoListadoContext.ReadByRecId();
            inValue.recId = recId;
            return ((RepositoryWebServiceTRH.PedidoListadoContext.PedidoListado_Port)(this)).ReadByRecIdAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        RepositoryWebServiceTRH.PedidoListadoContext.ReadMultiple_Result RepositoryWebServiceTRH.PedidoListadoContext.PedidoListado_Port.ReadMultiple(RepositoryWebServiceTRH.PedidoListadoContext.ReadMultiple request) {
            return base.Channel.ReadMultiple(request);
        }
        
        public RepositoryWebServiceTRH.PedidoListadoContext.PedidoListado[] ReadMultiple(RepositoryWebServiceTRH.PedidoListadoContext.PedidoListado_Filter[] filter, string bookmarkKey, int setSize) {
            RepositoryWebServiceTRH.PedidoListadoContext.ReadMultiple inValue = new RepositoryWebServiceTRH.PedidoListadoContext.ReadMultiple();
            inValue.filter = filter;
            inValue.bookmarkKey = bookmarkKey;
            inValue.setSize = setSize;
            RepositoryWebServiceTRH.PedidoListadoContext.ReadMultiple_Result retVal = ((RepositoryWebServiceTRH.PedidoListadoContext.PedidoListado_Port)(this)).ReadMultiple(inValue);
            return retVal.ReadMultiple_Result1;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<RepositoryWebServiceTRH.PedidoListadoContext.ReadMultiple_Result> RepositoryWebServiceTRH.PedidoListadoContext.PedidoListado_Port.ReadMultipleAsync(RepositoryWebServiceTRH.PedidoListadoContext.ReadMultiple request) {
            return base.Channel.ReadMultipleAsync(request);
        }
        
        public System.Threading.Tasks.Task<RepositoryWebServiceTRH.PedidoListadoContext.ReadMultiple_Result> ReadMultipleAsync(RepositoryWebServiceTRH.PedidoListadoContext.PedidoListado_Filter[] filter, string bookmarkKey, int setSize) {
            RepositoryWebServiceTRH.PedidoListadoContext.ReadMultiple inValue = new RepositoryWebServiceTRH.PedidoListadoContext.ReadMultiple();
            inValue.filter = filter;
            inValue.bookmarkKey = bookmarkKey;
            inValue.setSize = setSize;
            return ((RepositoryWebServiceTRH.PedidoListadoContext.PedidoListado_Port)(this)).ReadMultipleAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        RepositoryWebServiceTRH.PedidoListadoContext.IsUpdated_Result RepositoryWebServiceTRH.PedidoListadoContext.PedidoListado_Port.IsUpdated(RepositoryWebServiceTRH.PedidoListadoContext.IsUpdated request) {
            return base.Channel.IsUpdated(request);
        }
        
        public bool IsUpdated(string Key) {
            RepositoryWebServiceTRH.PedidoListadoContext.IsUpdated inValue = new RepositoryWebServiceTRH.PedidoListadoContext.IsUpdated();
            inValue.Key = Key;
            RepositoryWebServiceTRH.PedidoListadoContext.IsUpdated_Result retVal = ((RepositoryWebServiceTRH.PedidoListadoContext.PedidoListado_Port)(this)).IsUpdated(inValue);
            return retVal.IsUpdated_Result1;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<RepositoryWebServiceTRH.PedidoListadoContext.IsUpdated_Result> RepositoryWebServiceTRH.PedidoListadoContext.PedidoListado_Port.IsUpdatedAsync(RepositoryWebServiceTRH.PedidoListadoContext.IsUpdated request) {
            return base.Channel.IsUpdatedAsync(request);
        }
        
        public System.Threading.Tasks.Task<RepositoryWebServiceTRH.PedidoListadoContext.IsUpdated_Result> IsUpdatedAsync(string Key) {
            RepositoryWebServiceTRH.PedidoListadoContext.IsUpdated inValue = new RepositoryWebServiceTRH.PedidoListadoContext.IsUpdated();
            inValue.Key = Key;
            return ((RepositoryWebServiceTRH.PedidoListadoContext.PedidoListado_Port)(this)).IsUpdatedAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        RepositoryWebServiceTRH.PedidoListadoContext.GetRecIdFromKey_Result RepositoryWebServiceTRH.PedidoListadoContext.PedidoListado_Port.GetRecIdFromKey(RepositoryWebServiceTRH.PedidoListadoContext.GetRecIdFromKey request) {
            return base.Channel.GetRecIdFromKey(request);
        }
        
        public string GetRecIdFromKey(string Key) {
            RepositoryWebServiceTRH.PedidoListadoContext.GetRecIdFromKey inValue = new RepositoryWebServiceTRH.PedidoListadoContext.GetRecIdFromKey();
            inValue.Key = Key;
            RepositoryWebServiceTRH.PedidoListadoContext.GetRecIdFromKey_Result retVal = ((RepositoryWebServiceTRH.PedidoListadoContext.PedidoListado_Port)(this)).GetRecIdFromKey(inValue);
            return retVal.GetRecIdFromKey_Result1;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<RepositoryWebServiceTRH.PedidoListadoContext.GetRecIdFromKey_Result> RepositoryWebServiceTRH.PedidoListadoContext.PedidoListado_Port.GetRecIdFromKeyAsync(RepositoryWebServiceTRH.PedidoListadoContext.GetRecIdFromKey request) {
            return base.Channel.GetRecIdFromKeyAsync(request);
        }
        
        public System.Threading.Tasks.Task<RepositoryWebServiceTRH.PedidoListadoContext.GetRecIdFromKey_Result> GetRecIdFromKeyAsync(string Key) {
            RepositoryWebServiceTRH.PedidoListadoContext.GetRecIdFromKey inValue = new RepositoryWebServiceTRH.PedidoListadoContext.GetRecIdFromKey();
            inValue.Key = Key;
            return ((RepositoryWebServiceTRH.PedidoListadoContext.PedidoListado_Port)(this)).GetRecIdFromKeyAsync(inValue);
        }
    }
}
