//------------------------------------------------------------------------------
// <auto-generated>
//     Este código fue generado por una herramienta.
//     Versión de runtime:4.0.30319.42000
//
//     Los cambios en este archivo podrían causar un comportamiento incorrecto y se perderán si
//     se vuelve a generar el código.
// </auto-generated>
//------------------------------------------------------------------------------

using System.Runtime.Serialization;

namespace RepositoryWebServiceTRH.EntregaAlmacenEpisContext {
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(Namespace="urn:microsoft-dynamics-schemas/page/entregaalmacen", ConfigurationName="EntregaAlmacenEpisContext.EntregaAlmacen_Port")]
    public interface EntregaAlmacen_Port {
        
        // CODEGEN: Se está generando un contrato de mensaje, ya que el nombre de contenedor (Read_Result) del mensaje Read_Result no coincide con el valor predeterminado (Read)
        [System.ServiceModel.OperationContractAttribute(Action="urn:microsoft-dynamics-schemas/page/entregaalmacen:Read", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        RepositoryWebServiceTRH.EntregaAlmacenEpisContext.Read_Result Read(RepositoryWebServiceTRH.EntregaAlmacenEpisContext.Read request);
        
        [System.ServiceModel.OperationContractAttribute(Action="urn:microsoft-dynamics-schemas/page/entregaalmacen:Read", ReplyAction="*")]
        System.Threading.Tasks.Task<RepositoryWebServiceTRH.EntregaAlmacenEpisContext.Read_Result> ReadAsync(RepositoryWebServiceTRH.EntregaAlmacenEpisContext.Read request);
        
        // CODEGEN: Se está generando un contrato de mensaje, ya que el nombre de contenedor (ReadByRecId_Result) del mensaje ReadByRecId_Result no coincide con el valor predeterminado (ReadByRecId)
        [System.ServiceModel.OperationContractAttribute(Action="urn:microsoft-dynamics-schemas/page/entregaalmacen:ReadByRecId", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        RepositoryWebServiceTRH.EntregaAlmacenEpisContext.ReadByRecId_Result ReadByRecId(RepositoryWebServiceTRH.EntregaAlmacenEpisContext.ReadByRecId request);
        
        [System.ServiceModel.OperationContractAttribute(Action="urn:microsoft-dynamics-schemas/page/entregaalmacen:ReadByRecId", ReplyAction="*")]
        System.Threading.Tasks.Task<RepositoryWebServiceTRH.EntregaAlmacenEpisContext.ReadByRecId_Result> ReadByRecIdAsync(RepositoryWebServiceTRH.EntregaAlmacenEpisContext.ReadByRecId request);
        
        // CODEGEN: Se está generando un contrato de mensaje, ya que el nombre de contenedor (ReadMultiple_Result) del mensaje ReadMultiple_Result no coincide con el valor predeterminado (ReadMultiple)
        [System.ServiceModel.OperationContractAttribute(Action="urn:microsoft-dynamics-schemas/page/entregaalmacen:ReadMultiple", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        RepositoryWebServiceTRH.EntregaAlmacenEpisContext.ReadMultiple_Result ReadMultiple(RepositoryWebServiceTRH.EntregaAlmacenEpisContext.ReadMultiple request);
        
        [System.ServiceModel.OperationContractAttribute(Action="urn:microsoft-dynamics-schemas/page/entregaalmacen:ReadMultiple", ReplyAction="*")]
        System.Threading.Tasks.Task<RepositoryWebServiceTRH.EntregaAlmacenEpisContext.ReadMultiple_Result> ReadMultipleAsync(RepositoryWebServiceTRH.EntregaAlmacenEpisContext.ReadMultiple request);
        
        // CODEGEN: Se está generando un contrato de mensaje, ya que el nombre de contenedor (IsUpdated_Result) del mensaje IsUpdated_Result no coincide con el valor predeterminado (IsUpdated)
        [System.ServiceModel.OperationContractAttribute(Action="urn:microsoft-dynamics-schemas/page/entregaalmacen:IsUpdated", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        RepositoryWebServiceTRH.EntregaAlmacenEpisContext.IsUpdated_Result IsUpdated(RepositoryWebServiceTRH.EntregaAlmacenEpisContext.IsUpdated request);
        
        [System.ServiceModel.OperationContractAttribute(Action="urn:microsoft-dynamics-schemas/page/entregaalmacen:IsUpdated", ReplyAction="*")]
        System.Threading.Tasks.Task<RepositoryWebServiceTRH.EntregaAlmacenEpisContext.IsUpdated_Result> IsUpdatedAsync(RepositoryWebServiceTRH.EntregaAlmacenEpisContext.IsUpdated request);
        
        // CODEGEN: Se está generando un contrato de mensaje, ya que el nombre de contenedor (GetRecIdFromKey_Result) del mensaje GetRecIdFromKey_Result no coincide con el valor predeterminado (GetRecIdFromKey)
        [System.ServiceModel.OperationContractAttribute(Action="urn:microsoft-dynamics-schemas/page/entregaalmacen:GetRecIdFromKey", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        RepositoryWebServiceTRH.EntregaAlmacenEpisContext.GetRecIdFromKey_Result GetRecIdFromKey(RepositoryWebServiceTRH.EntregaAlmacenEpisContext.GetRecIdFromKey request);
        
        [System.ServiceModel.OperationContractAttribute(Action="urn:microsoft-dynamics-schemas/page/entregaalmacen:GetRecIdFromKey", ReplyAction="*")]
        System.Threading.Tasks.Task<RepositoryWebServiceTRH.EntregaAlmacenEpisContext.GetRecIdFromKey_Result> GetRecIdFromKeyAsync(RepositoryWebServiceTRH.EntregaAlmacenEpisContext.GetRecIdFromKey request);
        
        [System.ServiceModel.OperationContractAttribute(Action="urn:microsoft-dynamics-schemas/page/entregaalmacen:Create", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        RepositoryWebServiceTRH.EntregaAlmacenEpisContext.Create_Result Create(RepositoryWebServiceTRH.EntregaAlmacenEpisContext.Create request);
        
        // CODEGEN: Generando contrato de mensaje, ya que la operación tiene múltiples valores de devolución.
        [System.ServiceModel.OperationContractAttribute(Action="urn:microsoft-dynamics-schemas/page/entregaalmacen:Create", ReplyAction="*")]
        System.Threading.Tasks.Task<RepositoryWebServiceTRH.EntregaAlmacenEpisContext.Create_Result> CreateAsync(RepositoryWebServiceTRH.EntregaAlmacenEpisContext.Create request);
        
        [System.ServiceModel.OperationContractAttribute(Action="urn:microsoft-dynamics-schemas/page/entregaalmacen:CreateMultiple", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        RepositoryWebServiceTRH.EntregaAlmacenEpisContext.CreateMultiple_Result CreateMultiple(RepositoryWebServiceTRH.EntregaAlmacenEpisContext.CreateMultiple request);
        
        // CODEGEN: Generando contrato de mensaje, ya que la operación tiene múltiples valores de devolución.
        [System.ServiceModel.OperationContractAttribute(Action="urn:microsoft-dynamics-schemas/page/entregaalmacen:CreateMultiple", ReplyAction="*")]
        System.Threading.Tasks.Task<RepositoryWebServiceTRH.EntregaAlmacenEpisContext.CreateMultiple_Result> CreateMultipleAsync(RepositoryWebServiceTRH.EntregaAlmacenEpisContext.CreateMultiple request);
        
        [System.ServiceModel.OperationContractAttribute(Action="urn:microsoft-dynamics-schemas/page/entregaalmacen:Update", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        RepositoryWebServiceTRH.EntregaAlmacenEpisContext.Update_Result Update(RepositoryWebServiceTRH.EntregaAlmacenEpisContext.Update request);
        
        // CODEGEN: Generando contrato de mensaje, ya que la operación tiene múltiples valores de devolución.
        [System.ServiceModel.OperationContractAttribute(Action="urn:microsoft-dynamics-schemas/page/entregaalmacen:Update", ReplyAction="*")]
        System.Threading.Tasks.Task<RepositoryWebServiceTRH.EntregaAlmacenEpisContext.Update_Result> UpdateAsync(RepositoryWebServiceTRH.EntregaAlmacenEpisContext.Update request);
        
        [System.ServiceModel.OperationContractAttribute(Action="urn:microsoft-dynamics-schemas/page/entregaalmacen:UpdateMultiple", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        RepositoryWebServiceTRH.EntregaAlmacenEpisContext.UpdateMultiple_Result UpdateMultiple(RepositoryWebServiceTRH.EntregaAlmacenEpisContext.UpdateMultiple request);
        
        // CODEGEN: Generando contrato de mensaje, ya que la operación tiene múltiples valores de devolución.
        [System.ServiceModel.OperationContractAttribute(Action="urn:microsoft-dynamics-schemas/page/entregaalmacen:UpdateMultiple", ReplyAction="*")]
        System.Threading.Tasks.Task<RepositoryWebServiceTRH.EntregaAlmacenEpisContext.UpdateMultiple_Result> UpdateMultipleAsync(RepositoryWebServiceTRH.EntregaAlmacenEpisContext.UpdateMultiple request);
        
        // CODEGEN: Se está generando un contrato de mensaje, ya que el nombre de contenedor (Delete_Result) del mensaje Delete_Result no coincide con el valor predeterminado (Delete)
        [System.ServiceModel.OperationContractAttribute(Action="urn:microsoft-dynamics-schemas/page/entregaalmacen:Delete", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        RepositoryWebServiceTRH.EntregaAlmacenEpisContext.Delete_Result Delete(RepositoryWebServiceTRH.EntregaAlmacenEpisContext.Delete request);
        
        [System.ServiceModel.OperationContractAttribute(Action="urn:microsoft-dynamics-schemas/page/entregaalmacen:Delete", ReplyAction="*")]
        System.Threading.Tasks.Task<RepositoryWebServiceTRH.EntregaAlmacenEpisContext.Delete_Result> DeleteAsync(RepositoryWebServiceTRH.EntregaAlmacenEpisContext.Delete request);
    }
    
    /// <comentarios/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.6.1064.2")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="urn:microsoft-dynamics-schemas/page/entregaalmacen")]
    [DataContract]
    public partial class EntregaAlmacen : object, System.ComponentModel.INotifyPropertyChanged {
        [DataMember]
        private string keyField;
        [DataMember]
        private string cod_EmpleadoField;
        [DataMember]
        private string cod_ProductoField;
        [DataMember]
        private decimal inventoryField;
        [DataMember]
        private bool inventoryFieldSpecified;
        [DataMember]
        private string descripcion_ProductoField;
        [DataMember]
        private System.DateTime fechaField;
        [DataMember]
        private bool fechaFieldSpecified;
        [DataMember]
        private int cantidadField;
        [DataMember]
        private bool cantidadFieldSpecified;
        [DataMember]
        private string unit_of_Measure_CodeField;
        [DataMember]
        private string no_DocumentoField;
        [DataMember]
        private string comentarioField;
        [DataMember]
        private string cod_AlmacenField;
        [DataMember]
        private bool entregadoField;
        [DataMember]
        private bool entregadoFieldSpecified;
        [DataMember]
        private bool epiField;
        [DataMember]
        private bool epiFieldSpecified;
        [DataMember]
        private int no_LineaField;
        [DataMember]
        private bool no_LineaFieldSpecified;
        [DataMember]
        private Destino destinoField;
        [DataMember]
        private bool destinoFieldSpecified;
        [DataMember]
        private Maquina maquinaField;
        [DataMember]
        private bool maquinaFieldSpecified;
        
        /// <comentarios/>
        [System.Xml.Serialization.XmlElementAttribute(Order=0)]
        [DataMember]
        public string Key {
            get {
                return this.keyField;
            }
            set {
                this.keyField = value;
                this.RaisePropertyChanged("Key");
            }
        }
        
        /// <comentarios/>
        [System.Xml.Serialization.XmlElementAttribute(Order=1)]
        [DataMember]
        public string Cod_Empleado {
            get {
                return this.cod_EmpleadoField;
            }
            set {
                this.cod_EmpleadoField = value;
                this.RaisePropertyChanged("Cod_Empleado");
            }
        }
        
        /// <comentarios/>
        [System.Xml.Serialization.XmlElementAttribute(Order=2)]
        [DataMember]
        public string Cod_Producto {
            get {
                return this.cod_ProductoField;
            }
            set {
                this.cod_ProductoField = value;
                this.RaisePropertyChanged("Cod_Producto");
            }
        }
        
        /// <comentarios/>
        [System.Xml.Serialization.XmlElementAttribute(Order=3)]
        [DataMember]
        public decimal Inventory {
            get {
                return this.inventoryField;
            }
            set {
                this.inventoryField = value;
                this.RaisePropertyChanged("Inventory");
            }
        }
        
        /// <comentarios/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        [DataMember]
        public bool InventorySpecified {
            get {
                return this.inventoryFieldSpecified;
            }
            set {
                this.inventoryFieldSpecified = value;
                this.RaisePropertyChanged("InventorySpecified");
            }
        }
        
        /// <comentarios/>
        [System.Xml.Serialization.XmlElementAttribute("<Descripcion_Producto>", Order=4)]
        [DataMember]
        public string Descripcion_Producto {
            get {
                return this.descripcion_ProductoField;
            }
            set {
                this.descripcion_ProductoField = value;
                this.RaisePropertyChanged("Descripcion_Producto");
            }
        }
        
        /// <comentarios/>
        [System.Xml.Serialization.XmlElementAttribute(DataType="date", Order=5)]
        [DataMember]
        public System.DateTime Fecha {
            get {
                return this.fechaField;
            }
            set {
                this.fechaField = value;
                this.RaisePropertyChanged("Fecha");
            }
        }
        
        /// <comentarios/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        [DataMember]
        public bool FechaSpecified {
            get {
                return this.fechaFieldSpecified;
            }
            set {
                this.fechaFieldSpecified = value;
                this.RaisePropertyChanged("FechaSpecified");
            }
        }
        
        /// <comentarios/>
        [System.Xml.Serialization.XmlElementAttribute(Order=6)]
        [DataMember]
        public int Cantidad {
            get {
                return this.cantidadField;
            }
            set {
                this.cantidadField = value;
                this.RaisePropertyChanged("Cantidad");
            }
        }
        
        /// <comentarios/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        [DataMember]
        public bool CantidadSpecified {
            get {
                return this.cantidadFieldSpecified;
            }
            set {
                this.cantidadFieldSpecified = value;
                this.RaisePropertyChanged("CantidadSpecified");
            }
        }
        
        /// <comentarios/>
        [System.Xml.Serialization.XmlElementAttribute(Order=7)]
        [DataMember]
        public string Unit_of_Measure_Code {
            get {
                return this.unit_of_Measure_CodeField;
            }
            set {
                this.unit_of_Measure_CodeField = value;
                this.RaisePropertyChanged("Unit_of_Measure_Code");
            }
        }
        
        /// <comentarios/>
        [System.Xml.Serialization.XmlElementAttribute(Order=8)]
        [DataMember]
        public string No_Documento {
            get {
                return this.no_DocumentoField;
            }
            set {
                this.no_DocumentoField = value;
                this.RaisePropertyChanged("No_Documento");
            }
        }
        
        /// <comentarios/>
        [System.Xml.Serialization.XmlElementAttribute(Order=9)]
        [DataMember]
        public string Comentario {
            get {
                return this.comentarioField;
            }
            set {
                this.comentarioField = value;
                this.RaisePropertyChanged("Comentario");
            }
        }
        
        /// <comentarios/>
        [System.Xml.Serialization.XmlElementAttribute(Order=10)]
        [DataMember]
        public string Cod_Almacen {
            get {
                return this.cod_AlmacenField;
            }
            set {
                this.cod_AlmacenField = value;
                this.RaisePropertyChanged("Cod_Almacen");
            }
        }
        
        /// <comentarios/>
        [System.Xml.Serialization.XmlElementAttribute(Order=11)]
        [DataMember]
        public bool Entregado {
            get {
                return this.entregadoField;
            }
            set {
                this.entregadoField = value;
                this.RaisePropertyChanged("Entregado");
            }
        }
        
        /// <comentarios/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        [DataMember]
        public bool EntregadoSpecified {
            get {
                return this.entregadoFieldSpecified;
            }
            set {
                this.entregadoFieldSpecified = value;
                this.RaisePropertyChanged("EntregadoSpecified");
            }
        }
        
        /// <comentarios/>
        [System.Xml.Serialization.XmlElementAttribute(Order=12)]
        [DataMember]
        public bool Epi {
            get {
                return this.epiField;
            }
            set {
                this.epiField = value;
                this.RaisePropertyChanged("Epi");
            }
        }
        
        /// <comentarios/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        [DataMember]
        public bool EpiSpecified {
            get {
                return this.epiFieldSpecified;
            }
            set {
                this.epiFieldSpecified = value;
                this.RaisePropertyChanged("EpiSpecified");
            }
        }
        
        /// <comentarios/>
        [System.Xml.Serialization.XmlElementAttribute(Order=13)]
        [DataMember]
        public int No_Linea {
            get {
                return this.no_LineaField;
            }
            set {
                this.no_LineaField = value;
                this.RaisePropertyChanged("No_Linea");
            }
        }
        
        /// <comentarios/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        [DataMember]
        public bool No_LineaSpecified {
            get {
                return this.no_LineaFieldSpecified;
            }
            set {
                this.no_LineaFieldSpecified = value;
                this.RaisePropertyChanged("No_LineaSpecified");
            }
        }
        
        /// <comentarios/>
        [System.Xml.Serialization.XmlElementAttribute(Order=14)]
        [DataMember]
        public Destino Destino {
            get {
                return this.destinoField;
            }
            set {
                this.destinoField = value;
                this.RaisePropertyChanged("Destino");
            }
        }
        
        /// <comentarios/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        [DataMember]
        public bool DestinoSpecified {
            get {
                return this.destinoFieldSpecified;
            }
            set {
                this.destinoFieldSpecified = value;
                this.RaisePropertyChanged("DestinoSpecified");
            }
        }
        
        /// <comentarios/>
        [System.Xml.Serialization.XmlElementAttribute(Order=15)]
        [DataMember]
        public Maquina Maquina {
            get {
                return this.maquinaField;
            }
            set {
                this.maquinaField = value;
                this.RaisePropertyChanged("Maquina");
            }
        }
        
        /// <comentarios/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        [DataMember]
        public bool MaquinaSpecified {
            get {
                return this.maquinaFieldSpecified;
            }
            set {
                this.maquinaFieldSpecified = value;
                this.RaisePropertyChanged("MaquinaSpecified");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    /// <comentarios/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.6.1064.2")]
    [System.SerializableAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="urn:microsoft-dynamics-schemas/page/entregaalmacen")]
    public enum Destino {
        
        /// <comentarios/>
        _blank_,
        
        /// <comentarios/>
        Taller_Mecánico,
        
        /// <comentarios/>
        Taller_Eléctrico,
        
        /// <comentarios/>
        Máquina,
        
        /// <comentarios/>
        Sevilla,
        
        /// <comentarios/>
        Liege,
        
        /// <comentarios/>
        Servicios_Generales,
        
        /// <comentarios/>
        Otros,
    }
    
    /// <comentarios/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.6.1064.2")]
    [System.SerializableAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="urn:microsoft-dynamics-schemas/page/entregaalmacen")]
    ///Sevilla
    //public enum Maquina
    //{

    //    /// <comentarios/>
    //    _blank_,

    //    /// <comentarios/>
    //    M1,

    //    /// <comentarios/>
    //    M2,

    //    /// <comentarios/>
    //    M3,

    //    /// <comentarios/>
    //    M4,

    //    /// <comentarios/>
    //    R1,

    //    /// <comentarios/>
    //    R2,

    //    /// <comentarios/>
    //    E1,

    //    /// <comentarios/>
    //    E2,

    //    /// <comentarios/>
    //    T1,

    //    /// <comentarios/>
    //    T2,

    //    /// <comentarios/>
    //    T3,

    //    /// <comentarios/>
    //    T4,

    //    /// <comentarios/>
    //    T5,

    //    /// <comentarios/>
    //    T6,

    //    /// <comentarios/>
    //    T7,

    //    /// <comentarios/>
    //    T8,
    //}
    /////Lieja
    public enum Maquina
    {

        /// <comentarios/>
        _blank_,

        /// <comentarios/>
        M5,

        /// <comentarios/>
        M6,

        /// <comentarios/>
        M7,

        /// <comentarios/>
        M8,

        /// <comentarios/>
        R3,

        /// <comentarios/>
        R4,

        /// <comentarios/>
        E3,

        /// <comentarios/>
        E4,

        /// <comentarios/>
        T9,

        /// <comentarios/>
        T10,

        /// <comentarios/>
        T11,

        /// <comentarios/>
        T12,

        /// <comentarios/>
        T13,

        /// <comentarios/>
        T14,

        /// <comentarios/>
        T15


    }

    public enum Empresas
    {

        /// <comentarios/>
        Sevilla,

        /// <comentarios/>
        Liege,

        


    }
    /// <comentarios/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.6.1064.2")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="urn:microsoft-dynamics-schemas/page/entregaalmacen")]
    public partial class EntregaAlmacen_Filter : object, System.ComponentModel.INotifyPropertyChanged {
        
        private EntregaAlmacen_Fields fieldField;
        
        private string criteriaField;
        
        /// <comentarios/>
        [System.Xml.Serialization.XmlElementAttribute(Order=0)]
        public EntregaAlmacen_Fields Field {
            get {
                return this.fieldField;
            }
            set {
                this.fieldField = value;
                this.RaisePropertyChanged("Field");
            }
        }
        
        /// <comentarios/>
        [System.Xml.Serialization.XmlElementAttribute(Order=1)]
        public string Criteria {
            get {
                return this.criteriaField;
            }
            set {
                this.criteriaField = value;
                this.RaisePropertyChanged("Criteria");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    /// <comentarios/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.6.1064.2")]
    [System.SerializableAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="urn:microsoft-dynamics-schemas/page/entregaalmacen")]
    public enum EntregaAlmacen_Fields {
        
        /// <comentarios/>
        Cod_Empleado,
        
        /// <comentarios/>
        Cod_Producto,
        
        /// <comentarios/>
        Inventory,
        
        /// <comentarios/>
        _x003C_Descripcion_Producto_x003E_,
        
        /// <comentarios/>
        Fecha,
        
        /// <comentarios/>
        Cantidad,
        
        /// <comentarios/>
        Unit_of_Measure_Code,
        
        /// <comentarios/>
        No_Documento,
        
        /// <comentarios/>
        Comentario,
        
        /// <comentarios/>
        Cod_Almacen,
        
        /// <comentarios/>
        Entregado,
        
        /// <comentarios/>
        Epi,
        
        /// <comentarios/>
        No_Linea,
        
        /// <comentarios/>
        Destino,
        
        /// <comentarios/>
        Maquina,
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="Read", WrapperNamespace="urn:microsoft-dynamics-schemas/page/entregaalmacen", IsWrapped=true)]
    public partial class Read {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="urn:microsoft-dynamics-schemas/page/entregaalmacen", Order=0)]
        public string Cod_Empleado;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="urn:microsoft-dynamics-schemas/page/entregaalmacen", Order=1)]
        public string Cod_Producto;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="urn:microsoft-dynamics-schemas/page/entregaalmacen", Order=2)]
        [System.Xml.Serialization.XmlElementAttribute(DataType="date")]
        public System.DateTime Fecha;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="urn:microsoft-dynamics-schemas/page/entregaalmacen", Order=3)]
        public int No_Linea;
        
        public Read() {
        }
        
        public Read(string Cod_Empleado, string Cod_Producto, System.DateTime Fecha, int No_Linea) {
            this.Cod_Empleado = Cod_Empleado;
            this.Cod_Producto = Cod_Producto;
            this.Fecha = Fecha;
            this.No_Linea = No_Linea;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="Read_Result", WrapperNamespace="urn:microsoft-dynamics-schemas/page/entregaalmacen", IsWrapped=true)]
    public partial class Read_Result {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="urn:microsoft-dynamics-schemas/page/entregaalmacen", Order=0)]
        public RepositoryWebServiceTRH.EntregaAlmacenEpisContext.EntregaAlmacen EntregaAlmacen;
        
        public Read_Result() {
        }
        
        public Read_Result(RepositoryWebServiceTRH.EntregaAlmacenEpisContext.EntregaAlmacen EntregaAlmacen) {
            this.EntregaAlmacen = EntregaAlmacen;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="ReadByRecId", WrapperNamespace="urn:microsoft-dynamics-schemas/page/entregaalmacen", IsWrapped=true)]
    public partial class ReadByRecId {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="urn:microsoft-dynamics-schemas/page/entregaalmacen", Order=0)]
        public string recId;
        
        public ReadByRecId() {
        }
        
        public ReadByRecId(string recId) {
            this.recId = recId;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="ReadByRecId_Result", WrapperNamespace="urn:microsoft-dynamics-schemas/page/entregaalmacen", IsWrapped=true)]
    public partial class ReadByRecId_Result {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="urn:microsoft-dynamics-schemas/page/entregaalmacen", Order=0)]
        public RepositoryWebServiceTRH.EntregaAlmacenEpisContext.EntregaAlmacen EntregaAlmacen;
        
        public ReadByRecId_Result() {
        }
        
        public ReadByRecId_Result(RepositoryWebServiceTRH.EntregaAlmacenEpisContext.EntregaAlmacen EntregaAlmacen) {
            this.EntregaAlmacen = EntregaAlmacen;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="ReadMultiple", WrapperNamespace="urn:microsoft-dynamics-schemas/page/entregaalmacen", IsWrapped=true)]
    public partial class ReadMultiple {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="urn:microsoft-dynamics-schemas/page/entregaalmacen", Order=0)]
        [System.Xml.Serialization.XmlElementAttribute("filter")]
        public RepositoryWebServiceTRH.EntregaAlmacenEpisContext.EntregaAlmacen_Filter[] filter;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="urn:microsoft-dynamics-schemas/page/entregaalmacen", Order=1)]
        public string bookmarkKey;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="urn:microsoft-dynamics-schemas/page/entregaalmacen", Order=2)]
        public int setSize;
        
        public ReadMultiple() {
        }
        
        public ReadMultiple(RepositoryWebServiceTRH.EntregaAlmacenEpisContext.EntregaAlmacen_Filter[] filter, string bookmarkKey, int setSize) {
            this.filter = filter;
            this.bookmarkKey = bookmarkKey;
            this.setSize = setSize;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="ReadMultiple_Result", WrapperNamespace="urn:microsoft-dynamics-schemas/page/entregaalmacen", IsWrapped=true)]
    public partial class ReadMultiple_Result {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="ReadMultiple_Result", Namespace="urn:microsoft-dynamics-schemas/page/entregaalmacen", Order=0)]
        [System.Xml.Serialization.XmlArrayItemAttribute(IsNullable=false)]
        public RepositoryWebServiceTRH.EntregaAlmacenEpisContext.EntregaAlmacen[] ReadMultiple_Result1;
        
        public ReadMultiple_Result() {
        }
        
        public ReadMultiple_Result(RepositoryWebServiceTRH.EntregaAlmacenEpisContext.EntregaAlmacen[] ReadMultiple_Result1) {
            this.ReadMultiple_Result1 = ReadMultiple_Result1;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="IsUpdated", WrapperNamespace="urn:microsoft-dynamics-schemas/page/entregaalmacen", IsWrapped=true)]
    public partial class IsUpdated {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="urn:microsoft-dynamics-schemas/page/entregaalmacen", Order=0)]
        public string Key;
        
        public IsUpdated() {
        }
        
        public IsUpdated(string Key) {
            this.Key = Key;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="IsUpdated_Result", WrapperNamespace="urn:microsoft-dynamics-schemas/page/entregaalmacen", IsWrapped=true)]
    public partial class IsUpdated_Result {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="IsUpdated_Result", Namespace="urn:microsoft-dynamics-schemas/page/entregaalmacen", Order=0)]
        public bool IsUpdated_Result1;
        
        public IsUpdated_Result() {
        }
        
        public IsUpdated_Result(bool IsUpdated_Result1) {
            this.IsUpdated_Result1 = IsUpdated_Result1;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="GetRecIdFromKey", WrapperNamespace="urn:microsoft-dynamics-schemas/page/entregaalmacen", IsWrapped=true)]
    public partial class GetRecIdFromKey {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="urn:microsoft-dynamics-schemas/page/entregaalmacen", Order=0)]
        public string Key;
        
        public GetRecIdFromKey() {
        }
        
        public GetRecIdFromKey(string Key) {
            this.Key = Key;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="GetRecIdFromKey_Result", WrapperNamespace="urn:microsoft-dynamics-schemas/page/entregaalmacen", IsWrapped=true)]
    public partial class GetRecIdFromKey_Result {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="GetRecIdFromKey_Result", Namespace="urn:microsoft-dynamics-schemas/page/entregaalmacen", Order=0)]
        public string GetRecIdFromKey_Result1;
        
        public GetRecIdFromKey_Result() {
        }
        
        public GetRecIdFromKey_Result(string GetRecIdFromKey_Result1) {
            this.GetRecIdFromKey_Result1 = GetRecIdFromKey_Result1;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.MessageContractAttribute(WrapperName="Create", WrapperNamespace="urn:microsoft-dynamics-schemas/page/entregaalmacen", IsWrapped=true)]
    public partial class Create {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="urn:microsoft-dynamics-schemas/page/entregaalmacen", Order=0)]
        public RepositoryWebServiceTRH.EntregaAlmacenEpisContext.EntregaAlmacen EntregaAlmacen;
        
        public Create() {
        }
        
        public Create(RepositoryWebServiceTRH.EntregaAlmacenEpisContext.EntregaAlmacen EntregaAlmacen) {
            this.EntregaAlmacen = EntregaAlmacen;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.MessageContractAttribute(WrapperName="Create_Result", WrapperNamespace="urn:microsoft-dynamics-schemas/page/entregaalmacen", IsWrapped=true)]
    public partial class Create_Result {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="urn:microsoft-dynamics-schemas/page/entregaalmacen", Order=0)]
        public RepositoryWebServiceTRH.EntregaAlmacenEpisContext.EntregaAlmacen EntregaAlmacen;
        
        public Create_Result() {
        }
        
        public Create_Result(RepositoryWebServiceTRH.EntregaAlmacenEpisContext.EntregaAlmacen EntregaAlmacen) {
            this.EntregaAlmacen = EntregaAlmacen;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.MessageContractAttribute(WrapperName="CreateMultiple", WrapperNamespace="urn:microsoft-dynamics-schemas/page/entregaalmacen", IsWrapped=true)]
    public partial class CreateMultiple {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="urn:microsoft-dynamics-schemas/page/entregaalmacen", Order=0)]
        [System.Xml.Serialization.XmlArrayItemAttribute(IsNullable=false)]
        public RepositoryWebServiceTRH.EntregaAlmacenEpisContext.EntregaAlmacen[] EntregaAlmacen_List;
        
        public CreateMultiple() {
        }
        
        public CreateMultiple(RepositoryWebServiceTRH.EntregaAlmacenEpisContext.EntregaAlmacen[] EntregaAlmacen_List) {
            this.EntregaAlmacen_List = EntregaAlmacen_List;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.MessageContractAttribute(WrapperName="CreateMultiple_Result", WrapperNamespace="urn:microsoft-dynamics-schemas/page/entregaalmacen", IsWrapped=true)]
    public partial class CreateMultiple_Result {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="urn:microsoft-dynamics-schemas/page/entregaalmacen", Order=0)]
        [System.Xml.Serialization.XmlArrayItemAttribute(IsNullable=false)]
        public RepositoryWebServiceTRH.EntregaAlmacenEpisContext.EntregaAlmacen[] EntregaAlmacen_List;
        
        public CreateMultiple_Result() {
        }
        
        public CreateMultiple_Result(RepositoryWebServiceTRH.EntregaAlmacenEpisContext.EntregaAlmacen[] EntregaAlmacen_List) {
            this.EntregaAlmacen_List = EntregaAlmacen_List;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.MessageContractAttribute(WrapperName="Update", WrapperNamespace="urn:microsoft-dynamics-schemas/page/entregaalmacen", IsWrapped=true)]
    public partial class Update {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="urn:microsoft-dynamics-schemas/page/entregaalmacen", Order=0)]
        public RepositoryWebServiceTRH.EntregaAlmacenEpisContext.EntregaAlmacen EntregaAlmacen;
        
        public Update() {
        }
        
        public Update(RepositoryWebServiceTRH.EntregaAlmacenEpisContext.EntregaAlmacen EntregaAlmacen) {
            this.EntregaAlmacen = EntregaAlmacen;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.MessageContractAttribute(WrapperName="Update_Result", WrapperNamespace="urn:microsoft-dynamics-schemas/page/entregaalmacen", IsWrapped=true)]
    public partial class Update_Result {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="urn:microsoft-dynamics-schemas/page/entregaalmacen", Order=0)]
        public RepositoryWebServiceTRH.EntregaAlmacenEpisContext.EntregaAlmacen EntregaAlmacen;
        
        public Update_Result() {
        }
        
        public Update_Result(RepositoryWebServiceTRH.EntregaAlmacenEpisContext.EntregaAlmacen EntregaAlmacen) {
            this.EntregaAlmacen = EntregaAlmacen;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.MessageContractAttribute(WrapperName="UpdateMultiple", WrapperNamespace="urn:microsoft-dynamics-schemas/page/entregaalmacen", IsWrapped=true)]
    public partial class UpdateMultiple {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="urn:microsoft-dynamics-schemas/page/entregaalmacen", Order=0)]
        [System.Xml.Serialization.XmlArrayItemAttribute(IsNullable=false)]
        public RepositoryWebServiceTRH.EntregaAlmacenEpisContext.EntregaAlmacen[] EntregaAlmacen_List;
        
        public UpdateMultiple() {
        }
        
        public UpdateMultiple(RepositoryWebServiceTRH.EntregaAlmacenEpisContext.EntregaAlmacen[] EntregaAlmacen_List) {
            this.EntregaAlmacen_List = EntregaAlmacen_List;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.MessageContractAttribute(WrapperName="UpdateMultiple_Result", WrapperNamespace="urn:microsoft-dynamics-schemas/page/entregaalmacen", IsWrapped=true)]
    public partial class UpdateMultiple_Result {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="urn:microsoft-dynamics-schemas/page/entregaalmacen", Order=0)]
        [System.Xml.Serialization.XmlArrayItemAttribute(IsNullable=false)]
        public RepositoryWebServiceTRH.EntregaAlmacenEpisContext.EntregaAlmacen[] EntregaAlmacen_List;
        
        public UpdateMultiple_Result() {
        }
        
        public UpdateMultiple_Result(RepositoryWebServiceTRH.EntregaAlmacenEpisContext.EntregaAlmacen[] EntregaAlmacen_List) {
            this.EntregaAlmacen_List = EntregaAlmacen_List;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="Delete", WrapperNamespace="urn:microsoft-dynamics-schemas/page/entregaalmacen", IsWrapped=true)]
    public partial class Delete {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="urn:microsoft-dynamics-schemas/page/entregaalmacen", Order=0)]
        public string Key;
        
        public Delete() {
        }
        
        public Delete(string Key) {
            this.Key = Key;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="Delete_Result", WrapperNamespace="urn:microsoft-dynamics-schemas/page/entregaalmacen", IsWrapped=true)]
    public partial class Delete_Result {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="Delete_Result", Namespace="urn:microsoft-dynamics-schemas/page/entregaalmacen", Order=0)]
        public bool Delete_Result1;
        
        public Delete_Result() {
        }
        
        public Delete_Result(bool Delete_Result1) {
            this.Delete_Result1 = Delete_Result1;
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface EntregaAlmacen_PortChannel : RepositoryWebServiceTRH.EntregaAlmacenEpisContext.EntregaAlmacen_Port, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class EntregaAlmacen_PortClient : System.ServiceModel.ClientBase<RepositoryWebServiceTRH.EntregaAlmacenEpisContext.EntregaAlmacen_Port>, RepositoryWebServiceTRH.EntregaAlmacenEpisContext.EntregaAlmacen_Port {
        
        public EntregaAlmacen_PortClient() {
        }
        
        public EntregaAlmacen_PortClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public EntregaAlmacen_PortClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public EntregaAlmacen_PortClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public EntregaAlmacen_PortClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        RepositoryWebServiceTRH.EntregaAlmacenEpisContext.Read_Result RepositoryWebServiceTRH.EntregaAlmacenEpisContext.EntregaAlmacen_Port.Read(RepositoryWebServiceTRH.EntregaAlmacenEpisContext.Read request) {
            return base.Channel.Read(request);
        }
        
        public RepositoryWebServiceTRH.EntregaAlmacenEpisContext.EntregaAlmacen Read(string Cod_Empleado, string Cod_Producto, System.DateTime Fecha, int No_Linea) {
            RepositoryWebServiceTRH.EntregaAlmacenEpisContext.Read inValue = new RepositoryWebServiceTRH.EntregaAlmacenEpisContext.Read();
            inValue.Cod_Empleado = Cod_Empleado;
            inValue.Cod_Producto = Cod_Producto;
            inValue.Fecha = Fecha;
            inValue.No_Linea = No_Linea;
            RepositoryWebServiceTRH.EntregaAlmacenEpisContext.Read_Result retVal = ((RepositoryWebServiceTRH.EntregaAlmacenEpisContext.EntregaAlmacen_Port)(this)).Read(inValue);
            return retVal.EntregaAlmacen;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<RepositoryWebServiceTRH.EntregaAlmacenEpisContext.Read_Result> RepositoryWebServiceTRH.EntregaAlmacenEpisContext.EntregaAlmacen_Port.ReadAsync(RepositoryWebServiceTRH.EntregaAlmacenEpisContext.Read request) {
            return base.Channel.ReadAsync(request);
        }
        
        public System.Threading.Tasks.Task<RepositoryWebServiceTRH.EntregaAlmacenEpisContext.Read_Result> ReadAsync(string Cod_Empleado, string Cod_Producto, System.DateTime Fecha, int No_Linea) {
            RepositoryWebServiceTRH.EntregaAlmacenEpisContext.Read inValue = new RepositoryWebServiceTRH.EntregaAlmacenEpisContext.Read();
            inValue.Cod_Empleado = Cod_Empleado;
            inValue.Cod_Producto = Cod_Producto;
            inValue.Fecha = Fecha;
            inValue.No_Linea = No_Linea;
            return ((RepositoryWebServiceTRH.EntregaAlmacenEpisContext.EntregaAlmacen_Port)(this)).ReadAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        RepositoryWebServiceTRH.EntregaAlmacenEpisContext.ReadByRecId_Result RepositoryWebServiceTRH.EntregaAlmacenEpisContext.EntregaAlmacen_Port.ReadByRecId(RepositoryWebServiceTRH.EntregaAlmacenEpisContext.ReadByRecId request) {
            return base.Channel.ReadByRecId(request);
        }
        
        public RepositoryWebServiceTRH.EntregaAlmacenEpisContext.EntregaAlmacen ReadByRecId(string recId) {
            RepositoryWebServiceTRH.EntregaAlmacenEpisContext.ReadByRecId inValue = new RepositoryWebServiceTRH.EntregaAlmacenEpisContext.ReadByRecId();
            inValue.recId = recId;
            RepositoryWebServiceTRH.EntregaAlmacenEpisContext.ReadByRecId_Result retVal = ((RepositoryWebServiceTRH.EntregaAlmacenEpisContext.EntregaAlmacen_Port)(this)).ReadByRecId(inValue);
            return retVal.EntregaAlmacen;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<RepositoryWebServiceTRH.EntregaAlmacenEpisContext.ReadByRecId_Result> RepositoryWebServiceTRH.EntregaAlmacenEpisContext.EntregaAlmacen_Port.ReadByRecIdAsync(RepositoryWebServiceTRH.EntregaAlmacenEpisContext.ReadByRecId request) {
            return base.Channel.ReadByRecIdAsync(request);
        }
        
        public System.Threading.Tasks.Task<RepositoryWebServiceTRH.EntregaAlmacenEpisContext.ReadByRecId_Result> ReadByRecIdAsync(string recId) {
            RepositoryWebServiceTRH.EntregaAlmacenEpisContext.ReadByRecId inValue = new RepositoryWebServiceTRH.EntregaAlmacenEpisContext.ReadByRecId();
            inValue.recId = recId;
            return ((RepositoryWebServiceTRH.EntregaAlmacenEpisContext.EntregaAlmacen_Port)(this)).ReadByRecIdAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        RepositoryWebServiceTRH.EntregaAlmacenEpisContext.ReadMultiple_Result RepositoryWebServiceTRH.EntregaAlmacenEpisContext.EntregaAlmacen_Port.ReadMultiple(RepositoryWebServiceTRH.EntregaAlmacenEpisContext.ReadMultiple request) {
            return base.Channel.ReadMultiple(request);
        }
        
        public RepositoryWebServiceTRH.EntregaAlmacenEpisContext.EntregaAlmacen[] ReadMultiple(RepositoryWebServiceTRH.EntregaAlmacenEpisContext.EntregaAlmacen_Filter[] filter, string bookmarkKey, int setSize) {
            RepositoryWebServiceTRH.EntregaAlmacenEpisContext.ReadMultiple inValue = new RepositoryWebServiceTRH.EntregaAlmacenEpisContext.ReadMultiple();
            inValue.filter = filter;
            inValue.bookmarkKey = bookmarkKey;
            inValue.setSize = setSize;
            RepositoryWebServiceTRH.EntregaAlmacenEpisContext.ReadMultiple_Result retVal = ((RepositoryWebServiceTRH.EntregaAlmacenEpisContext.EntregaAlmacen_Port)(this)).ReadMultiple(inValue);
            return retVal.ReadMultiple_Result1;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<RepositoryWebServiceTRH.EntregaAlmacenEpisContext.ReadMultiple_Result> RepositoryWebServiceTRH.EntregaAlmacenEpisContext.EntregaAlmacen_Port.ReadMultipleAsync(RepositoryWebServiceTRH.EntregaAlmacenEpisContext.ReadMultiple request) {
            return base.Channel.ReadMultipleAsync(request);
        }
        
        public System.Threading.Tasks.Task<RepositoryWebServiceTRH.EntregaAlmacenEpisContext.ReadMultiple_Result> ReadMultipleAsync(RepositoryWebServiceTRH.EntregaAlmacenEpisContext.EntregaAlmacen_Filter[] filter, string bookmarkKey, int setSize) {
            RepositoryWebServiceTRH.EntregaAlmacenEpisContext.ReadMultiple inValue = new RepositoryWebServiceTRH.EntregaAlmacenEpisContext.ReadMultiple();
            inValue.filter = filter;
            inValue.bookmarkKey = bookmarkKey;
            inValue.setSize = setSize;
            return ((RepositoryWebServiceTRH.EntregaAlmacenEpisContext.EntregaAlmacen_Port)(this)).ReadMultipleAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        RepositoryWebServiceTRH.EntregaAlmacenEpisContext.IsUpdated_Result RepositoryWebServiceTRH.EntregaAlmacenEpisContext.EntregaAlmacen_Port.IsUpdated(RepositoryWebServiceTRH.EntregaAlmacenEpisContext.IsUpdated request) {
            return base.Channel.IsUpdated(request);
        }
        
        public bool IsUpdated(string Key) {
            RepositoryWebServiceTRH.EntregaAlmacenEpisContext.IsUpdated inValue = new RepositoryWebServiceTRH.EntregaAlmacenEpisContext.IsUpdated();
            inValue.Key = Key;
            RepositoryWebServiceTRH.EntregaAlmacenEpisContext.IsUpdated_Result retVal = ((RepositoryWebServiceTRH.EntregaAlmacenEpisContext.EntregaAlmacen_Port)(this)).IsUpdated(inValue);
            return retVal.IsUpdated_Result1;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<RepositoryWebServiceTRH.EntregaAlmacenEpisContext.IsUpdated_Result> RepositoryWebServiceTRH.EntregaAlmacenEpisContext.EntregaAlmacen_Port.IsUpdatedAsync(RepositoryWebServiceTRH.EntregaAlmacenEpisContext.IsUpdated request) {
            return base.Channel.IsUpdatedAsync(request);
        }
        
        public System.Threading.Tasks.Task<RepositoryWebServiceTRH.EntregaAlmacenEpisContext.IsUpdated_Result> IsUpdatedAsync(string Key) {
            RepositoryWebServiceTRH.EntregaAlmacenEpisContext.IsUpdated inValue = new RepositoryWebServiceTRH.EntregaAlmacenEpisContext.IsUpdated();
            inValue.Key = Key;
            return ((RepositoryWebServiceTRH.EntregaAlmacenEpisContext.EntregaAlmacen_Port)(this)).IsUpdatedAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        RepositoryWebServiceTRH.EntregaAlmacenEpisContext.GetRecIdFromKey_Result RepositoryWebServiceTRH.EntregaAlmacenEpisContext.EntregaAlmacen_Port.GetRecIdFromKey(RepositoryWebServiceTRH.EntregaAlmacenEpisContext.GetRecIdFromKey request) {
            return base.Channel.GetRecIdFromKey(request);
        }
        
        public string GetRecIdFromKey(string Key) {
            RepositoryWebServiceTRH.EntregaAlmacenEpisContext.GetRecIdFromKey inValue = new RepositoryWebServiceTRH.EntregaAlmacenEpisContext.GetRecIdFromKey();
            inValue.Key = Key;
            RepositoryWebServiceTRH.EntregaAlmacenEpisContext.GetRecIdFromKey_Result retVal = ((RepositoryWebServiceTRH.EntregaAlmacenEpisContext.EntregaAlmacen_Port)(this)).GetRecIdFromKey(inValue);
            return retVal.GetRecIdFromKey_Result1;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<RepositoryWebServiceTRH.EntregaAlmacenEpisContext.GetRecIdFromKey_Result> RepositoryWebServiceTRH.EntregaAlmacenEpisContext.EntregaAlmacen_Port.GetRecIdFromKeyAsync(RepositoryWebServiceTRH.EntregaAlmacenEpisContext.GetRecIdFromKey request) {
            return base.Channel.GetRecIdFromKeyAsync(request);
        }
        
        public System.Threading.Tasks.Task<RepositoryWebServiceTRH.EntregaAlmacenEpisContext.GetRecIdFromKey_Result> GetRecIdFromKeyAsync(string Key) {
            RepositoryWebServiceTRH.EntregaAlmacenEpisContext.GetRecIdFromKey inValue = new RepositoryWebServiceTRH.EntregaAlmacenEpisContext.GetRecIdFromKey();
            inValue.Key = Key;
            return ((RepositoryWebServiceTRH.EntregaAlmacenEpisContext.EntregaAlmacen_Port)(this)).GetRecIdFromKeyAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        RepositoryWebServiceTRH.EntregaAlmacenEpisContext.Create_Result RepositoryWebServiceTRH.EntregaAlmacenEpisContext.EntregaAlmacen_Port.Create(RepositoryWebServiceTRH.EntregaAlmacenEpisContext.Create request) {
            return base.Channel.Create(request);
        }
        
        public void Create(ref RepositoryWebServiceTRH.EntregaAlmacenEpisContext.EntregaAlmacen EntregaAlmacen) {
            RepositoryWebServiceTRH.EntregaAlmacenEpisContext.Create inValue = new RepositoryWebServiceTRH.EntregaAlmacenEpisContext.Create();
            inValue.EntregaAlmacen = EntregaAlmacen;
            RepositoryWebServiceTRH.EntregaAlmacenEpisContext.Create_Result retVal = ((RepositoryWebServiceTRH.EntregaAlmacenEpisContext.EntregaAlmacen_Port)(this)).Create(inValue);
            EntregaAlmacen = retVal.EntregaAlmacen;
        }
        
        public System.Threading.Tasks.Task<RepositoryWebServiceTRH.EntregaAlmacenEpisContext.Create_Result> CreateAsync(RepositoryWebServiceTRH.EntregaAlmacenEpisContext.Create request) {
            return base.Channel.CreateAsync(request);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        RepositoryWebServiceTRH.EntregaAlmacenEpisContext.CreateMultiple_Result RepositoryWebServiceTRH.EntregaAlmacenEpisContext.EntregaAlmacen_Port.CreateMultiple(RepositoryWebServiceTRH.EntregaAlmacenEpisContext.CreateMultiple request) {
            return base.Channel.CreateMultiple(request);
        }
        
        public void CreateMultiple(ref RepositoryWebServiceTRH.EntregaAlmacenEpisContext.EntregaAlmacen[] EntregaAlmacen_List) {
            RepositoryWebServiceTRH.EntregaAlmacenEpisContext.CreateMultiple inValue = new RepositoryWebServiceTRH.EntregaAlmacenEpisContext.CreateMultiple();
            inValue.EntregaAlmacen_List = EntregaAlmacen_List;
            RepositoryWebServiceTRH.EntregaAlmacenEpisContext.CreateMultiple_Result retVal = ((RepositoryWebServiceTRH.EntregaAlmacenEpisContext.EntregaAlmacen_Port)(this)).CreateMultiple(inValue);
            EntregaAlmacen_List = retVal.EntregaAlmacen_List;
        }
        
        public System.Threading.Tasks.Task<RepositoryWebServiceTRH.EntregaAlmacenEpisContext.CreateMultiple_Result> CreateMultipleAsync(RepositoryWebServiceTRH.EntregaAlmacenEpisContext.CreateMultiple request) {
            return base.Channel.CreateMultipleAsync(request);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        RepositoryWebServiceTRH.EntregaAlmacenEpisContext.Update_Result RepositoryWebServiceTRH.EntregaAlmacenEpisContext.EntregaAlmacen_Port.Update(RepositoryWebServiceTRH.EntregaAlmacenEpisContext.Update request) {
            return base.Channel.Update(request);
        }
        
        public void Update(ref RepositoryWebServiceTRH.EntregaAlmacenEpisContext.EntregaAlmacen EntregaAlmacen) {
            RepositoryWebServiceTRH.EntregaAlmacenEpisContext.Update inValue = new RepositoryWebServiceTRH.EntregaAlmacenEpisContext.Update();
            inValue.EntregaAlmacen = EntregaAlmacen;
            RepositoryWebServiceTRH.EntregaAlmacenEpisContext.Update_Result retVal = ((RepositoryWebServiceTRH.EntregaAlmacenEpisContext.EntregaAlmacen_Port)(this)).Update(inValue);
            EntregaAlmacen = retVal.EntregaAlmacen;
        }
        
        public System.Threading.Tasks.Task<RepositoryWebServiceTRH.EntregaAlmacenEpisContext.Update_Result> UpdateAsync(RepositoryWebServiceTRH.EntregaAlmacenEpisContext.Update request) {
            return base.Channel.UpdateAsync(request);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        RepositoryWebServiceTRH.EntregaAlmacenEpisContext.UpdateMultiple_Result RepositoryWebServiceTRH.EntregaAlmacenEpisContext.EntregaAlmacen_Port.UpdateMultiple(RepositoryWebServiceTRH.EntregaAlmacenEpisContext.UpdateMultiple request) {
            return base.Channel.UpdateMultiple(request);
        }
        
        public void UpdateMultiple(ref RepositoryWebServiceTRH.EntregaAlmacenEpisContext.EntregaAlmacen[] EntregaAlmacen_List) {
            RepositoryWebServiceTRH.EntregaAlmacenEpisContext.UpdateMultiple inValue = new RepositoryWebServiceTRH.EntregaAlmacenEpisContext.UpdateMultiple();
            inValue.EntregaAlmacen_List = EntregaAlmacen_List;
            RepositoryWebServiceTRH.EntregaAlmacenEpisContext.UpdateMultiple_Result retVal = ((RepositoryWebServiceTRH.EntregaAlmacenEpisContext.EntregaAlmacen_Port)(this)).UpdateMultiple(inValue);
            EntregaAlmacen_List = retVal.EntregaAlmacen_List;
        }
        
        public System.Threading.Tasks.Task<RepositoryWebServiceTRH.EntregaAlmacenEpisContext.UpdateMultiple_Result> UpdateMultipleAsync(RepositoryWebServiceTRH.EntregaAlmacenEpisContext.UpdateMultiple request) {
            return base.Channel.UpdateMultipleAsync(request);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        RepositoryWebServiceTRH.EntregaAlmacenEpisContext.Delete_Result RepositoryWebServiceTRH.EntregaAlmacenEpisContext.EntregaAlmacen_Port.Delete(RepositoryWebServiceTRH.EntregaAlmacenEpisContext.Delete request) {
            return base.Channel.Delete(request);
        }
        
        public bool Delete(string Key) {
            RepositoryWebServiceTRH.EntregaAlmacenEpisContext.Delete inValue = new RepositoryWebServiceTRH.EntregaAlmacenEpisContext.Delete();
            inValue.Key = Key;
            RepositoryWebServiceTRH.EntregaAlmacenEpisContext.Delete_Result retVal = ((RepositoryWebServiceTRH.EntregaAlmacenEpisContext.EntregaAlmacen_Port)(this)).Delete(inValue);
            return retVal.Delete_Result1;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<RepositoryWebServiceTRH.EntregaAlmacenEpisContext.Delete_Result> RepositoryWebServiceTRH.EntregaAlmacenEpisContext.EntregaAlmacen_Port.DeleteAsync(RepositoryWebServiceTRH.EntregaAlmacenEpisContext.Delete request) {
            return base.Channel.DeleteAsync(request);
        }
        
        public System.Threading.Tasks.Task<RepositoryWebServiceTRH.EntregaAlmacenEpisContext.Delete_Result> DeleteAsync(string Key) {
            RepositoryWebServiceTRH.EntregaAlmacenEpisContext.Delete inValue = new RepositoryWebServiceTRH.EntregaAlmacenEpisContext.Delete();
            inValue.Key = Key;
            return ((RepositoryWebServiceTRH.EntregaAlmacenEpisContext.EntregaAlmacen_Port)(this)).DeleteAsync(inValue);
        }
    }
}
