//------------------------------------------------------------------------------
// <auto-generated>
//     Este código fue generado por una herramienta.
//     Versión de runtime:4.0.30319.42000
//
//     Los cambios en este archivo podrían causar un comportamiento incorrecto y se perderán si
//     se vuelve a generar el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace wsTRH.pPostCode {
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(Namespace="urn:microsoft-dynamics-schemas/page/codigopostales", ConfigurationName="pPostCode.CodigoPostales_Port")]
    public interface CodigoPostales_Port {
        
        // CODEGEN: Se está generando un contrato de mensaje, ya que el nombre de contenedor (Read_Result) del mensaje Read_Result no coincide con el valor predeterminado (Read)
        [System.ServiceModel.OperationContractAttribute(Action="urn:microsoft-dynamics-schemas/page/codigopostales:Read", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        wsTRH.pPostCode.Read_Result Read(wsTRH.pPostCode.Read request);
        
        [System.ServiceModel.OperationContractAttribute(Action="urn:microsoft-dynamics-schemas/page/codigopostales:Read", ReplyAction="*")]
        System.Threading.Tasks.Task<wsTRH.pPostCode.Read_Result> ReadAsync(wsTRH.pPostCode.Read request);
        
        // CODEGEN: Se está generando un contrato de mensaje, ya que el nombre de contenedor (ReadByRecId_Result) del mensaje ReadByRecId_Result no coincide con el valor predeterminado (ReadByRecId)
        [System.ServiceModel.OperationContractAttribute(Action="urn:microsoft-dynamics-schemas/page/codigopostales:ReadByRecId", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        wsTRH.pPostCode.ReadByRecId_Result ReadByRecId(wsTRH.pPostCode.ReadByRecId request);
        
        [System.ServiceModel.OperationContractAttribute(Action="urn:microsoft-dynamics-schemas/page/codigopostales:ReadByRecId", ReplyAction="*")]
        System.Threading.Tasks.Task<wsTRH.pPostCode.ReadByRecId_Result> ReadByRecIdAsync(wsTRH.pPostCode.ReadByRecId request);
        
        // CODEGEN: Se está generando un contrato de mensaje, ya que el nombre de contenedor (ReadMultiple_Result) del mensaje ReadMultiple_Result no coincide con el valor predeterminado (ReadMultiple)
        [System.ServiceModel.OperationContractAttribute(Action="urn:microsoft-dynamics-schemas/page/codigopostales:ReadMultiple", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        wsTRH.pPostCode.ReadMultiple_Result ReadMultiple(wsTRH.pPostCode.ReadMultiple request);
        
        [System.ServiceModel.OperationContractAttribute(Action="urn:microsoft-dynamics-schemas/page/codigopostales:ReadMultiple", ReplyAction="*")]
        System.Threading.Tasks.Task<wsTRH.pPostCode.ReadMultiple_Result> ReadMultipleAsync(wsTRH.pPostCode.ReadMultiple request);
        
        // CODEGEN: Se está generando un contrato de mensaje, ya que el nombre de contenedor (IsUpdated_Result) del mensaje IsUpdated_Result no coincide con el valor predeterminado (IsUpdated)
        [System.ServiceModel.OperationContractAttribute(Action="urn:microsoft-dynamics-schemas/page/codigopostales:IsUpdated", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        wsTRH.pPostCode.IsUpdated_Result IsUpdated(wsTRH.pPostCode.IsUpdated request);
        
        [System.ServiceModel.OperationContractAttribute(Action="urn:microsoft-dynamics-schemas/page/codigopostales:IsUpdated", ReplyAction="*")]
        System.Threading.Tasks.Task<wsTRH.pPostCode.IsUpdated_Result> IsUpdatedAsync(wsTRH.pPostCode.IsUpdated request);
        
        // CODEGEN: Se está generando un contrato de mensaje, ya que el nombre de contenedor (GetRecIdFromKey_Result) del mensaje GetRecIdFromKey_Result no coincide con el valor predeterminado (GetRecIdFromKey)
        [System.ServiceModel.OperationContractAttribute(Action="urn:microsoft-dynamics-schemas/page/codigopostales:GetRecIdFromKey", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        wsTRH.pPostCode.GetRecIdFromKey_Result GetRecIdFromKey(wsTRH.pPostCode.GetRecIdFromKey request);
        
        [System.ServiceModel.OperationContractAttribute(Action="urn:microsoft-dynamics-schemas/page/codigopostales:GetRecIdFromKey", ReplyAction="*")]
        System.Threading.Tasks.Task<wsTRH.pPostCode.GetRecIdFromKey_Result> GetRecIdFromKeyAsync(wsTRH.pPostCode.GetRecIdFromKey request);
        
        [System.ServiceModel.OperationContractAttribute(Action="urn:microsoft-dynamics-schemas/page/codigopostales:Create", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        wsTRH.pPostCode.Create_Result Create(wsTRH.pPostCode.Create request);
        
        // CODEGEN: Generando contrato de mensaje, ya que la operación tiene múltiples valores de devolución.
        [System.ServiceModel.OperationContractAttribute(Action="urn:microsoft-dynamics-schemas/page/codigopostales:Create", ReplyAction="*")]
        System.Threading.Tasks.Task<wsTRH.pPostCode.Create_Result> CreateAsync(wsTRH.pPostCode.Create request);
        
        [System.ServiceModel.OperationContractAttribute(Action="urn:microsoft-dynamics-schemas/page/codigopostales:CreateMultiple", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        wsTRH.pPostCode.CreateMultiple_Result CreateMultiple(wsTRH.pPostCode.CreateMultiple request);
        
        // CODEGEN: Generando contrato de mensaje, ya que la operación tiene múltiples valores de devolución.
        [System.ServiceModel.OperationContractAttribute(Action="urn:microsoft-dynamics-schemas/page/codigopostales:CreateMultiple", ReplyAction="*")]
        System.Threading.Tasks.Task<wsTRH.pPostCode.CreateMultiple_Result> CreateMultipleAsync(wsTRH.pPostCode.CreateMultiple request);
        
        [System.ServiceModel.OperationContractAttribute(Action="urn:microsoft-dynamics-schemas/page/codigopostales:Update", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        wsTRH.pPostCode.Update_Result Update(wsTRH.pPostCode.Update request);
        
        // CODEGEN: Generando contrato de mensaje, ya que la operación tiene múltiples valores de devolución.
        [System.ServiceModel.OperationContractAttribute(Action="urn:microsoft-dynamics-schemas/page/codigopostales:Update", ReplyAction="*")]
        System.Threading.Tasks.Task<wsTRH.pPostCode.Update_Result> UpdateAsync(wsTRH.pPostCode.Update request);
        
        [System.ServiceModel.OperationContractAttribute(Action="urn:microsoft-dynamics-schemas/page/codigopostales:UpdateMultiple", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        wsTRH.pPostCode.UpdateMultiple_Result UpdateMultiple(wsTRH.pPostCode.UpdateMultiple request);
        
        // CODEGEN: Generando contrato de mensaje, ya que la operación tiene múltiples valores de devolución.
        [System.ServiceModel.OperationContractAttribute(Action="urn:microsoft-dynamics-schemas/page/codigopostales:UpdateMultiple", ReplyAction="*")]
        System.Threading.Tasks.Task<wsTRH.pPostCode.UpdateMultiple_Result> UpdateMultipleAsync(wsTRH.pPostCode.UpdateMultiple request);
        
        // CODEGEN: Se está generando un contrato de mensaje, ya que el nombre de contenedor (Delete_Result) del mensaje Delete_Result no coincide con el valor predeterminado (Delete)
        [System.ServiceModel.OperationContractAttribute(Action="urn:microsoft-dynamics-schemas/page/codigopostales:Delete", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        wsTRH.pPostCode.Delete_Result Delete(wsTRH.pPostCode.Delete request);
        
        [System.ServiceModel.OperationContractAttribute(Action="urn:microsoft-dynamics-schemas/page/codigopostales:Delete", ReplyAction="*")]
        System.Threading.Tasks.Task<wsTRH.pPostCode.Delete_Result> DeleteAsync(wsTRH.pPostCode.Delete request);
    }
    
    /// <comentarios/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.6.1064.2")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="urn:microsoft-dynamics-schemas/page/codigopostales")]
    public partial class CodigoPostales : object, System.ComponentModel.INotifyPropertyChanged {
        
        private string keyField;
        
        private string codeField;
        
        private string cityField;
        
        private string country_Region_CodeField;
        
        private string countyField;
        
        private decimal euros_TmField;
        
        private bool euros_TmFieldSpecified;
        
        private decimal latitudField;
        
        private bool latitudFieldSpecified;
        
        private decimal longitudField;
        
        private bool longitudFieldSpecified;
        
        private decimal euros_Tm_ProveedorField;
        
        private bool euros_Tm_ProveedorFieldSpecified;
        
        private decimal distancia_FabricaField;
        
        private bool distancia_FabricaFieldSpecified;
        
        /// <comentarios/>
        [System.Xml.Serialization.XmlElementAttribute(Order=0)]
        public string Key {
            get {
                return this.keyField;
            }
            set {
                this.keyField = value;
                this.RaisePropertyChanged("Key");
            }
        }
        
        /// <comentarios/>
        [System.Xml.Serialization.XmlElementAttribute(Order=1)]
        public string Code {
            get {
                return this.codeField;
            }
            set {
                this.codeField = value;
                this.RaisePropertyChanged("Code");
            }
        }
        
        /// <comentarios/>
        [System.Xml.Serialization.XmlElementAttribute(Order=2)]
        public string City {
            get {
                return this.cityField;
            }
            set {
                this.cityField = value;
                this.RaisePropertyChanged("City");
            }
        }
        
        /// <comentarios/>
        [System.Xml.Serialization.XmlElementAttribute(Order=3)]
        public string Country_Region_Code {
            get {
                return this.country_Region_CodeField;
            }
            set {
                this.country_Region_CodeField = value;
                this.RaisePropertyChanged("Country_Region_Code");
            }
        }
        
        /// <comentarios/>
        [System.Xml.Serialization.XmlElementAttribute(Order=4)]
        public string County {
            get {
                return this.countyField;
            }
            set {
                this.countyField = value;
                this.RaisePropertyChanged("County");
            }
        }
        
        /// <comentarios/>
        [System.Xml.Serialization.XmlElementAttribute(Order=5)]
        public decimal Euros_Tm {
            get {
                return this.euros_TmField;
            }
            set {
                this.euros_TmField = value;
                this.RaisePropertyChanged("Euros_Tm");
            }
        }
        
        /// <comentarios/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool Euros_TmSpecified {
            get {
                return this.euros_TmFieldSpecified;
            }
            set {
                this.euros_TmFieldSpecified = value;
                this.RaisePropertyChanged("Euros_TmSpecified");
            }
        }
        
        /// <comentarios/>
        [System.Xml.Serialization.XmlElementAttribute(Order=6)]
        public decimal latitud {
            get {
                return this.latitudField;
            }
            set {
                this.latitudField = value;
                this.RaisePropertyChanged("latitud");
            }
        }
        
        /// <comentarios/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool latitudSpecified {
            get {
                return this.latitudFieldSpecified;
            }
            set {
                this.latitudFieldSpecified = value;
                this.RaisePropertyChanged("latitudSpecified");
            }
        }
        
        /// <comentarios/>
        [System.Xml.Serialization.XmlElementAttribute(Order=7)]
        public decimal longitud {
            get {
                return this.longitudField;
            }
            set {
                this.longitudField = value;
                this.RaisePropertyChanged("longitud");
            }
        }
        
        /// <comentarios/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool longitudSpecified {
            get {
                return this.longitudFieldSpecified;
            }
            set {
                this.longitudFieldSpecified = value;
                this.RaisePropertyChanged("longitudSpecified");
            }
        }
        
        /// <comentarios/>
        [System.Xml.Serialization.XmlElementAttribute(Order=8)]
        public decimal Euros_Tm_Proveedor {
            get {
                return this.euros_Tm_ProveedorField;
            }
            set {
                this.euros_Tm_ProveedorField = value;
                this.RaisePropertyChanged("Euros_Tm_Proveedor");
            }
        }
        
        /// <comentarios/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool Euros_Tm_ProveedorSpecified {
            get {
                return this.euros_Tm_ProveedorFieldSpecified;
            }
            set {
                this.euros_Tm_ProveedorFieldSpecified = value;
                this.RaisePropertyChanged("Euros_Tm_ProveedorSpecified");
            }
        }
        
        /// <comentarios/>
        [System.Xml.Serialization.XmlElementAttribute(Order=9)]
        public decimal Distancia_Fabrica {
            get {
                return this.distancia_FabricaField;
            }
            set {
                this.distancia_FabricaField = value;
                this.RaisePropertyChanged("Distancia_Fabrica");
            }
        }
        
        /// <comentarios/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool Distancia_FabricaSpecified {
            get {
                return this.distancia_FabricaFieldSpecified;
            }
            set {
                this.distancia_FabricaFieldSpecified = value;
                this.RaisePropertyChanged("Distancia_FabricaSpecified");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    /// <comentarios/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.6.1064.2")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="urn:microsoft-dynamics-schemas/page/codigopostales")]
    public partial class CodigoPostales_Filter : object, System.ComponentModel.INotifyPropertyChanged {
        
        private CodigoPostales_Fields fieldField;
        
        private string criteriaField;
        
        /// <comentarios/>
        [System.Xml.Serialization.XmlElementAttribute(Order=0)]
        public CodigoPostales_Fields Field {
            get {
                return this.fieldField;
            }
            set {
                this.fieldField = value;
                this.RaisePropertyChanged("Field");
            }
        }
        
        /// <comentarios/>
        [System.Xml.Serialization.XmlElementAttribute(Order=1)]
        public string Criteria {
            get {
                return this.criteriaField;
            }
            set {
                this.criteriaField = value;
                this.RaisePropertyChanged("Criteria");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    /// <comentarios/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.6.1064.2")]
    [System.SerializableAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="urn:microsoft-dynamics-schemas/page/codigopostales")]
    public enum CodigoPostales_Fields {
        
        /// <comentarios/>
        Code,
        
        /// <comentarios/>
        City,
        
        /// <comentarios/>
        Country_Region_Code,
        
        /// <comentarios/>
        County,
        
        /// <comentarios/>
        Euros_Tm,
        
        /// <comentarios/>
        latitud,
        
        /// <comentarios/>
        longitud,
        
        /// <comentarios/>
        Euros_Tm_Proveedor,
        
        /// <comentarios/>
        Distancia_Fabrica,
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="Read", WrapperNamespace="urn:microsoft-dynamics-schemas/page/codigopostales", IsWrapped=true)]
    public partial class Read {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="urn:microsoft-dynamics-schemas/page/codigopostales", Order=0)]
        public string Code;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="urn:microsoft-dynamics-schemas/page/codigopostales", Order=1)]
        public string City;
        
        public Read() {
        }
        
        public Read(string Code, string City) {
            this.Code = Code;
            this.City = City;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="Read_Result", WrapperNamespace="urn:microsoft-dynamics-schemas/page/codigopostales", IsWrapped=true)]
    public partial class Read_Result {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="urn:microsoft-dynamics-schemas/page/codigopostales", Order=0)]
        public wsTRH.pPostCode.CodigoPostales CodigoPostales;
        
        public Read_Result() {
        }
        
        public Read_Result(wsTRH.pPostCode.CodigoPostales CodigoPostales) {
            this.CodigoPostales = CodigoPostales;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="ReadByRecId", WrapperNamespace="urn:microsoft-dynamics-schemas/page/codigopostales", IsWrapped=true)]
    public partial class ReadByRecId {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="urn:microsoft-dynamics-schemas/page/codigopostales", Order=0)]
        public string recId;
        
        public ReadByRecId() {
        }
        
        public ReadByRecId(string recId) {
            this.recId = recId;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="ReadByRecId_Result", WrapperNamespace="urn:microsoft-dynamics-schemas/page/codigopostales", IsWrapped=true)]
    public partial class ReadByRecId_Result {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="urn:microsoft-dynamics-schemas/page/codigopostales", Order=0)]
        public wsTRH.pPostCode.CodigoPostales CodigoPostales;
        
        public ReadByRecId_Result() {
        }
        
        public ReadByRecId_Result(wsTRH.pPostCode.CodigoPostales CodigoPostales) {
            this.CodigoPostales = CodigoPostales;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="ReadMultiple", WrapperNamespace="urn:microsoft-dynamics-schemas/page/codigopostales", IsWrapped=true)]
    public partial class ReadMultiple {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="urn:microsoft-dynamics-schemas/page/codigopostales", Order=0)]
        [System.Xml.Serialization.XmlElementAttribute("filter")]
        public wsTRH.pPostCode.CodigoPostales_Filter[] filter;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="urn:microsoft-dynamics-schemas/page/codigopostales", Order=1)]
        public string bookmarkKey;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="urn:microsoft-dynamics-schemas/page/codigopostales", Order=2)]
        public int setSize;
        
        public ReadMultiple() {
        }
        
        public ReadMultiple(wsTRH.pPostCode.CodigoPostales_Filter[] filter, string bookmarkKey, int setSize) {
            this.filter = filter;
            this.bookmarkKey = bookmarkKey;
            this.setSize = setSize;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="ReadMultiple_Result", WrapperNamespace="urn:microsoft-dynamics-schemas/page/codigopostales", IsWrapped=true)]
    public partial class ReadMultiple_Result {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="ReadMultiple_Result", Namespace="urn:microsoft-dynamics-schemas/page/codigopostales", Order=0)]
        [System.Xml.Serialization.XmlArrayItemAttribute(IsNullable=false)]
        public wsTRH.pPostCode.CodigoPostales[] ReadMultiple_Result1;
        
        public ReadMultiple_Result() {
        }
        
        public ReadMultiple_Result(wsTRH.pPostCode.CodigoPostales[] ReadMultiple_Result1) {
            this.ReadMultiple_Result1 = ReadMultiple_Result1;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="IsUpdated", WrapperNamespace="urn:microsoft-dynamics-schemas/page/codigopostales", IsWrapped=true)]
    public partial class IsUpdated {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="urn:microsoft-dynamics-schemas/page/codigopostales", Order=0)]
        public string Key;
        
        public IsUpdated() {
        }
        
        public IsUpdated(string Key) {
            this.Key = Key;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="IsUpdated_Result", WrapperNamespace="urn:microsoft-dynamics-schemas/page/codigopostales", IsWrapped=true)]
    public partial class IsUpdated_Result {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="IsUpdated_Result", Namespace="urn:microsoft-dynamics-schemas/page/codigopostales", Order=0)]
        public bool IsUpdated_Result1;
        
        public IsUpdated_Result() {
        }
        
        public IsUpdated_Result(bool IsUpdated_Result1) {
            this.IsUpdated_Result1 = IsUpdated_Result1;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="GetRecIdFromKey", WrapperNamespace="urn:microsoft-dynamics-schemas/page/codigopostales", IsWrapped=true)]
    public partial class GetRecIdFromKey {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="urn:microsoft-dynamics-schemas/page/codigopostales", Order=0)]
        public string Key;
        
        public GetRecIdFromKey() {
        }
        
        public GetRecIdFromKey(string Key) {
            this.Key = Key;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="GetRecIdFromKey_Result", WrapperNamespace="urn:microsoft-dynamics-schemas/page/codigopostales", IsWrapped=true)]
    public partial class GetRecIdFromKey_Result {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="GetRecIdFromKey_Result", Namespace="urn:microsoft-dynamics-schemas/page/codigopostales", Order=0)]
        public string GetRecIdFromKey_Result1;
        
        public GetRecIdFromKey_Result() {
        }
        
        public GetRecIdFromKey_Result(string GetRecIdFromKey_Result1) {
            this.GetRecIdFromKey_Result1 = GetRecIdFromKey_Result1;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.MessageContractAttribute(WrapperName="Create", WrapperNamespace="urn:microsoft-dynamics-schemas/page/codigopostales", IsWrapped=true)]
    public partial class Create {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="urn:microsoft-dynamics-schemas/page/codigopostales", Order=0)]
        public wsTRH.pPostCode.CodigoPostales CodigoPostales;
        
        public Create() {
        }
        
        public Create(wsTRH.pPostCode.CodigoPostales CodigoPostales) {
            this.CodigoPostales = CodigoPostales;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.MessageContractAttribute(WrapperName="Create_Result", WrapperNamespace="urn:microsoft-dynamics-schemas/page/codigopostales", IsWrapped=true)]
    public partial class Create_Result {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="urn:microsoft-dynamics-schemas/page/codigopostales", Order=0)]
        public wsTRH.pPostCode.CodigoPostales CodigoPostales;
        
        public Create_Result() {
        }
        
        public Create_Result(wsTRH.pPostCode.CodigoPostales CodigoPostales) {
            this.CodigoPostales = CodigoPostales;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.MessageContractAttribute(WrapperName="CreateMultiple", WrapperNamespace="urn:microsoft-dynamics-schemas/page/codigopostales", IsWrapped=true)]
    public partial class CreateMultiple {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="urn:microsoft-dynamics-schemas/page/codigopostales", Order=0)]
        [System.Xml.Serialization.XmlArrayItemAttribute(IsNullable=false)]
        public wsTRH.pPostCode.CodigoPostales[] CodigoPostales_List;
        
        public CreateMultiple() {
        }
        
        public CreateMultiple(wsTRH.pPostCode.CodigoPostales[] CodigoPostales_List) {
            this.CodigoPostales_List = CodigoPostales_List;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.MessageContractAttribute(WrapperName="CreateMultiple_Result", WrapperNamespace="urn:microsoft-dynamics-schemas/page/codigopostales", IsWrapped=true)]
    public partial class CreateMultiple_Result {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="urn:microsoft-dynamics-schemas/page/codigopostales", Order=0)]
        [System.Xml.Serialization.XmlArrayItemAttribute(IsNullable=false)]
        public wsTRH.pPostCode.CodigoPostales[] CodigoPostales_List;
        
        public CreateMultiple_Result() {
        }
        
        public CreateMultiple_Result(wsTRH.pPostCode.CodigoPostales[] CodigoPostales_List) {
            this.CodigoPostales_List = CodigoPostales_List;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.MessageContractAttribute(WrapperName="Update", WrapperNamespace="urn:microsoft-dynamics-schemas/page/codigopostales", IsWrapped=true)]
    public partial class Update {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="urn:microsoft-dynamics-schemas/page/codigopostales", Order=0)]
        public wsTRH.pPostCode.CodigoPostales CodigoPostales;
        
        public Update() {
        }
        
        public Update(wsTRH.pPostCode.CodigoPostales CodigoPostales) {
            this.CodigoPostales = CodigoPostales;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.MessageContractAttribute(WrapperName="Update_Result", WrapperNamespace="urn:microsoft-dynamics-schemas/page/codigopostales", IsWrapped=true)]
    public partial class Update_Result {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="urn:microsoft-dynamics-schemas/page/codigopostales", Order=0)]
        public wsTRH.pPostCode.CodigoPostales CodigoPostales;
        
        public Update_Result() {
        }
        
        public Update_Result(wsTRH.pPostCode.CodigoPostales CodigoPostales) {
            this.CodigoPostales = CodigoPostales;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.MessageContractAttribute(WrapperName="UpdateMultiple", WrapperNamespace="urn:microsoft-dynamics-schemas/page/codigopostales", IsWrapped=true)]
    public partial class UpdateMultiple {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="urn:microsoft-dynamics-schemas/page/codigopostales", Order=0)]
        [System.Xml.Serialization.XmlArrayItemAttribute(IsNullable=false)]
        public wsTRH.pPostCode.CodigoPostales[] CodigoPostales_List;
        
        public UpdateMultiple() {
        }
        
        public UpdateMultiple(wsTRH.pPostCode.CodigoPostales[] CodigoPostales_List) {
            this.CodigoPostales_List = CodigoPostales_List;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.MessageContractAttribute(WrapperName="UpdateMultiple_Result", WrapperNamespace="urn:microsoft-dynamics-schemas/page/codigopostales", IsWrapped=true)]
    public partial class UpdateMultiple_Result {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="urn:microsoft-dynamics-schemas/page/codigopostales", Order=0)]
        [System.Xml.Serialization.XmlArrayItemAttribute(IsNullable=false)]
        public wsTRH.pPostCode.CodigoPostales[] CodigoPostales_List;
        
        public UpdateMultiple_Result() {
        }
        
        public UpdateMultiple_Result(wsTRH.pPostCode.CodigoPostales[] CodigoPostales_List) {
            this.CodigoPostales_List = CodigoPostales_List;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="Delete", WrapperNamespace="urn:microsoft-dynamics-schemas/page/codigopostales", IsWrapped=true)]
    public partial class Delete {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="urn:microsoft-dynamics-schemas/page/codigopostales", Order=0)]
        public string Key;
        
        public Delete() {
        }
        
        public Delete(string Key) {
            this.Key = Key;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="Delete_Result", WrapperNamespace="urn:microsoft-dynamics-schemas/page/codigopostales", IsWrapped=true)]
    public partial class Delete_Result {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="Delete_Result", Namespace="urn:microsoft-dynamics-schemas/page/codigopostales", Order=0)]
        public bool Delete_Result1;
        
        public Delete_Result() {
        }
        
        public Delete_Result(bool Delete_Result1) {
            this.Delete_Result1 = Delete_Result1;
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface CodigoPostales_PortChannel : wsTRH.pPostCode.CodigoPostales_Port, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class CodigoPostales_PortClient : System.ServiceModel.ClientBase<wsTRH.pPostCode.CodigoPostales_Port>, wsTRH.pPostCode.CodigoPostales_Port {
        
        public CodigoPostales_PortClient() {
        }
        
        public CodigoPostales_PortClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public CodigoPostales_PortClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public CodigoPostales_PortClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public CodigoPostales_PortClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        wsTRH.pPostCode.Read_Result wsTRH.pPostCode.CodigoPostales_Port.Read(wsTRH.pPostCode.Read request) {
            return base.Channel.Read(request);
        }
        
        public wsTRH.pPostCode.CodigoPostales Read(string Code, string City) {
            wsTRH.pPostCode.Read inValue = new wsTRH.pPostCode.Read();
            inValue.Code = Code;
            inValue.City = City;
            wsTRH.pPostCode.Read_Result retVal = ((wsTRH.pPostCode.CodigoPostales_Port)(this)).Read(inValue);
            return retVal.CodigoPostales;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<wsTRH.pPostCode.Read_Result> wsTRH.pPostCode.CodigoPostales_Port.ReadAsync(wsTRH.pPostCode.Read request) {
            return base.Channel.ReadAsync(request);
        }
        
        public System.Threading.Tasks.Task<wsTRH.pPostCode.Read_Result> ReadAsync(string Code, string City) {
            wsTRH.pPostCode.Read inValue = new wsTRH.pPostCode.Read();
            inValue.Code = Code;
            inValue.City = City;
            return ((wsTRH.pPostCode.CodigoPostales_Port)(this)).ReadAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        wsTRH.pPostCode.ReadByRecId_Result wsTRH.pPostCode.CodigoPostales_Port.ReadByRecId(wsTRH.pPostCode.ReadByRecId request) {
            return base.Channel.ReadByRecId(request);
        }
        
        public wsTRH.pPostCode.CodigoPostales ReadByRecId(string recId) {
            wsTRH.pPostCode.ReadByRecId inValue = new wsTRH.pPostCode.ReadByRecId();
            inValue.recId = recId;
            wsTRH.pPostCode.ReadByRecId_Result retVal = ((wsTRH.pPostCode.CodigoPostales_Port)(this)).ReadByRecId(inValue);
            return retVal.CodigoPostales;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<wsTRH.pPostCode.ReadByRecId_Result> wsTRH.pPostCode.CodigoPostales_Port.ReadByRecIdAsync(wsTRH.pPostCode.ReadByRecId request) {
            return base.Channel.ReadByRecIdAsync(request);
        }
        
        public System.Threading.Tasks.Task<wsTRH.pPostCode.ReadByRecId_Result> ReadByRecIdAsync(string recId) {
            wsTRH.pPostCode.ReadByRecId inValue = new wsTRH.pPostCode.ReadByRecId();
            inValue.recId = recId;
            return ((wsTRH.pPostCode.CodigoPostales_Port)(this)).ReadByRecIdAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        wsTRH.pPostCode.ReadMultiple_Result wsTRH.pPostCode.CodigoPostales_Port.ReadMultiple(wsTRH.pPostCode.ReadMultiple request) {
            return base.Channel.ReadMultiple(request);
        }
        
        public wsTRH.pPostCode.CodigoPostales[] ReadMultiple(wsTRH.pPostCode.CodigoPostales_Filter[] filter, string bookmarkKey, int setSize) {
            wsTRH.pPostCode.ReadMultiple inValue = new wsTRH.pPostCode.ReadMultiple();
            inValue.filter = filter;
            inValue.bookmarkKey = bookmarkKey;
            inValue.setSize = setSize;
            wsTRH.pPostCode.ReadMultiple_Result retVal = ((wsTRH.pPostCode.CodigoPostales_Port)(this)).ReadMultiple(inValue);
            return retVal.ReadMultiple_Result1;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<wsTRH.pPostCode.ReadMultiple_Result> wsTRH.pPostCode.CodigoPostales_Port.ReadMultipleAsync(wsTRH.pPostCode.ReadMultiple request) {
            return base.Channel.ReadMultipleAsync(request);
        }
        
        public System.Threading.Tasks.Task<wsTRH.pPostCode.ReadMultiple_Result> ReadMultipleAsync(wsTRH.pPostCode.CodigoPostales_Filter[] filter, string bookmarkKey, int setSize) {
            wsTRH.pPostCode.ReadMultiple inValue = new wsTRH.pPostCode.ReadMultiple();
            inValue.filter = filter;
            inValue.bookmarkKey = bookmarkKey;
            inValue.setSize = setSize;
            return ((wsTRH.pPostCode.CodigoPostales_Port)(this)).ReadMultipleAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        wsTRH.pPostCode.IsUpdated_Result wsTRH.pPostCode.CodigoPostales_Port.IsUpdated(wsTRH.pPostCode.IsUpdated request) {
            return base.Channel.IsUpdated(request);
        }
        
        public bool IsUpdated(string Key) {
            wsTRH.pPostCode.IsUpdated inValue = new wsTRH.pPostCode.IsUpdated();
            inValue.Key = Key;
            wsTRH.pPostCode.IsUpdated_Result retVal = ((wsTRH.pPostCode.CodigoPostales_Port)(this)).IsUpdated(inValue);
            return retVal.IsUpdated_Result1;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<wsTRH.pPostCode.IsUpdated_Result> wsTRH.pPostCode.CodigoPostales_Port.IsUpdatedAsync(wsTRH.pPostCode.IsUpdated request) {
            return base.Channel.IsUpdatedAsync(request);
        }
        
        public System.Threading.Tasks.Task<wsTRH.pPostCode.IsUpdated_Result> IsUpdatedAsync(string Key) {
            wsTRH.pPostCode.IsUpdated inValue = new wsTRH.pPostCode.IsUpdated();
            inValue.Key = Key;
            return ((wsTRH.pPostCode.CodigoPostales_Port)(this)).IsUpdatedAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        wsTRH.pPostCode.GetRecIdFromKey_Result wsTRH.pPostCode.CodigoPostales_Port.GetRecIdFromKey(wsTRH.pPostCode.GetRecIdFromKey request) {
            return base.Channel.GetRecIdFromKey(request);
        }
        
        public string GetRecIdFromKey(string Key) {
            wsTRH.pPostCode.GetRecIdFromKey inValue = new wsTRH.pPostCode.GetRecIdFromKey();
            inValue.Key = Key;
            wsTRH.pPostCode.GetRecIdFromKey_Result retVal = ((wsTRH.pPostCode.CodigoPostales_Port)(this)).GetRecIdFromKey(inValue);
            return retVal.GetRecIdFromKey_Result1;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<wsTRH.pPostCode.GetRecIdFromKey_Result> wsTRH.pPostCode.CodigoPostales_Port.GetRecIdFromKeyAsync(wsTRH.pPostCode.GetRecIdFromKey request) {
            return base.Channel.GetRecIdFromKeyAsync(request);
        }
        
        public System.Threading.Tasks.Task<wsTRH.pPostCode.GetRecIdFromKey_Result> GetRecIdFromKeyAsync(string Key) {
            wsTRH.pPostCode.GetRecIdFromKey inValue = new wsTRH.pPostCode.GetRecIdFromKey();
            inValue.Key = Key;
            return ((wsTRH.pPostCode.CodigoPostales_Port)(this)).GetRecIdFromKeyAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        wsTRH.pPostCode.Create_Result wsTRH.pPostCode.CodigoPostales_Port.Create(wsTRH.pPostCode.Create request) {
            return base.Channel.Create(request);
        }
        
        public void Create(ref wsTRH.pPostCode.CodigoPostales CodigoPostales) {
            wsTRH.pPostCode.Create inValue = new wsTRH.pPostCode.Create();
            inValue.CodigoPostales = CodigoPostales;
            wsTRH.pPostCode.Create_Result retVal = ((wsTRH.pPostCode.CodigoPostales_Port)(this)).Create(inValue);
            CodigoPostales = retVal.CodigoPostales;
        }
        
        public System.Threading.Tasks.Task<wsTRH.pPostCode.Create_Result> CreateAsync(wsTRH.pPostCode.Create request) {
            return base.Channel.CreateAsync(request);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        wsTRH.pPostCode.CreateMultiple_Result wsTRH.pPostCode.CodigoPostales_Port.CreateMultiple(wsTRH.pPostCode.CreateMultiple request) {
            return base.Channel.CreateMultiple(request);
        }
        
        public void CreateMultiple(ref wsTRH.pPostCode.CodigoPostales[] CodigoPostales_List) {
            wsTRH.pPostCode.CreateMultiple inValue = new wsTRH.pPostCode.CreateMultiple();
            inValue.CodigoPostales_List = CodigoPostales_List;
            wsTRH.pPostCode.CreateMultiple_Result retVal = ((wsTRH.pPostCode.CodigoPostales_Port)(this)).CreateMultiple(inValue);
            CodigoPostales_List = retVal.CodigoPostales_List;
        }
        
        public System.Threading.Tasks.Task<wsTRH.pPostCode.CreateMultiple_Result> CreateMultipleAsync(wsTRH.pPostCode.CreateMultiple request) {
            return base.Channel.CreateMultipleAsync(request);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        wsTRH.pPostCode.Update_Result wsTRH.pPostCode.CodigoPostales_Port.Update(wsTRH.pPostCode.Update request) {
            return base.Channel.Update(request);
        }
        
        public void Update(ref wsTRH.pPostCode.CodigoPostales CodigoPostales) {
            wsTRH.pPostCode.Update inValue = new wsTRH.pPostCode.Update();
            inValue.CodigoPostales = CodigoPostales;
            wsTRH.pPostCode.Update_Result retVal = ((wsTRH.pPostCode.CodigoPostales_Port)(this)).Update(inValue);
            CodigoPostales = retVal.CodigoPostales;
        }
        
        public System.Threading.Tasks.Task<wsTRH.pPostCode.Update_Result> UpdateAsync(wsTRH.pPostCode.Update request) {
            return base.Channel.UpdateAsync(request);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        wsTRH.pPostCode.UpdateMultiple_Result wsTRH.pPostCode.CodigoPostales_Port.UpdateMultiple(wsTRH.pPostCode.UpdateMultiple request) {
            return base.Channel.UpdateMultiple(request);
        }
        
        public void UpdateMultiple(ref wsTRH.pPostCode.CodigoPostales[] CodigoPostales_List) {
            wsTRH.pPostCode.UpdateMultiple inValue = new wsTRH.pPostCode.UpdateMultiple();
            inValue.CodigoPostales_List = CodigoPostales_List;
            wsTRH.pPostCode.UpdateMultiple_Result retVal = ((wsTRH.pPostCode.CodigoPostales_Port)(this)).UpdateMultiple(inValue);
            CodigoPostales_List = retVal.CodigoPostales_List;
        }
        
        public System.Threading.Tasks.Task<wsTRH.pPostCode.UpdateMultiple_Result> UpdateMultipleAsync(wsTRH.pPostCode.UpdateMultiple request) {
            return base.Channel.UpdateMultipleAsync(request);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        wsTRH.pPostCode.Delete_Result wsTRH.pPostCode.CodigoPostales_Port.Delete(wsTRH.pPostCode.Delete request) {
            return base.Channel.Delete(request);
        }
        
        public bool Delete(string Key) {
            wsTRH.pPostCode.Delete inValue = new wsTRH.pPostCode.Delete();
            inValue.Key = Key;
            wsTRH.pPostCode.Delete_Result retVal = ((wsTRH.pPostCode.CodigoPostales_Port)(this)).Delete(inValue);
            return retVal.Delete_Result1;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<wsTRH.pPostCode.Delete_Result> wsTRH.pPostCode.CodigoPostales_Port.DeleteAsync(wsTRH.pPostCode.Delete request) {
            return base.Channel.DeleteAsync(request);
        }
        
        public System.Threading.Tasks.Task<wsTRH.pPostCode.Delete_Result> DeleteAsync(string Key) {
            wsTRH.pPostCode.Delete inValue = new wsTRH.pPostCode.Delete();
            inValue.Key = Key;
            return ((wsTRH.pPostCode.CodigoPostales_Port)(this)).DeleteAsync(inValue);
        }
    }
}
