//------------------------------------------------------------------------------
// <auto-generated>
//     Este código fue generado por una herramienta.
//     Versión de runtime:4.0.30319.42000
//
//     Los cambios en este archivo podrían causar un comportamiento incorrecto y se perderán si
//     se vuelve a generar el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace RepositoryWebServiceTRH.ClientesContext {
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(Namespace="urn:microsoft-dynamics-schemas/page/clientes", ConfigurationName="ClientesContext.Clientes_Port")]
    public interface Clientes_Port {
        
        // CODEGEN: Se está generando un contrato de mensaje, ya que el nombre de contenedor (Read_Result) del mensaje Read_Result no coincide con el valor predeterminado (Read)
        [System.ServiceModel.OperationContractAttribute(Action="urn:microsoft-dynamics-schemas/page/clientes:Read", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        RepositoryWebServiceTRH.ClientesContext.Read_Result Read(RepositoryWebServiceTRH.ClientesContext.Read request);
        
        [System.ServiceModel.OperationContractAttribute(Action="urn:microsoft-dynamics-schemas/page/clientes:Read", ReplyAction="*")]
        System.Threading.Tasks.Task<RepositoryWebServiceTRH.ClientesContext.Read_Result> ReadAsync(RepositoryWebServiceTRH.ClientesContext.Read request);
        
        // CODEGEN: Se está generando un contrato de mensaje, ya que el nombre de contenedor (ReadByRecId_Result) del mensaje ReadByRecId_Result no coincide con el valor predeterminado (ReadByRecId)
        [System.ServiceModel.OperationContractAttribute(Action="urn:microsoft-dynamics-schemas/page/clientes:ReadByRecId", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        RepositoryWebServiceTRH.ClientesContext.ReadByRecId_Result ReadByRecId(RepositoryWebServiceTRH.ClientesContext.ReadByRecId request);
        
        [System.ServiceModel.OperationContractAttribute(Action="urn:microsoft-dynamics-schemas/page/clientes:ReadByRecId", ReplyAction="*")]
        System.Threading.Tasks.Task<RepositoryWebServiceTRH.ClientesContext.ReadByRecId_Result> ReadByRecIdAsync(RepositoryWebServiceTRH.ClientesContext.ReadByRecId request);
        
        // CODEGEN: Se está generando un contrato de mensaje, ya que el nombre de contenedor (ReadMultiple_Result) del mensaje ReadMultiple_Result no coincide con el valor predeterminado (ReadMultiple)
        [System.ServiceModel.OperationContractAttribute(Action="urn:microsoft-dynamics-schemas/page/clientes:ReadMultiple", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        RepositoryWebServiceTRH.ClientesContext.ReadMultiple_Result ReadMultiple(RepositoryWebServiceTRH.ClientesContext.ReadMultiple request);
        
        [System.ServiceModel.OperationContractAttribute(Action="urn:microsoft-dynamics-schemas/page/clientes:ReadMultiple", ReplyAction="*")]
        System.Threading.Tasks.Task<RepositoryWebServiceTRH.ClientesContext.ReadMultiple_Result> ReadMultipleAsync(RepositoryWebServiceTRH.ClientesContext.ReadMultiple request);
        
        // CODEGEN: Se está generando un contrato de mensaje, ya que el nombre de contenedor (IsUpdated_Result) del mensaje IsUpdated_Result no coincide con el valor predeterminado (IsUpdated)
        [System.ServiceModel.OperationContractAttribute(Action="urn:microsoft-dynamics-schemas/page/clientes:IsUpdated", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        RepositoryWebServiceTRH.ClientesContext.IsUpdated_Result IsUpdated(RepositoryWebServiceTRH.ClientesContext.IsUpdated request);
        
        [System.ServiceModel.OperationContractAttribute(Action="urn:microsoft-dynamics-schemas/page/clientes:IsUpdated", ReplyAction="*")]
        System.Threading.Tasks.Task<RepositoryWebServiceTRH.ClientesContext.IsUpdated_Result> IsUpdatedAsync(RepositoryWebServiceTRH.ClientesContext.IsUpdated request);
        
        // CODEGEN: Se está generando un contrato de mensaje, ya que el nombre de contenedor (GetRecIdFromKey_Result) del mensaje GetRecIdFromKey_Result no coincide con el valor predeterminado (GetRecIdFromKey)
        [System.ServiceModel.OperationContractAttribute(Action="urn:microsoft-dynamics-schemas/page/clientes:GetRecIdFromKey", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        RepositoryWebServiceTRH.ClientesContext.GetRecIdFromKey_Result GetRecIdFromKey(RepositoryWebServiceTRH.ClientesContext.GetRecIdFromKey request);
        
        [System.ServiceModel.OperationContractAttribute(Action="urn:microsoft-dynamics-schemas/page/clientes:GetRecIdFromKey", ReplyAction="*")]
        System.Threading.Tasks.Task<RepositoryWebServiceTRH.ClientesContext.GetRecIdFromKey_Result> GetRecIdFromKeyAsync(RepositoryWebServiceTRH.ClientesContext.GetRecIdFromKey request);
        
        [System.ServiceModel.OperationContractAttribute(Action="urn:microsoft-dynamics-schemas/page/clientes:Create", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        RepositoryWebServiceTRH.ClientesContext.Create_Result Create(RepositoryWebServiceTRH.ClientesContext.Create request);
        
        // CODEGEN: Generando contrato de mensaje, ya que la operación tiene múltiples valores de devolución.
        [System.ServiceModel.OperationContractAttribute(Action="urn:microsoft-dynamics-schemas/page/clientes:Create", ReplyAction="*")]
        System.Threading.Tasks.Task<RepositoryWebServiceTRH.ClientesContext.Create_Result> CreateAsync(RepositoryWebServiceTRH.ClientesContext.Create request);
        
        [System.ServiceModel.OperationContractAttribute(Action="urn:microsoft-dynamics-schemas/page/clientes:CreateMultiple", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        RepositoryWebServiceTRH.ClientesContext.CreateMultiple_Result CreateMultiple(RepositoryWebServiceTRH.ClientesContext.CreateMultiple request);
        
        // CODEGEN: Generando contrato de mensaje, ya que la operación tiene múltiples valores de devolución.
        [System.ServiceModel.OperationContractAttribute(Action="urn:microsoft-dynamics-schemas/page/clientes:CreateMultiple", ReplyAction="*")]
        System.Threading.Tasks.Task<RepositoryWebServiceTRH.ClientesContext.CreateMultiple_Result> CreateMultipleAsync(RepositoryWebServiceTRH.ClientesContext.CreateMultiple request);
        
        [System.ServiceModel.OperationContractAttribute(Action="urn:microsoft-dynamics-schemas/page/clientes:Update", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        RepositoryWebServiceTRH.ClientesContext.Update_Result Update(RepositoryWebServiceTRH.ClientesContext.Update request);
        
        // CODEGEN: Generando contrato de mensaje, ya que la operación tiene múltiples valores de devolución.
        [System.ServiceModel.OperationContractAttribute(Action="urn:microsoft-dynamics-schemas/page/clientes:Update", ReplyAction="*")]
        System.Threading.Tasks.Task<RepositoryWebServiceTRH.ClientesContext.Update_Result> UpdateAsync(RepositoryWebServiceTRH.ClientesContext.Update request);
        
        [System.ServiceModel.OperationContractAttribute(Action="urn:microsoft-dynamics-schemas/page/clientes:UpdateMultiple", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        RepositoryWebServiceTRH.ClientesContext.UpdateMultiple_Result UpdateMultiple(RepositoryWebServiceTRH.ClientesContext.UpdateMultiple request);
        
        // CODEGEN: Generando contrato de mensaje, ya que la operación tiene múltiples valores de devolución.
        [System.ServiceModel.OperationContractAttribute(Action="urn:microsoft-dynamics-schemas/page/clientes:UpdateMultiple", ReplyAction="*")]
        System.Threading.Tasks.Task<RepositoryWebServiceTRH.ClientesContext.UpdateMultiple_Result> UpdateMultipleAsync(RepositoryWebServiceTRH.ClientesContext.UpdateMultiple request);
        
        // CODEGEN: Se está generando un contrato de mensaje, ya que el nombre de contenedor (Delete_Result) del mensaje Delete_Result no coincide con el valor predeterminado (Delete)
        [System.ServiceModel.OperationContractAttribute(Action="urn:microsoft-dynamics-schemas/page/clientes:Delete", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        RepositoryWebServiceTRH.ClientesContext.Delete_Result Delete(RepositoryWebServiceTRH.ClientesContext.Delete request);
        
        [System.ServiceModel.OperationContractAttribute(Action="urn:microsoft-dynamics-schemas/page/clientes:Delete", ReplyAction="*")]
        System.Threading.Tasks.Task<RepositoryWebServiceTRH.ClientesContext.Delete_Result> DeleteAsync(RepositoryWebServiceTRH.ClientesContext.Delete request);
    }
    
    /// <comentarios/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.6.1064.2")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="urn:microsoft-dynamics-schemas/page/clientes")]
    public partial class Clientes : object, System.ComponentModel.INotifyPropertyChanged {
        
        private string keyField;
        
        private string noField;
        
        private string nameField;
        
        private string location_CodeField;
        
        private string post_CodeField;
        
        private string country_Region_CodeField;
        
        private string phone_NoField;
        
        private string fax_NoField;
        
        private string addressField;
        
        private string address_2Field;
        
        private string cityField;
        
        private string contactField;
        
        private string salesperson_CodeField;
        
        private string dias_PagoField;
        
        private string forma_PagoField;
        
        private string search_NameField;
        
        private decimal credit_Limit_LCYField;
        
        private bool credit_Limit_LCYFieldSpecified;
        
        private decimal cred_Max_CESCEField;
        
        private bool cred_Max_CESCEFieldSpecified;
        
        private decimal balanceField;
        
        private bool balanceFieldSpecified;
        
        private string e_MailField;
        
        private string home_PageField;
        
        private string vAT_Registration_NoField;
        
        private string countyField;
        
        private string name_2Field;
        
        private string codigo_Cliente_ContactoField;
        
        private string eMail_AdministrativoField;
        
        private decimal saldo_DisponibleField;
        
        private bool saldo_DisponibleFieldSpecified;
        
        private decimal saldo_VencidosField;
        
        private bool saldo_VencidosFieldSpecified;
        
        private decimal saldoField;
        
        private bool saldoFieldSpecified;
        
        /// <comentarios/>
        [System.Xml.Serialization.XmlElementAttribute(Order=0)]
        public string Key {
            get {
                return this.keyField;
            }
            set {
                this.keyField = value;
                this.RaisePropertyChanged("Key");
            }
        }
        
        /// <comentarios/>
        [System.Xml.Serialization.XmlElementAttribute(Order=1)]
        public string No {
            get {
                return this.noField;
            }
            set {
                this.noField = value;
                this.RaisePropertyChanged("No");
            }
        }
        
        /// <comentarios/>
        [System.Xml.Serialization.XmlElementAttribute(Order=2)]
        public string Name {
            get {
                return this.nameField;
            }
            set {
                this.nameField = value;
                this.RaisePropertyChanged("Name");
            }
        }
        
        /// <comentarios/>
        [System.Xml.Serialization.XmlElementAttribute(Order=3)]
        public string Location_Code {
            get {
                return this.location_CodeField;
            }
            set {
                this.location_CodeField = value;
                this.RaisePropertyChanged("Location_Code");
            }
        }
        
        /// <comentarios/>
        [System.Xml.Serialization.XmlElementAttribute(Order=4)]
        public string Post_Code {
            get {
                return this.post_CodeField;
            }
            set {
                this.post_CodeField = value;
                this.RaisePropertyChanged("Post_Code");
            }
        }
        
        /// <comentarios/>
        [System.Xml.Serialization.XmlElementAttribute(Order=5)]
        public string Country_Region_Code {
            get {
                return this.country_Region_CodeField;
            }
            set {
                this.country_Region_CodeField = value;
                this.RaisePropertyChanged("Country_Region_Code");
            }
        }
        
        /// <comentarios/>
        [System.Xml.Serialization.XmlElementAttribute(Order=6)]
        public string Phone_No {
            get {
                return this.phone_NoField;
            }
            set {
                this.phone_NoField = value;
                this.RaisePropertyChanged("Phone_No");
            }
        }
        
        /// <comentarios/>
        [System.Xml.Serialization.XmlElementAttribute(Order=7)]
        public string Fax_No {
            get {
                return this.fax_NoField;
            }
            set {
                this.fax_NoField = value;
                this.RaisePropertyChanged("Fax_No");
            }
        }
        
        /// <comentarios/>
        [System.Xml.Serialization.XmlElementAttribute(Order=8)]
        public string Address {
            get {
                return this.addressField;
            }
            set {
                this.addressField = value;
                this.RaisePropertyChanged("Address");
            }
        }
        
        /// <comentarios/>
        [System.Xml.Serialization.XmlElementAttribute(Order=9)]
        public string Address_2 {
            get {
                return this.address_2Field;
            }
            set {
                this.address_2Field = value;
                this.RaisePropertyChanged("Address_2");
            }
        }
        
        /// <comentarios/>
        [System.Xml.Serialization.XmlElementAttribute(Order=10)]
        public string City {
            get {
                return this.cityField;
            }
            set {
                this.cityField = value;
                this.RaisePropertyChanged("City");
            }
        }
        
        /// <comentarios/>
        [System.Xml.Serialization.XmlElementAttribute(Order=11)]
        public string Contact {
            get {
                return this.contactField;
            }
            set {
                this.contactField = value;
                this.RaisePropertyChanged("Contact");
            }
        }
        
        /// <comentarios/>
        [System.Xml.Serialization.XmlElementAttribute(Order=12)]
        public string Salesperson_Code {
            get {
                return this.salesperson_CodeField;
            }
            set {
                this.salesperson_CodeField = value;
                this.RaisePropertyChanged("Salesperson_Code");
            }
        }
        
        /// <comentarios/>
        [System.Xml.Serialization.XmlElementAttribute(Order=13)]
        public string Dias_Pago {
            get {
                return this.dias_PagoField;
            }
            set {
                this.dias_PagoField = value;
                this.RaisePropertyChanged("Dias_Pago");
            }
        }
        
        /// <comentarios/>
        [System.Xml.Serialization.XmlElementAttribute(Order=14)]
        public string Forma_Pago {
            get {
                return this.forma_PagoField;
            }
            set {
                this.forma_PagoField = value;
                this.RaisePropertyChanged("Forma_Pago");
            }
        }
        
        /// <comentarios/>
        [System.Xml.Serialization.XmlElementAttribute(Order=15)]
        public string Search_Name {
            get {
                return this.search_NameField;
            }
            set {
                this.search_NameField = value;
                this.RaisePropertyChanged("Search_Name");
            }
        }
        
        /// <comentarios/>
        [System.Xml.Serialization.XmlElementAttribute(Order=16)]
        public decimal Credit_Limit_LCY {
            get {
                return this.credit_Limit_LCYField;
            }
            set {
                this.credit_Limit_LCYField = value;
                this.RaisePropertyChanged("Credit_Limit_LCY");
            }
        }
        
        /// <comentarios/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool Credit_Limit_LCYSpecified {
            get {
                return this.credit_Limit_LCYFieldSpecified;
            }
            set {
                this.credit_Limit_LCYFieldSpecified = value;
                this.RaisePropertyChanged("Credit_Limit_LCYSpecified");
            }
        }
        
        /// <comentarios/>
        [System.Xml.Serialization.XmlElementAttribute(Order=17)]
        public decimal Cred_Max_CESCE {
            get {
                return this.cred_Max_CESCEField;
            }
            set {
                this.cred_Max_CESCEField = value;
                this.RaisePropertyChanged("Cred_Max_CESCE");
            }
        }
        
        /// <comentarios/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool Cred_Max_CESCESpecified {
            get {
                return this.cred_Max_CESCEFieldSpecified;
            }
            set {
                this.cred_Max_CESCEFieldSpecified = value;
                this.RaisePropertyChanged("Cred_Max_CESCESpecified");
            }
        }
        
        /// <comentarios/>
        [System.Xml.Serialization.XmlElementAttribute(Order=18)]
        public decimal Balance {
            get {
                return this.balanceField;
            }
            set {
                this.balanceField = value;
                this.RaisePropertyChanged("Balance");
            }
        }
        
        /// <comentarios/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool BalanceSpecified {
            get {
                return this.balanceFieldSpecified;
            }
            set {
                this.balanceFieldSpecified = value;
                this.RaisePropertyChanged("BalanceSpecified");
            }
        }
        
        /// <comentarios/>
        [System.Xml.Serialization.XmlElementAttribute(Order=19)]
        public string E_Mail {
            get {
                return this.e_MailField;
            }
            set {
                this.e_MailField = value;
                this.RaisePropertyChanged("E_Mail");
            }
        }
        
        /// <comentarios/>
        [System.Xml.Serialization.XmlElementAttribute(Order=20)]
        public string Home_Page {
            get {
                return this.home_PageField;
            }
            set {
                this.home_PageField = value;
                this.RaisePropertyChanged("Home_Page");
            }
        }
        
        /// <comentarios/>
        [System.Xml.Serialization.XmlElementAttribute(Order=21)]
        public string VAT_Registration_No {
            get {
                return this.vAT_Registration_NoField;
            }
            set {
                this.vAT_Registration_NoField = value;
                this.RaisePropertyChanged("VAT_Registration_No");
            }
        }
        
        /// <comentarios/>
        [System.Xml.Serialization.XmlElementAttribute(Order=22)]
        public string County {
            get {
                return this.countyField;
            }
            set {
                this.countyField = value;
                this.RaisePropertyChanged("County");
            }
        }
        
        /// <comentarios/>
        [System.Xml.Serialization.XmlElementAttribute(Order=23)]
        public string Name_2 {
            get {
                return this.name_2Field;
            }
            set {
                this.name_2Field = value;
                this.RaisePropertyChanged("Name_2");
            }
        }
        
        /// <comentarios/>
        [System.Xml.Serialization.XmlElementAttribute(Order=24)]
        public string Codigo_Cliente_Contacto {
            get {
                return this.codigo_Cliente_ContactoField;
            }
            set {
                this.codigo_Cliente_ContactoField = value;
                this.RaisePropertyChanged("Codigo_Cliente_Contacto");
            }
        }
        
        /// <comentarios/>
        [System.Xml.Serialization.XmlElementAttribute(Order=25)]
        public string EMail_Administrativo {
            get {
                return this.eMail_AdministrativoField;
            }
            set {
                this.eMail_AdministrativoField = value;
                this.RaisePropertyChanged("EMail_Administrativo");
            }
        }
        
        /// <comentarios/>
        [System.Xml.Serialization.XmlElementAttribute(Order=26)]
        public decimal Saldo_Disponible {
            get {
                return this.saldo_DisponibleField;
            }
            set {
                this.saldo_DisponibleField = value;
                this.RaisePropertyChanged("Saldo_Disponible");
            }
        }
        
        /// <comentarios/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool Saldo_DisponibleSpecified {
            get {
                return this.saldo_DisponibleFieldSpecified;
            }
            set {
                this.saldo_DisponibleFieldSpecified = value;
                this.RaisePropertyChanged("Saldo_DisponibleSpecified");
            }
        }
        
        /// <comentarios/>
        [System.Xml.Serialization.XmlElementAttribute(Order=27)]
        public decimal Saldo_Vencidos {
            get {
                return this.saldo_VencidosField;
            }
            set {
                this.saldo_VencidosField = value;
                this.RaisePropertyChanged("Saldo_Vencidos");
            }
        }
        
        /// <comentarios/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool Saldo_VencidosSpecified {
            get {
                return this.saldo_VencidosFieldSpecified;
            }
            set {
                this.saldo_VencidosFieldSpecified = value;
                this.RaisePropertyChanged("Saldo_VencidosSpecified");
            }
        }
        
        /// <comentarios/>
        [System.Xml.Serialization.XmlElementAttribute(Order=28)]
        public decimal Saldo {
            get {
                return this.saldoField;
            }
            set {
                this.saldoField = value;
                this.RaisePropertyChanged("Saldo");
            }
        }
        
        /// <comentarios/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool SaldoSpecified {
            get {
                return this.saldoFieldSpecified;
            }
            set {
                this.saldoFieldSpecified = value;
                this.RaisePropertyChanged("SaldoSpecified");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    /// <comentarios/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.6.1064.2")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="urn:microsoft-dynamics-schemas/page/clientes")]
    public partial class Clientes_Filter : object, System.ComponentModel.INotifyPropertyChanged {
        
        private Clientes_Fields fieldField;
        
        private string criteriaField;
        
        /// <comentarios/>
        [System.Xml.Serialization.XmlElementAttribute(Order=0)]
        public Clientes_Fields Field {
            get {
                return this.fieldField;
            }
            set {
                this.fieldField = value;
                this.RaisePropertyChanged("Field");
            }
        }
        
        /// <comentarios/>
        [System.Xml.Serialization.XmlElementAttribute(Order=1)]
        public string Criteria {
            get {
                return this.criteriaField;
            }
            set {
                this.criteriaField = value;
                this.RaisePropertyChanged("Criteria");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    /// <comentarios/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.6.1064.2")]
    [System.SerializableAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="urn:microsoft-dynamics-schemas/page/clientes")]
    public enum Clientes_Fields {
        
        /// <comentarios/>
        No,
        
        /// <comentarios/>
        Name,
        
        /// <comentarios/>
        Location_Code,
        
        /// <comentarios/>
        Post_Code,
        
        /// <comentarios/>
        Country_Region_Code,
        
        /// <comentarios/>
        Phone_No,
        
        /// <comentarios/>
        Fax_No,
        
        /// <comentarios/>
        Address,
        
        /// <comentarios/>
        Address_2,
        
        /// <comentarios/>
        City,
        
        /// <comentarios/>
        Contact,
        
        /// <comentarios/>
        Salesperson_Code,
        
        /// <comentarios/>
        Dias_Pago,
        
        /// <comentarios/>
        Forma_Pago,
        
        /// <comentarios/>
        Search_Name,
        
        /// <comentarios/>
        Credit_Limit_LCY,
        
        /// <comentarios/>
        Cred_Max_CESCE,
        
        /// <comentarios/>
        Balance,
        
        /// <comentarios/>
        E_Mail,
        
        /// <comentarios/>
        Home_Page,
        
        /// <comentarios/>
        VAT_Registration_No,
        
        /// <comentarios/>
        County,
        
        /// <comentarios/>
        Name_2,
        
        /// <comentarios/>
        Codigo_Cliente_Contacto,
        
        /// <comentarios/>
        EMail_Administrativo,
        
        /// <comentarios/>
        Saldo_Disponible,
        
        /// <comentarios/>
        Saldo_Vencidos,
        
        /// <comentarios/>
        Saldo,
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="Read", WrapperNamespace="urn:microsoft-dynamics-schemas/page/clientes", IsWrapped=true)]
    public partial class Read {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="urn:microsoft-dynamics-schemas/page/clientes", Order=0)]
        public string No;
        
        public Read() {
        }
        
        public Read(string No) {
            this.No = No;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="Read_Result", WrapperNamespace="urn:microsoft-dynamics-schemas/page/clientes", IsWrapped=true)]
    public partial class Read_Result {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="urn:microsoft-dynamics-schemas/page/clientes", Order=0)]
        public RepositoryWebServiceTRH.ClientesContext.Clientes Clientes;
        
        public Read_Result() {
        }
        
        public Read_Result(RepositoryWebServiceTRH.ClientesContext.Clientes Clientes) {
            this.Clientes = Clientes;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="ReadByRecId", WrapperNamespace="urn:microsoft-dynamics-schemas/page/clientes", IsWrapped=true)]
    public partial class ReadByRecId {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="urn:microsoft-dynamics-schemas/page/clientes", Order=0)]
        public string recId;
        
        public ReadByRecId() {
        }
        
        public ReadByRecId(string recId) {
            this.recId = recId;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="ReadByRecId_Result", WrapperNamespace="urn:microsoft-dynamics-schemas/page/clientes", IsWrapped=true)]
    public partial class ReadByRecId_Result {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="urn:microsoft-dynamics-schemas/page/clientes", Order=0)]
        public RepositoryWebServiceTRH.ClientesContext.Clientes Clientes;
        
        public ReadByRecId_Result() {
        }
        
        public ReadByRecId_Result(RepositoryWebServiceTRH.ClientesContext.Clientes Clientes) {
            this.Clientes = Clientes;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="ReadMultiple", WrapperNamespace="urn:microsoft-dynamics-schemas/page/clientes", IsWrapped=true)]
    public partial class ReadMultiple {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="urn:microsoft-dynamics-schemas/page/clientes", Order=0)]
        [System.Xml.Serialization.XmlElementAttribute("filter")]
        public RepositoryWebServiceTRH.ClientesContext.Clientes_Filter[] filter;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="urn:microsoft-dynamics-schemas/page/clientes", Order=1)]
        public string bookmarkKey;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="urn:microsoft-dynamics-schemas/page/clientes", Order=2)]
        public int setSize;
        
        public ReadMultiple() {
        }
        
        public ReadMultiple(RepositoryWebServiceTRH.ClientesContext.Clientes_Filter[] filter, string bookmarkKey, int setSize) {
            this.filter = filter;
            this.bookmarkKey = bookmarkKey;
            this.setSize = setSize;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="ReadMultiple_Result", WrapperNamespace="urn:microsoft-dynamics-schemas/page/clientes", IsWrapped=true)]
    public partial class ReadMultiple_Result {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="ReadMultiple_Result", Namespace="urn:microsoft-dynamics-schemas/page/clientes", Order=0)]
        [System.Xml.Serialization.XmlArrayItemAttribute(IsNullable=false)]
        public RepositoryWebServiceTRH.ClientesContext.Clientes[] ReadMultiple_Result1;
        
        public ReadMultiple_Result() {
        }
        
        public ReadMultiple_Result(RepositoryWebServiceTRH.ClientesContext.Clientes[] ReadMultiple_Result1) {
            this.ReadMultiple_Result1 = ReadMultiple_Result1;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="IsUpdated", WrapperNamespace="urn:microsoft-dynamics-schemas/page/clientes", IsWrapped=true)]
    public partial class IsUpdated {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="urn:microsoft-dynamics-schemas/page/clientes", Order=0)]
        public string Key;
        
        public IsUpdated() {
        }
        
        public IsUpdated(string Key) {
            this.Key = Key;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="IsUpdated_Result", WrapperNamespace="urn:microsoft-dynamics-schemas/page/clientes", IsWrapped=true)]
    public partial class IsUpdated_Result {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="IsUpdated_Result", Namespace="urn:microsoft-dynamics-schemas/page/clientes", Order=0)]
        public bool IsUpdated_Result1;
        
        public IsUpdated_Result() {
        }
        
        public IsUpdated_Result(bool IsUpdated_Result1) {
            this.IsUpdated_Result1 = IsUpdated_Result1;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="GetRecIdFromKey", WrapperNamespace="urn:microsoft-dynamics-schemas/page/clientes", IsWrapped=true)]
    public partial class GetRecIdFromKey {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="urn:microsoft-dynamics-schemas/page/clientes", Order=0)]
        public string Key;
        
        public GetRecIdFromKey() {
        }
        
        public GetRecIdFromKey(string Key) {
            this.Key = Key;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="GetRecIdFromKey_Result", WrapperNamespace="urn:microsoft-dynamics-schemas/page/clientes", IsWrapped=true)]
    public partial class GetRecIdFromKey_Result {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="GetRecIdFromKey_Result", Namespace="urn:microsoft-dynamics-schemas/page/clientes", Order=0)]
        public string GetRecIdFromKey_Result1;
        
        public GetRecIdFromKey_Result() {
        }
        
        public GetRecIdFromKey_Result(string GetRecIdFromKey_Result1) {
            this.GetRecIdFromKey_Result1 = GetRecIdFromKey_Result1;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.MessageContractAttribute(WrapperName="Create", WrapperNamespace="urn:microsoft-dynamics-schemas/page/clientes", IsWrapped=true)]
    public partial class Create {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="urn:microsoft-dynamics-schemas/page/clientes", Order=0)]
        public RepositoryWebServiceTRH.ClientesContext.Clientes Clientes;
        
        public Create() {
        }
        
        public Create(RepositoryWebServiceTRH.ClientesContext.Clientes Clientes) {
            this.Clientes = Clientes;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.MessageContractAttribute(WrapperName="Create_Result", WrapperNamespace="urn:microsoft-dynamics-schemas/page/clientes", IsWrapped=true)]
    public partial class Create_Result {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="urn:microsoft-dynamics-schemas/page/clientes", Order=0)]
        public RepositoryWebServiceTRH.ClientesContext.Clientes Clientes;
        
        public Create_Result() {
        }
        
        public Create_Result(RepositoryWebServiceTRH.ClientesContext.Clientes Clientes) {
            this.Clientes = Clientes;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.MessageContractAttribute(WrapperName="CreateMultiple", WrapperNamespace="urn:microsoft-dynamics-schemas/page/clientes", IsWrapped=true)]
    public partial class CreateMultiple {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="urn:microsoft-dynamics-schemas/page/clientes", Order=0)]
        [System.Xml.Serialization.XmlArrayItemAttribute(IsNullable=false)]
        public RepositoryWebServiceTRH.ClientesContext.Clientes[] Clientes_List;
        
        public CreateMultiple() {
        }
        
        public CreateMultiple(RepositoryWebServiceTRH.ClientesContext.Clientes[] Clientes_List) {
            this.Clientes_List = Clientes_List;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.MessageContractAttribute(WrapperName="CreateMultiple_Result", WrapperNamespace="urn:microsoft-dynamics-schemas/page/clientes", IsWrapped=true)]
    public partial class CreateMultiple_Result {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="urn:microsoft-dynamics-schemas/page/clientes", Order=0)]
        [System.Xml.Serialization.XmlArrayItemAttribute(IsNullable=false)]
        public RepositoryWebServiceTRH.ClientesContext.Clientes[] Clientes_List;
        
        public CreateMultiple_Result() {
        }
        
        public CreateMultiple_Result(RepositoryWebServiceTRH.ClientesContext.Clientes[] Clientes_List) {
            this.Clientes_List = Clientes_List;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.MessageContractAttribute(WrapperName="Update", WrapperNamespace="urn:microsoft-dynamics-schemas/page/clientes", IsWrapped=true)]
    public partial class Update {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="urn:microsoft-dynamics-schemas/page/clientes", Order=0)]
        public RepositoryWebServiceTRH.ClientesContext.Clientes Clientes;
        
        public Update() {
        }
        
        public Update(RepositoryWebServiceTRH.ClientesContext.Clientes Clientes) {
            this.Clientes = Clientes;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.MessageContractAttribute(WrapperName="Update_Result", WrapperNamespace="urn:microsoft-dynamics-schemas/page/clientes", IsWrapped=true)]
    public partial class Update_Result {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="urn:microsoft-dynamics-schemas/page/clientes", Order=0)]
        public RepositoryWebServiceTRH.ClientesContext.Clientes Clientes;
        
        public Update_Result() {
        }
        
        public Update_Result(RepositoryWebServiceTRH.ClientesContext.Clientes Clientes) {
            this.Clientes = Clientes;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.MessageContractAttribute(WrapperName="UpdateMultiple", WrapperNamespace="urn:microsoft-dynamics-schemas/page/clientes", IsWrapped=true)]
    public partial class UpdateMultiple {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="urn:microsoft-dynamics-schemas/page/clientes", Order=0)]
        [System.Xml.Serialization.XmlArrayItemAttribute(IsNullable=false)]
        public RepositoryWebServiceTRH.ClientesContext.Clientes[] Clientes_List;
        
        public UpdateMultiple() {
        }
        
        public UpdateMultiple(RepositoryWebServiceTRH.ClientesContext.Clientes[] Clientes_List) {
            this.Clientes_List = Clientes_List;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.MessageContractAttribute(WrapperName="UpdateMultiple_Result", WrapperNamespace="urn:microsoft-dynamics-schemas/page/clientes", IsWrapped=true)]
    public partial class UpdateMultiple_Result {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="urn:microsoft-dynamics-schemas/page/clientes", Order=0)]
        [System.Xml.Serialization.XmlArrayItemAttribute(IsNullable=false)]
        public RepositoryWebServiceTRH.ClientesContext.Clientes[] Clientes_List;
        
        public UpdateMultiple_Result() {
        }
        
        public UpdateMultiple_Result(RepositoryWebServiceTRH.ClientesContext.Clientes[] Clientes_List) {
            this.Clientes_List = Clientes_List;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="Delete", WrapperNamespace="urn:microsoft-dynamics-schemas/page/clientes", IsWrapped=true)]
    public partial class Delete {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="urn:microsoft-dynamics-schemas/page/clientes", Order=0)]
        public string Key;
        
        public Delete() {
        }
        
        public Delete(string Key) {
            this.Key = Key;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="Delete_Result", WrapperNamespace="urn:microsoft-dynamics-schemas/page/clientes", IsWrapped=true)]
    public partial class Delete_Result {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="Delete_Result", Namespace="urn:microsoft-dynamics-schemas/page/clientes", Order=0)]
        public bool Delete_Result1;
        
        public Delete_Result() {
        }
        
        public Delete_Result(bool Delete_Result1) {
            this.Delete_Result1 = Delete_Result1;
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface Clientes_PortChannel : RepositoryWebServiceTRH.ClientesContext.Clientes_Port, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class Clientes_PortClient : System.ServiceModel.ClientBase<RepositoryWebServiceTRH.ClientesContext.Clientes_Port>, RepositoryWebServiceTRH.ClientesContext.Clientes_Port {
        
        public Clientes_PortClient() {
        }
        
        public Clientes_PortClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public Clientes_PortClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public Clientes_PortClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public Clientes_PortClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        RepositoryWebServiceTRH.ClientesContext.Read_Result RepositoryWebServiceTRH.ClientesContext.Clientes_Port.Read(RepositoryWebServiceTRH.ClientesContext.Read request) {
            return base.Channel.Read(request);
        }
        
        public RepositoryWebServiceTRH.ClientesContext.Clientes Read(string No) {
            RepositoryWebServiceTRH.ClientesContext.Read inValue = new RepositoryWebServiceTRH.ClientesContext.Read();
            inValue.No = No;
            RepositoryWebServiceTRH.ClientesContext.Read_Result retVal = ((RepositoryWebServiceTRH.ClientesContext.Clientes_Port)(this)).Read(inValue);
            return retVal.Clientes;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<RepositoryWebServiceTRH.ClientesContext.Read_Result> RepositoryWebServiceTRH.ClientesContext.Clientes_Port.ReadAsync(RepositoryWebServiceTRH.ClientesContext.Read request) {
            return base.Channel.ReadAsync(request);
        }
        
        public System.Threading.Tasks.Task<RepositoryWebServiceTRH.ClientesContext.Read_Result> ReadAsync(string No) {
            RepositoryWebServiceTRH.ClientesContext.Read inValue = new RepositoryWebServiceTRH.ClientesContext.Read();
            inValue.No = No;
            return ((RepositoryWebServiceTRH.ClientesContext.Clientes_Port)(this)).ReadAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        RepositoryWebServiceTRH.ClientesContext.ReadByRecId_Result RepositoryWebServiceTRH.ClientesContext.Clientes_Port.ReadByRecId(RepositoryWebServiceTRH.ClientesContext.ReadByRecId request) {
            return base.Channel.ReadByRecId(request);
        }
        
        public RepositoryWebServiceTRH.ClientesContext.Clientes ReadByRecId(string recId) {
            RepositoryWebServiceTRH.ClientesContext.ReadByRecId inValue = new RepositoryWebServiceTRH.ClientesContext.ReadByRecId();
            inValue.recId = recId;
            RepositoryWebServiceTRH.ClientesContext.ReadByRecId_Result retVal = ((RepositoryWebServiceTRH.ClientesContext.Clientes_Port)(this)).ReadByRecId(inValue);
            return retVal.Clientes;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<RepositoryWebServiceTRH.ClientesContext.ReadByRecId_Result> RepositoryWebServiceTRH.ClientesContext.Clientes_Port.ReadByRecIdAsync(RepositoryWebServiceTRH.ClientesContext.ReadByRecId request) {
            return base.Channel.ReadByRecIdAsync(request);
        }
        
        public System.Threading.Tasks.Task<RepositoryWebServiceTRH.ClientesContext.ReadByRecId_Result> ReadByRecIdAsync(string recId) {
            RepositoryWebServiceTRH.ClientesContext.ReadByRecId inValue = new RepositoryWebServiceTRH.ClientesContext.ReadByRecId();
            inValue.recId = recId;
            return ((RepositoryWebServiceTRH.ClientesContext.Clientes_Port)(this)).ReadByRecIdAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        RepositoryWebServiceTRH.ClientesContext.ReadMultiple_Result RepositoryWebServiceTRH.ClientesContext.Clientes_Port.ReadMultiple(RepositoryWebServiceTRH.ClientesContext.ReadMultiple request) {
            return base.Channel.ReadMultiple(request);
        }
        
        public RepositoryWebServiceTRH.ClientesContext.Clientes[] ReadMultiple(RepositoryWebServiceTRH.ClientesContext.Clientes_Filter[] filter, string bookmarkKey, int setSize) {
            RepositoryWebServiceTRH.ClientesContext.ReadMultiple inValue = new RepositoryWebServiceTRH.ClientesContext.ReadMultiple();
            inValue.filter = filter;
            inValue.bookmarkKey = bookmarkKey;
            inValue.setSize = setSize;
            RepositoryWebServiceTRH.ClientesContext.ReadMultiple_Result retVal = ((RepositoryWebServiceTRH.ClientesContext.Clientes_Port)(this)).ReadMultiple(inValue);
            return retVal.ReadMultiple_Result1;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<RepositoryWebServiceTRH.ClientesContext.ReadMultiple_Result> RepositoryWebServiceTRH.ClientesContext.Clientes_Port.ReadMultipleAsync(RepositoryWebServiceTRH.ClientesContext.ReadMultiple request) {
            return base.Channel.ReadMultipleAsync(request);
        }
        
        public System.Threading.Tasks.Task<RepositoryWebServiceTRH.ClientesContext.ReadMultiple_Result> ReadMultipleAsync(RepositoryWebServiceTRH.ClientesContext.Clientes_Filter[] filter, string bookmarkKey, int setSize) {
            RepositoryWebServiceTRH.ClientesContext.ReadMultiple inValue = new RepositoryWebServiceTRH.ClientesContext.ReadMultiple();
            inValue.filter = filter;
            inValue.bookmarkKey = bookmarkKey;
            inValue.setSize = setSize;
            return ((RepositoryWebServiceTRH.ClientesContext.Clientes_Port)(this)).ReadMultipleAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        RepositoryWebServiceTRH.ClientesContext.IsUpdated_Result RepositoryWebServiceTRH.ClientesContext.Clientes_Port.IsUpdated(RepositoryWebServiceTRH.ClientesContext.IsUpdated request) {
            return base.Channel.IsUpdated(request);
        }
        
        public bool IsUpdated(string Key) {
            RepositoryWebServiceTRH.ClientesContext.IsUpdated inValue = new RepositoryWebServiceTRH.ClientesContext.IsUpdated();
            inValue.Key = Key;
            RepositoryWebServiceTRH.ClientesContext.IsUpdated_Result retVal = ((RepositoryWebServiceTRH.ClientesContext.Clientes_Port)(this)).IsUpdated(inValue);
            return retVal.IsUpdated_Result1;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<RepositoryWebServiceTRH.ClientesContext.IsUpdated_Result> RepositoryWebServiceTRH.ClientesContext.Clientes_Port.IsUpdatedAsync(RepositoryWebServiceTRH.ClientesContext.IsUpdated request) {
            return base.Channel.IsUpdatedAsync(request);
        }
        
        public System.Threading.Tasks.Task<RepositoryWebServiceTRH.ClientesContext.IsUpdated_Result> IsUpdatedAsync(string Key) {
            RepositoryWebServiceTRH.ClientesContext.IsUpdated inValue = new RepositoryWebServiceTRH.ClientesContext.IsUpdated();
            inValue.Key = Key;
            return ((RepositoryWebServiceTRH.ClientesContext.Clientes_Port)(this)).IsUpdatedAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        RepositoryWebServiceTRH.ClientesContext.GetRecIdFromKey_Result RepositoryWebServiceTRH.ClientesContext.Clientes_Port.GetRecIdFromKey(RepositoryWebServiceTRH.ClientesContext.GetRecIdFromKey request) {
            return base.Channel.GetRecIdFromKey(request);
        }
        
        public string GetRecIdFromKey(string Key) {
            RepositoryWebServiceTRH.ClientesContext.GetRecIdFromKey inValue = new RepositoryWebServiceTRH.ClientesContext.GetRecIdFromKey();
            inValue.Key = Key;
            RepositoryWebServiceTRH.ClientesContext.GetRecIdFromKey_Result retVal = ((RepositoryWebServiceTRH.ClientesContext.Clientes_Port)(this)).GetRecIdFromKey(inValue);
            return retVal.GetRecIdFromKey_Result1;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<RepositoryWebServiceTRH.ClientesContext.GetRecIdFromKey_Result> RepositoryWebServiceTRH.ClientesContext.Clientes_Port.GetRecIdFromKeyAsync(RepositoryWebServiceTRH.ClientesContext.GetRecIdFromKey request) {
            return base.Channel.GetRecIdFromKeyAsync(request);
        }
        
        public System.Threading.Tasks.Task<RepositoryWebServiceTRH.ClientesContext.GetRecIdFromKey_Result> GetRecIdFromKeyAsync(string Key) {
            RepositoryWebServiceTRH.ClientesContext.GetRecIdFromKey inValue = new RepositoryWebServiceTRH.ClientesContext.GetRecIdFromKey();
            inValue.Key = Key;
            return ((RepositoryWebServiceTRH.ClientesContext.Clientes_Port)(this)).GetRecIdFromKeyAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        RepositoryWebServiceTRH.ClientesContext.Create_Result RepositoryWebServiceTRH.ClientesContext.Clientes_Port.Create(RepositoryWebServiceTRH.ClientesContext.Create request) {
            return base.Channel.Create(request);
        }
        
        public void Create(ref RepositoryWebServiceTRH.ClientesContext.Clientes Clientes) {
            RepositoryWebServiceTRH.ClientesContext.Create inValue = new RepositoryWebServiceTRH.ClientesContext.Create();
            inValue.Clientes = Clientes;
            RepositoryWebServiceTRH.ClientesContext.Create_Result retVal = ((RepositoryWebServiceTRH.ClientesContext.Clientes_Port)(this)).Create(inValue);
            Clientes = retVal.Clientes;
        }
        
        public System.Threading.Tasks.Task<RepositoryWebServiceTRH.ClientesContext.Create_Result> CreateAsync(RepositoryWebServiceTRH.ClientesContext.Create request) {
            return base.Channel.CreateAsync(request);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        RepositoryWebServiceTRH.ClientesContext.CreateMultiple_Result RepositoryWebServiceTRH.ClientesContext.Clientes_Port.CreateMultiple(RepositoryWebServiceTRH.ClientesContext.CreateMultiple request) {
            return base.Channel.CreateMultiple(request);
        }
        
        public void CreateMultiple(ref RepositoryWebServiceTRH.ClientesContext.Clientes[] Clientes_List) {
            RepositoryWebServiceTRH.ClientesContext.CreateMultiple inValue = new RepositoryWebServiceTRH.ClientesContext.CreateMultiple();
            inValue.Clientes_List = Clientes_List;
            RepositoryWebServiceTRH.ClientesContext.CreateMultiple_Result retVal = ((RepositoryWebServiceTRH.ClientesContext.Clientes_Port)(this)).CreateMultiple(inValue);
            Clientes_List = retVal.Clientes_List;
        }
        
        public System.Threading.Tasks.Task<RepositoryWebServiceTRH.ClientesContext.CreateMultiple_Result> CreateMultipleAsync(RepositoryWebServiceTRH.ClientesContext.CreateMultiple request) {
            return base.Channel.CreateMultipleAsync(request);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        RepositoryWebServiceTRH.ClientesContext.Update_Result RepositoryWebServiceTRH.ClientesContext.Clientes_Port.Update(RepositoryWebServiceTRH.ClientesContext.Update request) {
            return base.Channel.Update(request);
        }
        
        public void Update(ref RepositoryWebServiceTRH.ClientesContext.Clientes Clientes) {
            RepositoryWebServiceTRH.ClientesContext.Update inValue = new RepositoryWebServiceTRH.ClientesContext.Update();
            inValue.Clientes = Clientes;
            RepositoryWebServiceTRH.ClientesContext.Update_Result retVal = ((RepositoryWebServiceTRH.ClientesContext.Clientes_Port)(this)).Update(inValue);
            Clientes = retVal.Clientes;
        }
        
        public System.Threading.Tasks.Task<RepositoryWebServiceTRH.ClientesContext.Update_Result> UpdateAsync(RepositoryWebServiceTRH.ClientesContext.Update request) {
            return base.Channel.UpdateAsync(request);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        RepositoryWebServiceTRH.ClientesContext.UpdateMultiple_Result RepositoryWebServiceTRH.ClientesContext.Clientes_Port.UpdateMultiple(RepositoryWebServiceTRH.ClientesContext.UpdateMultiple request) {
            return base.Channel.UpdateMultiple(request);
        }
        
        public void UpdateMultiple(ref RepositoryWebServiceTRH.ClientesContext.Clientes[] Clientes_List) {
            RepositoryWebServiceTRH.ClientesContext.UpdateMultiple inValue = new RepositoryWebServiceTRH.ClientesContext.UpdateMultiple();
            inValue.Clientes_List = Clientes_List;
            RepositoryWebServiceTRH.ClientesContext.UpdateMultiple_Result retVal = ((RepositoryWebServiceTRH.ClientesContext.Clientes_Port)(this)).UpdateMultiple(inValue);
            Clientes_List = retVal.Clientes_List;
        }
        
        public System.Threading.Tasks.Task<RepositoryWebServiceTRH.ClientesContext.UpdateMultiple_Result> UpdateMultipleAsync(RepositoryWebServiceTRH.ClientesContext.UpdateMultiple request) {
            return base.Channel.UpdateMultipleAsync(request);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        RepositoryWebServiceTRH.ClientesContext.Delete_Result RepositoryWebServiceTRH.ClientesContext.Clientes_Port.Delete(RepositoryWebServiceTRH.ClientesContext.Delete request) {
            return base.Channel.Delete(request);
        }
        
        public bool Delete(string Key) {
            RepositoryWebServiceTRH.ClientesContext.Delete inValue = new RepositoryWebServiceTRH.ClientesContext.Delete();
            inValue.Key = Key;
            RepositoryWebServiceTRH.ClientesContext.Delete_Result retVal = ((RepositoryWebServiceTRH.ClientesContext.Clientes_Port)(this)).Delete(inValue);
            return retVal.Delete_Result1;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<RepositoryWebServiceTRH.ClientesContext.Delete_Result> RepositoryWebServiceTRH.ClientesContext.Clientes_Port.DeleteAsync(RepositoryWebServiceTRH.ClientesContext.Delete request) {
            return base.Channel.DeleteAsync(request);
        }
        
        public System.Threading.Tasks.Task<RepositoryWebServiceTRH.ClientesContext.Delete_Result> DeleteAsync(string Key) {
            RepositoryWebServiceTRH.ClientesContext.Delete inValue = new RepositoryWebServiceTRH.ClientesContext.Delete();
            inValue.Key = Key;
            return ((RepositoryWebServiceTRH.ClientesContext.Clientes_Port)(this)).DeleteAsync(inValue);
        }
    }
}
