//------------------------------------------------------------------------------
// <auto-generated>
//     Este código fue generado por una herramienta.
//     Versión de runtime:4.0.30319.42000
//
//     Los cambios en este archivo podrían causar un comportamiento incorrecto y se perderán si
//     se vuelve a generar el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace wsTRH.pDireccionesEnvio {
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(Namespace="urn:microsoft-dynamics-schemas/page/direccionesenvio", ConfigurationName="pDireccionesEnvio.DireccionesEnvio_Port")]
    public interface DireccionesEnvio_Port {
        
        // CODEGEN: Se está generando un contrato de mensaje, ya que el nombre de contenedor (Read_Result) del mensaje Read_Result no coincide con el valor predeterminado (Read)
        [System.ServiceModel.OperationContractAttribute(Action="urn:microsoft-dynamics-schemas/page/direccionesenvio:Read", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        wsTRH.pDireccionesEnvio.Read_Result Read(wsTRH.pDireccionesEnvio.Read request);
        
        [System.ServiceModel.OperationContractAttribute(Action="urn:microsoft-dynamics-schemas/page/direccionesenvio:Read", ReplyAction="*")]
        System.Threading.Tasks.Task<wsTRH.pDireccionesEnvio.Read_Result> ReadAsync(wsTRH.pDireccionesEnvio.Read request);
        
        // CODEGEN: Se está generando un contrato de mensaje, ya que el nombre de contenedor (ReadByRecId_Result) del mensaje ReadByRecId_Result no coincide con el valor predeterminado (ReadByRecId)
        [System.ServiceModel.OperationContractAttribute(Action="urn:microsoft-dynamics-schemas/page/direccionesenvio:ReadByRecId", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        wsTRH.pDireccionesEnvio.ReadByRecId_Result ReadByRecId(wsTRH.pDireccionesEnvio.ReadByRecId request);
        
        [System.ServiceModel.OperationContractAttribute(Action="urn:microsoft-dynamics-schemas/page/direccionesenvio:ReadByRecId", ReplyAction="*")]
        System.Threading.Tasks.Task<wsTRH.pDireccionesEnvio.ReadByRecId_Result> ReadByRecIdAsync(wsTRH.pDireccionesEnvio.ReadByRecId request);
        
        // CODEGEN: Se está generando un contrato de mensaje, ya que el nombre de contenedor (ReadMultiple_Result) del mensaje ReadMultiple_Result no coincide con el valor predeterminado (ReadMultiple)
        [System.ServiceModel.OperationContractAttribute(Action="urn:microsoft-dynamics-schemas/page/direccionesenvio:ReadMultiple", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        wsTRH.pDireccionesEnvio.ReadMultiple_Result ReadMultiple(wsTRH.pDireccionesEnvio.ReadMultiple request);
        
        [System.ServiceModel.OperationContractAttribute(Action="urn:microsoft-dynamics-schemas/page/direccionesenvio:ReadMultiple", ReplyAction="*")]
        System.Threading.Tasks.Task<wsTRH.pDireccionesEnvio.ReadMultiple_Result> ReadMultipleAsync(wsTRH.pDireccionesEnvio.ReadMultiple request);
        
        // CODEGEN: Se está generando un contrato de mensaje, ya que el nombre de contenedor (IsUpdated_Result) del mensaje IsUpdated_Result no coincide con el valor predeterminado (IsUpdated)
        [System.ServiceModel.OperationContractAttribute(Action="urn:microsoft-dynamics-schemas/page/direccionesenvio:IsUpdated", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        wsTRH.pDireccionesEnvio.IsUpdated_Result IsUpdated(wsTRH.pDireccionesEnvio.IsUpdated request);
        
        [System.ServiceModel.OperationContractAttribute(Action="urn:microsoft-dynamics-schemas/page/direccionesenvio:IsUpdated", ReplyAction="*")]
        System.Threading.Tasks.Task<wsTRH.pDireccionesEnvio.IsUpdated_Result> IsUpdatedAsync(wsTRH.pDireccionesEnvio.IsUpdated request);
        
        // CODEGEN: Se está generando un contrato de mensaje, ya que el nombre de contenedor (GetRecIdFromKey_Result) del mensaje GetRecIdFromKey_Result no coincide con el valor predeterminado (GetRecIdFromKey)
        [System.ServiceModel.OperationContractAttribute(Action="urn:microsoft-dynamics-schemas/page/direccionesenvio:GetRecIdFromKey", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        wsTRH.pDireccionesEnvio.GetRecIdFromKey_Result GetRecIdFromKey(wsTRH.pDireccionesEnvio.GetRecIdFromKey request);
        
        [System.ServiceModel.OperationContractAttribute(Action="urn:microsoft-dynamics-schemas/page/direccionesenvio:GetRecIdFromKey", ReplyAction="*")]
        System.Threading.Tasks.Task<wsTRH.pDireccionesEnvio.GetRecIdFromKey_Result> GetRecIdFromKeyAsync(wsTRH.pDireccionesEnvio.GetRecIdFromKey request);
        
        [System.ServiceModel.OperationContractAttribute(Action="urn:microsoft-dynamics-schemas/page/direccionesenvio:Create", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        wsTRH.pDireccionesEnvio.Create_Result Create(wsTRH.pDireccionesEnvio.Create request);
        
        // CODEGEN: Generando contrato de mensaje, ya que la operación tiene múltiples valores de devolución.
        [System.ServiceModel.OperationContractAttribute(Action="urn:microsoft-dynamics-schemas/page/direccionesenvio:Create", ReplyAction="*")]
        System.Threading.Tasks.Task<wsTRH.pDireccionesEnvio.Create_Result> CreateAsync(wsTRH.pDireccionesEnvio.Create request);
        
        [System.ServiceModel.OperationContractAttribute(Action="urn:microsoft-dynamics-schemas/page/direccionesenvio:CreateMultiple", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        wsTRH.pDireccionesEnvio.CreateMultiple_Result CreateMultiple(wsTRH.pDireccionesEnvio.CreateMultiple request);
        
        // CODEGEN: Generando contrato de mensaje, ya que la operación tiene múltiples valores de devolución.
        [System.ServiceModel.OperationContractAttribute(Action="urn:microsoft-dynamics-schemas/page/direccionesenvio:CreateMultiple", ReplyAction="*")]
        System.Threading.Tasks.Task<wsTRH.pDireccionesEnvio.CreateMultiple_Result> CreateMultipleAsync(wsTRH.pDireccionesEnvio.CreateMultiple request);
        
        [System.ServiceModel.OperationContractAttribute(Action="urn:microsoft-dynamics-schemas/page/direccionesenvio:Update", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        wsTRH.pDireccionesEnvio.Update_Result Update(wsTRH.pDireccionesEnvio.Update request);
        
        // CODEGEN: Generando contrato de mensaje, ya que la operación tiene múltiples valores de devolución.
        [System.ServiceModel.OperationContractAttribute(Action="urn:microsoft-dynamics-schemas/page/direccionesenvio:Update", ReplyAction="*")]
        System.Threading.Tasks.Task<wsTRH.pDireccionesEnvio.Update_Result> UpdateAsync(wsTRH.pDireccionesEnvio.Update request);
        
        [System.ServiceModel.OperationContractAttribute(Action="urn:microsoft-dynamics-schemas/page/direccionesenvio:UpdateMultiple", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        wsTRH.pDireccionesEnvio.UpdateMultiple_Result UpdateMultiple(wsTRH.pDireccionesEnvio.UpdateMultiple request);
        
        // CODEGEN: Generando contrato de mensaje, ya que la operación tiene múltiples valores de devolución.
        [System.ServiceModel.OperationContractAttribute(Action="urn:microsoft-dynamics-schemas/page/direccionesenvio:UpdateMultiple", ReplyAction="*")]
        System.Threading.Tasks.Task<wsTRH.pDireccionesEnvio.UpdateMultiple_Result> UpdateMultipleAsync(wsTRH.pDireccionesEnvio.UpdateMultiple request);
        
        // CODEGEN: Se está generando un contrato de mensaje, ya que el nombre de contenedor (Delete_Result) del mensaje Delete_Result no coincide con el valor predeterminado (Delete)
        [System.ServiceModel.OperationContractAttribute(Action="urn:microsoft-dynamics-schemas/page/direccionesenvio:Delete", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        wsTRH.pDireccionesEnvio.Delete_Result Delete(wsTRH.pDireccionesEnvio.Delete request);
        
        [System.ServiceModel.OperationContractAttribute(Action="urn:microsoft-dynamics-schemas/page/direccionesenvio:Delete", ReplyAction="*")]
        System.Threading.Tasks.Task<wsTRH.pDireccionesEnvio.Delete_Result> DeleteAsync(wsTRH.pDireccionesEnvio.Delete request);
    }
    
    /// <comentarios/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.6.1064.2")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="urn:microsoft-dynamics-schemas/page/direccionesenvio")]
    public partial class DireccionesEnvio : object, System.ComponentModel.INotifyPropertyChanged {
        
        private string keyField;
        
        private string codeField;
        
        private string nameField;
        
        private string addressField;
        
        private string address_2Field;
        
        private string post_CodeField;
        
        private string cityField;
        
        private string countyField;
        
        private string country_Region_CodeField;
        
        private string phone_NoField;
        
        private string contactField;
        
        private string otros_datosField;
        
        private string location_CodeField;
        
        private string shipment_Method_CodeField;
        
        private string shipping_Agent_CodeField;
        
        private string shipping_Agent_Service_CodeField;
        
        private string service_Zone_CodeField;
        
        private System.DateTime last_Date_ModifiedField;
        
        private bool last_Date_ModifiedFieldSpecified;
        
        private string telex_NoField;
        
        private string fax_NoField;
        
        private string e_MailField;
        
        private string home_PageField;
        
        private string customer_NoField;
        
        /// <comentarios/>
        [System.Xml.Serialization.XmlElementAttribute(Order=0)]
        public string Key {
            get {
                return this.keyField;
            }
            set {
                this.keyField = value;
                this.RaisePropertyChanged("Key");
            }
        }
        
        /// <comentarios/>
        [System.Xml.Serialization.XmlElementAttribute(Order=1)]
        public string Code {
            get {
                return this.codeField;
            }
            set {
                this.codeField = value;
                this.RaisePropertyChanged("Code");
            }
        }
        
        /// <comentarios/>
        [System.Xml.Serialization.XmlElementAttribute(Order=2)]
        public string Name {
            get {
                return this.nameField;
            }
            set {
                this.nameField = value;
                this.RaisePropertyChanged("Name");
            }
        }
        
        /// <comentarios/>
        [System.Xml.Serialization.XmlElementAttribute(Order=3)]
        public string Address {
            get {
                return this.addressField;
            }
            set {
                this.addressField = value;
                this.RaisePropertyChanged("Address");
            }
        }
        
        /// <comentarios/>
        [System.Xml.Serialization.XmlElementAttribute(Order=4)]
        public string Address_2 {
            get {
                return this.address_2Field;
            }
            set {
                this.address_2Field = value;
                this.RaisePropertyChanged("Address_2");
            }
        }
        
        /// <comentarios/>
        [System.Xml.Serialization.XmlElementAttribute(Order=5)]
        public string Post_Code {
            get {
                return this.post_CodeField;
            }
            set {
                this.post_CodeField = value;
                this.RaisePropertyChanged("Post_Code");
            }
        }
        
        /// <comentarios/>
        [System.Xml.Serialization.XmlElementAttribute(Order=6)]
        public string City {
            get {
                return this.cityField;
            }
            set {
                this.cityField = value;
                this.RaisePropertyChanged("City");
            }
        }
        
        /// <comentarios/>
        [System.Xml.Serialization.XmlElementAttribute(Order=7)]
        public string County {
            get {
                return this.countyField;
            }
            set {
                this.countyField = value;
                this.RaisePropertyChanged("County");
            }
        }
        
        /// <comentarios/>
        [System.Xml.Serialization.XmlElementAttribute(Order=8)]
        public string Country_Region_Code {
            get {
                return this.country_Region_CodeField;
            }
            set {
                this.country_Region_CodeField = value;
                this.RaisePropertyChanged("Country_Region_Code");
            }
        }
        
        /// <comentarios/>
        [System.Xml.Serialization.XmlElementAttribute(Order=9)]
        public string Phone_No {
            get {
                return this.phone_NoField;
            }
            set {
                this.phone_NoField = value;
                this.RaisePropertyChanged("Phone_No");
            }
        }
        
        /// <comentarios/>
        [System.Xml.Serialization.XmlElementAttribute(Order=10)]
        public string Contact {
            get {
                return this.contactField;
            }
            set {
                this.contactField = value;
                this.RaisePropertyChanged("Contact");
            }
        }
        
        /// <comentarios/>
        [System.Xml.Serialization.XmlElementAttribute(Order=11)]
        public string Otros_datos {
            get {
                return this.otros_datosField;
            }
            set {
                this.otros_datosField = value;
                this.RaisePropertyChanged("Otros_datos");
            }
        }
        
        /// <comentarios/>
        [System.Xml.Serialization.XmlElementAttribute(Order=12)]
        public string Location_Code {
            get {
                return this.location_CodeField;
            }
            set {
                this.location_CodeField = value;
                this.RaisePropertyChanged("Location_Code");
            }
        }
        
        /// <comentarios/>
        [System.Xml.Serialization.XmlElementAttribute(Order=13)]
        public string Shipment_Method_Code {
            get {
                return this.shipment_Method_CodeField;
            }
            set {
                this.shipment_Method_CodeField = value;
                this.RaisePropertyChanged("Shipment_Method_Code");
            }
        }
        
        /// <comentarios/>
        [System.Xml.Serialization.XmlElementAttribute(Order=14)]
        public string Shipping_Agent_Code {
            get {
                return this.shipping_Agent_CodeField;
            }
            set {
                this.shipping_Agent_CodeField = value;
                this.RaisePropertyChanged("Shipping_Agent_Code");
            }
        }
        
        /// <comentarios/>
        [System.Xml.Serialization.XmlElementAttribute(Order=15)]
        public string Shipping_Agent_Service_Code {
            get {
                return this.shipping_Agent_Service_CodeField;
            }
            set {
                this.shipping_Agent_Service_CodeField = value;
                this.RaisePropertyChanged("Shipping_Agent_Service_Code");
            }
        }
        
        /// <comentarios/>
        [System.Xml.Serialization.XmlElementAttribute(Order=16)]
        public string Service_Zone_Code {
            get {
                return this.service_Zone_CodeField;
            }
            set {
                this.service_Zone_CodeField = value;
                this.RaisePropertyChanged("Service_Zone_Code");
            }
        }
        
        /// <comentarios/>
        [System.Xml.Serialization.XmlElementAttribute(DataType="date", Order=17)]
        public System.DateTime Last_Date_Modified {
            get {
                return this.last_Date_ModifiedField;
            }
            set {
                this.last_Date_ModifiedField = value;
                this.RaisePropertyChanged("Last_Date_Modified");
            }
        }
        
        /// <comentarios/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool Last_Date_ModifiedSpecified {
            get {
                return this.last_Date_ModifiedFieldSpecified;
            }
            set {
                this.last_Date_ModifiedFieldSpecified = value;
                this.RaisePropertyChanged("Last_Date_ModifiedSpecified");
            }
        }
        
        /// <comentarios/>
        [System.Xml.Serialization.XmlElementAttribute(Order=18)]
        public string Telex_No {
            get {
                return this.telex_NoField;
            }
            set {
                this.telex_NoField = value;
                this.RaisePropertyChanged("Telex_No");
            }
        }
        
        /// <comentarios/>
        [System.Xml.Serialization.XmlElementAttribute(Order=19)]
        public string Fax_No {
            get {
                return this.fax_NoField;
            }
            set {
                this.fax_NoField = value;
                this.RaisePropertyChanged("Fax_No");
            }
        }
        
        /// <comentarios/>
        [System.Xml.Serialization.XmlElementAttribute(Order=20)]
        public string E_Mail {
            get {
                return this.e_MailField;
            }
            set {
                this.e_MailField = value;
                this.RaisePropertyChanged("E_Mail");
            }
        }
        
        /// <comentarios/>
        [System.Xml.Serialization.XmlElementAttribute(Order=21)]
        public string Home_Page {
            get {
                return this.home_PageField;
            }
            set {
                this.home_PageField = value;
                this.RaisePropertyChanged("Home_Page");
            }
        }
        
        /// <comentarios/>
        [System.Xml.Serialization.XmlElementAttribute(Order=22)]
        public string Customer_No {
            get {
                return this.customer_NoField;
            }
            set {
                this.customer_NoField = value;
                this.RaisePropertyChanged("Customer_No");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    /// <comentarios/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.6.1064.2")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="urn:microsoft-dynamics-schemas/page/direccionesenvio")]
    public partial class DireccionesEnvio_Filter : object, System.ComponentModel.INotifyPropertyChanged {
        
        private DireccionesEnvio_Fields fieldField;
        
        private string criteriaField;
        
        /// <comentarios/>
        [System.Xml.Serialization.XmlElementAttribute(Order=0)]
        public DireccionesEnvio_Fields Field {
            get {
                return this.fieldField;
            }
            set {
                this.fieldField = value;
                this.RaisePropertyChanged("Field");
            }
        }
        
        /// <comentarios/>
        [System.Xml.Serialization.XmlElementAttribute(Order=1)]
        public string Criteria {
            get {
                return this.criteriaField;
            }
            set {
                this.criteriaField = value;
                this.RaisePropertyChanged("Criteria");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    /// <comentarios/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.6.1064.2")]
    [System.SerializableAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="urn:microsoft-dynamics-schemas/page/direccionesenvio")]
    public enum DireccionesEnvio_Fields {
        
        /// <comentarios/>
        Code,
        
        /// <comentarios/>
        Name,
        
        /// <comentarios/>
        Address,
        
        /// <comentarios/>
        Address_2,
        
        /// <comentarios/>
        Post_Code,
        
        /// <comentarios/>
        City,
        
        /// <comentarios/>
        County,
        
        /// <comentarios/>
        Country_Region_Code,
        
        /// <comentarios/>
        Phone_No,
        
        /// <comentarios/>
        Contact,
        
        /// <comentarios/>
        Otros_datos,
        
        /// <comentarios/>
        Location_Code,
        
        /// <comentarios/>
        Shipment_Method_Code,
        
        /// <comentarios/>
        Shipping_Agent_Code,
        
        /// <comentarios/>
        Shipping_Agent_Service_Code,
        
        /// <comentarios/>
        Service_Zone_Code,
        
        /// <comentarios/>
        Last_Date_Modified,
        
        /// <comentarios/>
        Telex_No,
        
        /// <comentarios/>
        Fax_No,
        
        /// <comentarios/>
        E_Mail,
        
        /// <comentarios/>
        Home_Page,
        
        /// <comentarios/>
        Customer_No,
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="Read", WrapperNamespace="urn:microsoft-dynamics-schemas/page/direccionesenvio", IsWrapped=true)]
    public partial class Read {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="urn:microsoft-dynamics-schemas/page/direccionesenvio", Order=0)]
        public string Customer_No;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="urn:microsoft-dynamics-schemas/page/direccionesenvio", Order=1)]
        public string Code;
        
        public Read() {
        }
        
        public Read(string Customer_No, string Code) {
            this.Customer_No = Customer_No;
            this.Code = Code;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="Read_Result", WrapperNamespace="urn:microsoft-dynamics-schemas/page/direccionesenvio", IsWrapped=true)]
    public partial class Read_Result {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="urn:microsoft-dynamics-schemas/page/direccionesenvio", Order=0)]
        public wsTRH.pDireccionesEnvio.DireccionesEnvio DireccionesEnvio;
        
        public Read_Result() {
        }
        
        public Read_Result(wsTRH.pDireccionesEnvio.DireccionesEnvio DireccionesEnvio) {
            this.DireccionesEnvio = DireccionesEnvio;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="ReadByRecId", WrapperNamespace="urn:microsoft-dynamics-schemas/page/direccionesenvio", IsWrapped=true)]
    public partial class ReadByRecId {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="urn:microsoft-dynamics-schemas/page/direccionesenvio", Order=0)]
        public string recId;
        
        public ReadByRecId() {
        }
        
        public ReadByRecId(string recId) {
            this.recId = recId;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="ReadByRecId_Result", WrapperNamespace="urn:microsoft-dynamics-schemas/page/direccionesenvio", IsWrapped=true)]
    public partial class ReadByRecId_Result {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="urn:microsoft-dynamics-schemas/page/direccionesenvio", Order=0)]
        public wsTRH.pDireccionesEnvio.DireccionesEnvio DireccionesEnvio;
        
        public ReadByRecId_Result() {
        }
        
        public ReadByRecId_Result(wsTRH.pDireccionesEnvio.DireccionesEnvio DireccionesEnvio) {
            this.DireccionesEnvio = DireccionesEnvio;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="ReadMultiple", WrapperNamespace="urn:microsoft-dynamics-schemas/page/direccionesenvio", IsWrapped=true)]
    public partial class ReadMultiple {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="urn:microsoft-dynamics-schemas/page/direccionesenvio", Order=0)]
        [System.Xml.Serialization.XmlElementAttribute("filter")]
        public wsTRH.pDireccionesEnvio.DireccionesEnvio_Filter[] filter;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="urn:microsoft-dynamics-schemas/page/direccionesenvio", Order=1)]
        public string bookmarkKey;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="urn:microsoft-dynamics-schemas/page/direccionesenvio", Order=2)]
        public int setSize;
        
        public ReadMultiple() {
        }
        
        public ReadMultiple(wsTRH.pDireccionesEnvio.DireccionesEnvio_Filter[] filter, string bookmarkKey, int setSize) {
            this.filter = filter;
            this.bookmarkKey = bookmarkKey;
            this.setSize = setSize;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="ReadMultiple_Result", WrapperNamespace="urn:microsoft-dynamics-schemas/page/direccionesenvio", IsWrapped=true)]
    public partial class ReadMultiple_Result {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="ReadMultiple_Result", Namespace="urn:microsoft-dynamics-schemas/page/direccionesenvio", Order=0)]
        [System.Xml.Serialization.XmlArrayItemAttribute(IsNullable=false)]
        public wsTRH.pDireccionesEnvio.DireccionesEnvio[] ReadMultiple_Result1;
        
        public ReadMultiple_Result() {
        }
        
        public ReadMultiple_Result(wsTRH.pDireccionesEnvio.DireccionesEnvio[] ReadMultiple_Result1) {
            this.ReadMultiple_Result1 = ReadMultiple_Result1;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="IsUpdated", WrapperNamespace="urn:microsoft-dynamics-schemas/page/direccionesenvio", IsWrapped=true)]
    public partial class IsUpdated {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="urn:microsoft-dynamics-schemas/page/direccionesenvio", Order=0)]
        public string Key;
        
        public IsUpdated() {
        }
        
        public IsUpdated(string Key) {
            this.Key = Key;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="IsUpdated_Result", WrapperNamespace="urn:microsoft-dynamics-schemas/page/direccionesenvio", IsWrapped=true)]
    public partial class IsUpdated_Result {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="IsUpdated_Result", Namespace="urn:microsoft-dynamics-schemas/page/direccionesenvio", Order=0)]
        public bool IsUpdated_Result1;
        
        public IsUpdated_Result() {
        }
        
        public IsUpdated_Result(bool IsUpdated_Result1) {
            this.IsUpdated_Result1 = IsUpdated_Result1;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="GetRecIdFromKey", WrapperNamespace="urn:microsoft-dynamics-schemas/page/direccionesenvio", IsWrapped=true)]
    public partial class GetRecIdFromKey {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="urn:microsoft-dynamics-schemas/page/direccionesenvio", Order=0)]
        public string Key;
        
        public GetRecIdFromKey() {
        }
        
        public GetRecIdFromKey(string Key) {
            this.Key = Key;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="GetRecIdFromKey_Result", WrapperNamespace="urn:microsoft-dynamics-schemas/page/direccionesenvio", IsWrapped=true)]
    public partial class GetRecIdFromKey_Result {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="GetRecIdFromKey_Result", Namespace="urn:microsoft-dynamics-schemas/page/direccionesenvio", Order=0)]
        public string GetRecIdFromKey_Result1;
        
        public GetRecIdFromKey_Result() {
        }
        
        public GetRecIdFromKey_Result(string GetRecIdFromKey_Result1) {
            this.GetRecIdFromKey_Result1 = GetRecIdFromKey_Result1;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.MessageContractAttribute(WrapperName="Create", WrapperNamespace="urn:microsoft-dynamics-schemas/page/direccionesenvio", IsWrapped=true)]
    public partial class Create {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="urn:microsoft-dynamics-schemas/page/direccionesenvio", Order=0)]
        public wsTRH.pDireccionesEnvio.DireccionesEnvio DireccionesEnvio;
        
        public Create() {
        }
        
        public Create(wsTRH.pDireccionesEnvio.DireccionesEnvio DireccionesEnvio) {
            this.DireccionesEnvio = DireccionesEnvio;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.MessageContractAttribute(WrapperName="Create_Result", WrapperNamespace="urn:microsoft-dynamics-schemas/page/direccionesenvio", IsWrapped=true)]
    public partial class Create_Result {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="urn:microsoft-dynamics-schemas/page/direccionesenvio", Order=0)]
        public wsTRH.pDireccionesEnvio.DireccionesEnvio DireccionesEnvio;
        
        public Create_Result() {
        }
        
        public Create_Result(wsTRH.pDireccionesEnvio.DireccionesEnvio DireccionesEnvio) {
            this.DireccionesEnvio = DireccionesEnvio;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.MessageContractAttribute(WrapperName="CreateMultiple", WrapperNamespace="urn:microsoft-dynamics-schemas/page/direccionesenvio", IsWrapped=true)]
    public partial class CreateMultiple {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="urn:microsoft-dynamics-schemas/page/direccionesenvio", Order=0)]
        [System.Xml.Serialization.XmlArrayItemAttribute(IsNullable=false)]
        public wsTRH.pDireccionesEnvio.DireccionesEnvio[] DireccionesEnvio_List;
        
        public CreateMultiple() {
        }
        
        public CreateMultiple(wsTRH.pDireccionesEnvio.DireccionesEnvio[] DireccionesEnvio_List) {
            this.DireccionesEnvio_List = DireccionesEnvio_List;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.MessageContractAttribute(WrapperName="CreateMultiple_Result", WrapperNamespace="urn:microsoft-dynamics-schemas/page/direccionesenvio", IsWrapped=true)]
    public partial class CreateMultiple_Result {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="urn:microsoft-dynamics-schemas/page/direccionesenvio", Order=0)]
        [System.Xml.Serialization.XmlArrayItemAttribute(IsNullable=false)]
        public wsTRH.pDireccionesEnvio.DireccionesEnvio[] DireccionesEnvio_List;
        
        public CreateMultiple_Result() {
        }
        
        public CreateMultiple_Result(wsTRH.pDireccionesEnvio.DireccionesEnvio[] DireccionesEnvio_List) {
            this.DireccionesEnvio_List = DireccionesEnvio_List;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.MessageContractAttribute(WrapperName="Update", WrapperNamespace="urn:microsoft-dynamics-schemas/page/direccionesenvio", IsWrapped=true)]
    public partial class Update {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="urn:microsoft-dynamics-schemas/page/direccionesenvio", Order=0)]
        public wsTRH.pDireccionesEnvio.DireccionesEnvio DireccionesEnvio;
        
        public Update() {
        }
        
        public Update(wsTRH.pDireccionesEnvio.DireccionesEnvio DireccionesEnvio) {
            this.DireccionesEnvio = DireccionesEnvio;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.MessageContractAttribute(WrapperName="Update_Result", WrapperNamespace="urn:microsoft-dynamics-schemas/page/direccionesenvio", IsWrapped=true)]
    public partial class Update_Result {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="urn:microsoft-dynamics-schemas/page/direccionesenvio", Order=0)]
        public wsTRH.pDireccionesEnvio.DireccionesEnvio DireccionesEnvio;
        
        public Update_Result() {
        }
        
        public Update_Result(wsTRH.pDireccionesEnvio.DireccionesEnvio DireccionesEnvio) {
            this.DireccionesEnvio = DireccionesEnvio;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.MessageContractAttribute(WrapperName="UpdateMultiple", WrapperNamespace="urn:microsoft-dynamics-schemas/page/direccionesenvio", IsWrapped=true)]
    public partial class UpdateMultiple {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="urn:microsoft-dynamics-schemas/page/direccionesenvio", Order=0)]
        [System.Xml.Serialization.XmlArrayItemAttribute(IsNullable=false)]
        public wsTRH.pDireccionesEnvio.DireccionesEnvio[] DireccionesEnvio_List;
        
        public UpdateMultiple() {
        }
        
        public UpdateMultiple(wsTRH.pDireccionesEnvio.DireccionesEnvio[] DireccionesEnvio_List) {
            this.DireccionesEnvio_List = DireccionesEnvio_List;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.MessageContractAttribute(WrapperName="UpdateMultiple_Result", WrapperNamespace="urn:microsoft-dynamics-schemas/page/direccionesenvio", IsWrapped=true)]
    public partial class UpdateMultiple_Result {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="urn:microsoft-dynamics-schemas/page/direccionesenvio", Order=0)]
        [System.Xml.Serialization.XmlArrayItemAttribute(IsNullable=false)]
        public wsTRH.pDireccionesEnvio.DireccionesEnvio[] DireccionesEnvio_List;
        
        public UpdateMultiple_Result() {
        }
        
        public UpdateMultiple_Result(wsTRH.pDireccionesEnvio.DireccionesEnvio[] DireccionesEnvio_List) {
            this.DireccionesEnvio_List = DireccionesEnvio_List;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="Delete", WrapperNamespace="urn:microsoft-dynamics-schemas/page/direccionesenvio", IsWrapped=true)]
    public partial class Delete {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="urn:microsoft-dynamics-schemas/page/direccionesenvio", Order=0)]
        public string Key;
        
        public Delete() {
        }
        
        public Delete(string Key) {
            this.Key = Key;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="Delete_Result", WrapperNamespace="urn:microsoft-dynamics-schemas/page/direccionesenvio", IsWrapped=true)]
    public partial class Delete_Result {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="Delete_Result", Namespace="urn:microsoft-dynamics-schemas/page/direccionesenvio", Order=0)]
        public bool Delete_Result1;
        
        public Delete_Result() {
        }
        
        public Delete_Result(bool Delete_Result1) {
            this.Delete_Result1 = Delete_Result1;
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface DireccionesEnvio_PortChannel : wsTRH.pDireccionesEnvio.DireccionesEnvio_Port, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class DireccionesEnvio_PortClient : System.ServiceModel.ClientBase<wsTRH.pDireccionesEnvio.DireccionesEnvio_Port>, wsTRH.pDireccionesEnvio.DireccionesEnvio_Port {
        
        public DireccionesEnvio_PortClient() {
        }
        
        public DireccionesEnvio_PortClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public DireccionesEnvio_PortClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public DireccionesEnvio_PortClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public DireccionesEnvio_PortClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        wsTRH.pDireccionesEnvio.Read_Result wsTRH.pDireccionesEnvio.DireccionesEnvio_Port.Read(wsTRH.pDireccionesEnvio.Read request) {
            return base.Channel.Read(request);
        }
        
        public wsTRH.pDireccionesEnvio.DireccionesEnvio Read(string Customer_No, string Code) {
            wsTRH.pDireccionesEnvio.Read inValue = new wsTRH.pDireccionesEnvio.Read();
            inValue.Customer_No = Customer_No;
            inValue.Code = Code;
            wsTRH.pDireccionesEnvio.Read_Result retVal = ((wsTRH.pDireccionesEnvio.DireccionesEnvio_Port)(this)).Read(inValue);
            return retVal.DireccionesEnvio;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<wsTRH.pDireccionesEnvio.Read_Result> wsTRH.pDireccionesEnvio.DireccionesEnvio_Port.ReadAsync(wsTRH.pDireccionesEnvio.Read request) {
            return base.Channel.ReadAsync(request);
        }
        
        public System.Threading.Tasks.Task<wsTRH.pDireccionesEnvio.Read_Result> ReadAsync(string Customer_No, string Code) {
            wsTRH.pDireccionesEnvio.Read inValue = new wsTRH.pDireccionesEnvio.Read();
            inValue.Customer_No = Customer_No;
            inValue.Code = Code;
            return ((wsTRH.pDireccionesEnvio.DireccionesEnvio_Port)(this)).ReadAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        wsTRH.pDireccionesEnvio.ReadByRecId_Result wsTRH.pDireccionesEnvio.DireccionesEnvio_Port.ReadByRecId(wsTRH.pDireccionesEnvio.ReadByRecId request) {
            return base.Channel.ReadByRecId(request);
        }
        
        public wsTRH.pDireccionesEnvio.DireccionesEnvio ReadByRecId(string recId) {
            wsTRH.pDireccionesEnvio.ReadByRecId inValue = new wsTRH.pDireccionesEnvio.ReadByRecId();
            inValue.recId = recId;
            wsTRH.pDireccionesEnvio.ReadByRecId_Result retVal = ((wsTRH.pDireccionesEnvio.DireccionesEnvio_Port)(this)).ReadByRecId(inValue);
            return retVal.DireccionesEnvio;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<wsTRH.pDireccionesEnvio.ReadByRecId_Result> wsTRH.pDireccionesEnvio.DireccionesEnvio_Port.ReadByRecIdAsync(wsTRH.pDireccionesEnvio.ReadByRecId request) {
            return base.Channel.ReadByRecIdAsync(request);
        }
        
        public System.Threading.Tasks.Task<wsTRH.pDireccionesEnvio.ReadByRecId_Result> ReadByRecIdAsync(string recId) {
            wsTRH.pDireccionesEnvio.ReadByRecId inValue = new wsTRH.pDireccionesEnvio.ReadByRecId();
            inValue.recId = recId;
            return ((wsTRH.pDireccionesEnvio.DireccionesEnvio_Port)(this)).ReadByRecIdAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        wsTRH.pDireccionesEnvio.ReadMultiple_Result wsTRH.pDireccionesEnvio.DireccionesEnvio_Port.ReadMultiple(wsTRH.pDireccionesEnvio.ReadMultiple request) {
            return base.Channel.ReadMultiple(request);
        }
        
        public wsTRH.pDireccionesEnvio.DireccionesEnvio[] ReadMultiple(wsTRH.pDireccionesEnvio.DireccionesEnvio_Filter[] filter, string bookmarkKey, int setSize) {
            wsTRH.pDireccionesEnvio.ReadMultiple inValue = new wsTRH.pDireccionesEnvio.ReadMultiple();
            inValue.filter = filter;
            inValue.bookmarkKey = bookmarkKey;
            inValue.setSize = setSize;
            wsTRH.pDireccionesEnvio.ReadMultiple_Result retVal = ((wsTRH.pDireccionesEnvio.DireccionesEnvio_Port)(this)).ReadMultiple(inValue);
            return retVal.ReadMultiple_Result1;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<wsTRH.pDireccionesEnvio.ReadMultiple_Result> wsTRH.pDireccionesEnvio.DireccionesEnvio_Port.ReadMultipleAsync(wsTRH.pDireccionesEnvio.ReadMultiple request) {
            return base.Channel.ReadMultipleAsync(request);
        }
        
        public System.Threading.Tasks.Task<wsTRH.pDireccionesEnvio.ReadMultiple_Result> ReadMultipleAsync(wsTRH.pDireccionesEnvio.DireccionesEnvio_Filter[] filter, string bookmarkKey, int setSize) {
            wsTRH.pDireccionesEnvio.ReadMultiple inValue = new wsTRH.pDireccionesEnvio.ReadMultiple();
            inValue.filter = filter;
            inValue.bookmarkKey = bookmarkKey;
            inValue.setSize = setSize;
            return ((wsTRH.pDireccionesEnvio.DireccionesEnvio_Port)(this)).ReadMultipleAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        wsTRH.pDireccionesEnvio.IsUpdated_Result wsTRH.pDireccionesEnvio.DireccionesEnvio_Port.IsUpdated(wsTRH.pDireccionesEnvio.IsUpdated request) {
            return base.Channel.IsUpdated(request);
        }
        
        public bool IsUpdated(string Key) {
            wsTRH.pDireccionesEnvio.IsUpdated inValue = new wsTRH.pDireccionesEnvio.IsUpdated();
            inValue.Key = Key;
            wsTRH.pDireccionesEnvio.IsUpdated_Result retVal = ((wsTRH.pDireccionesEnvio.DireccionesEnvio_Port)(this)).IsUpdated(inValue);
            return retVal.IsUpdated_Result1;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<wsTRH.pDireccionesEnvio.IsUpdated_Result> wsTRH.pDireccionesEnvio.DireccionesEnvio_Port.IsUpdatedAsync(wsTRH.pDireccionesEnvio.IsUpdated request) {
            return base.Channel.IsUpdatedAsync(request);
        }
        
        public System.Threading.Tasks.Task<wsTRH.pDireccionesEnvio.IsUpdated_Result> IsUpdatedAsync(string Key) {
            wsTRH.pDireccionesEnvio.IsUpdated inValue = new wsTRH.pDireccionesEnvio.IsUpdated();
            inValue.Key = Key;
            return ((wsTRH.pDireccionesEnvio.DireccionesEnvio_Port)(this)).IsUpdatedAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        wsTRH.pDireccionesEnvio.GetRecIdFromKey_Result wsTRH.pDireccionesEnvio.DireccionesEnvio_Port.GetRecIdFromKey(wsTRH.pDireccionesEnvio.GetRecIdFromKey request) {
            return base.Channel.GetRecIdFromKey(request);
        }
        
        public string GetRecIdFromKey(string Key) {
            wsTRH.pDireccionesEnvio.GetRecIdFromKey inValue = new wsTRH.pDireccionesEnvio.GetRecIdFromKey();
            inValue.Key = Key;
            wsTRH.pDireccionesEnvio.GetRecIdFromKey_Result retVal = ((wsTRH.pDireccionesEnvio.DireccionesEnvio_Port)(this)).GetRecIdFromKey(inValue);
            return retVal.GetRecIdFromKey_Result1;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<wsTRH.pDireccionesEnvio.GetRecIdFromKey_Result> wsTRH.pDireccionesEnvio.DireccionesEnvio_Port.GetRecIdFromKeyAsync(wsTRH.pDireccionesEnvio.GetRecIdFromKey request) {
            return base.Channel.GetRecIdFromKeyAsync(request);
        }
        
        public System.Threading.Tasks.Task<wsTRH.pDireccionesEnvio.GetRecIdFromKey_Result> GetRecIdFromKeyAsync(string Key) {
            wsTRH.pDireccionesEnvio.GetRecIdFromKey inValue = new wsTRH.pDireccionesEnvio.GetRecIdFromKey();
            inValue.Key = Key;
            return ((wsTRH.pDireccionesEnvio.DireccionesEnvio_Port)(this)).GetRecIdFromKeyAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        wsTRH.pDireccionesEnvio.Create_Result wsTRH.pDireccionesEnvio.DireccionesEnvio_Port.Create(wsTRH.pDireccionesEnvio.Create request) {
            return base.Channel.Create(request);
        }
        
        public void Create(ref wsTRH.pDireccionesEnvio.DireccionesEnvio DireccionesEnvio) {
            wsTRH.pDireccionesEnvio.Create inValue = new wsTRH.pDireccionesEnvio.Create();
            inValue.DireccionesEnvio = DireccionesEnvio;
            wsTRH.pDireccionesEnvio.Create_Result retVal = ((wsTRH.pDireccionesEnvio.DireccionesEnvio_Port)(this)).Create(inValue);
            DireccionesEnvio = retVal.DireccionesEnvio;
        }
        
        public System.Threading.Tasks.Task<wsTRH.pDireccionesEnvio.Create_Result> CreateAsync(wsTRH.pDireccionesEnvio.Create request) {
            return base.Channel.CreateAsync(request);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        wsTRH.pDireccionesEnvio.CreateMultiple_Result wsTRH.pDireccionesEnvio.DireccionesEnvio_Port.CreateMultiple(wsTRH.pDireccionesEnvio.CreateMultiple request) {
            return base.Channel.CreateMultiple(request);
        }
        
        public void CreateMultiple(ref wsTRH.pDireccionesEnvio.DireccionesEnvio[] DireccionesEnvio_List) {
            wsTRH.pDireccionesEnvio.CreateMultiple inValue = new wsTRH.pDireccionesEnvio.CreateMultiple();
            inValue.DireccionesEnvio_List = DireccionesEnvio_List;
            wsTRH.pDireccionesEnvio.CreateMultiple_Result retVal = ((wsTRH.pDireccionesEnvio.DireccionesEnvio_Port)(this)).CreateMultiple(inValue);
            DireccionesEnvio_List = retVal.DireccionesEnvio_List;
        }
        
        public System.Threading.Tasks.Task<wsTRH.pDireccionesEnvio.CreateMultiple_Result> CreateMultipleAsync(wsTRH.pDireccionesEnvio.CreateMultiple request) {
            return base.Channel.CreateMultipleAsync(request);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        wsTRH.pDireccionesEnvio.Update_Result wsTRH.pDireccionesEnvio.DireccionesEnvio_Port.Update(wsTRH.pDireccionesEnvio.Update request) {
            return base.Channel.Update(request);
        }
        
        public void Update(ref wsTRH.pDireccionesEnvio.DireccionesEnvio DireccionesEnvio) {
            wsTRH.pDireccionesEnvio.Update inValue = new wsTRH.pDireccionesEnvio.Update();
            inValue.DireccionesEnvio = DireccionesEnvio;
            wsTRH.pDireccionesEnvio.Update_Result retVal = ((wsTRH.pDireccionesEnvio.DireccionesEnvio_Port)(this)).Update(inValue);
            DireccionesEnvio = retVal.DireccionesEnvio;
        }
        
        public System.Threading.Tasks.Task<wsTRH.pDireccionesEnvio.Update_Result> UpdateAsync(wsTRH.pDireccionesEnvio.Update request) {
            return base.Channel.UpdateAsync(request);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        wsTRH.pDireccionesEnvio.UpdateMultiple_Result wsTRH.pDireccionesEnvio.DireccionesEnvio_Port.UpdateMultiple(wsTRH.pDireccionesEnvio.UpdateMultiple request) {
            return base.Channel.UpdateMultiple(request);
        }
        
        public void UpdateMultiple(ref wsTRH.pDireccionesEnvio.DireccionesEnvio[] DireccionesEnvio_List) {
            wsTRH.pDireccionesEnvio.UpdateMultiple inValue = new wsTRH.pDireccionesEnvio.UpdateMultiple();
            inValue.DireccionesEnvio_List = DireccionesEnvio_List;
            wsTRH.pDireccionesEnvio.UpdateMultiple_Result retVal = ((wsTRH.pDireccionesEnvio.DireccionesEnvio_Port)(this)).UpdateMultiple(inValue);
            DireccionesEnvio_List = retVal.DireccionesEnvio_List;
        }
        
        public System.Threading.Tasks.Task<wsTRH.pDireccionesEnvio.UpdateMultiple_Result> UpdateMultipleAsync(wsTRH.pDireccionesEnvio.UpdateMultiple request) {
            return base.Channel.UpdateMultipleAsync(request);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        wsTRH.pDireccionesEnvio.Delete_Result wsTRH.pDireccionesEnvio.DireccionesEnvio_Port.Delete(wsTRH.pDireccionesEnvio.Delete request) {
            return base.Channel.Delete(request);
        }
        
        public bool Delete(string Key) {
            wsTRH.pDireccionesEnvio.Delete inValue = new wsTRH.pDireccionesEnvio.Delete();
            inValue.Key = Key;
            wsTRH.pDireccionesEnvio.Delete_Result retVal = ((wsTRH.pDireccionesEnvio.DireccionesEnvio_Port)(this)).Delete(inValue);
            return retVal.Delete_Result1;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<wsTRH.pDireccionesEnvio.Delete_Result> wsTRH.pDireccionesEnvio.DireccionesEnvio_Port.DeleteAsync(wsTRH.pDireccionesEnvio.Delete request) {
            return base.Channel.DeleteAsync(request);
        }
        
        public System.Threading.Tasks.Task<wsTRH.pDireccionesEnvio.Delete_Result> DeleteAsync(string Key) {
            wsTRH.pDireccionesEnvio.Delete inValue = new wsTRH.pDireccionesEnvio.Delete();
            inValue.Key = Key;
            return ((wsTRH.pDireccionesEnvio.DireccionesEnvio_Port)(this)).DeleteAsync(inValue);
        }
    }
}
