//------------------------------------------------------------------------------
// <auto-generated>
//     Este código fue generado por una herramienta.
//     Versión de runtime:4.0.30319.42000
//
//     Los cambios en este archivo podrían causar un comportamiento incorrecto y se perderán si
//     se vuelve a generar el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace RepositoryWebServiceTRH.AlmacenRepuestosContext {
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(Namespace="urn:microsoft-dynamics-schemas/codeunit/AlmacenRepuestos", ConfigurationName="AlmacenRepuestosContext.AlmacenRepuestos_Port")]
    public interface AlmacenRepuestos_Port {
        
        // CODEGEN: Se está generando un contrato de mensaje, ya que el nombre de contenedor (RegistrarEntrega_Result) del mensaje RegistrarEntrega_Result no coincide con el valor predeterminado (RegistrarEntrega)
        [System.ServiceModel.OperationContractAttribute(Action="urn:microsoft-dynamics-schemas/codeunit/AlmacenRepuestos:RegistrarEntrega", ReplyAction="*")]
        RepositoryWebServiceTRH.AlmacenRepuestosContext.RegistrarEntrega_Result RegistrarEntrega(RepositoryWebServiceTRH.AlmacenRepuestosContext.RegistrarEntrega request);
        
        [System.ServiceModel.OperationContractAttribute(Action="urn:microsoft-dynamics-schemas/codeunit/AlmacenRepuestos:RegistrarEntrega", ReplyAction="*")]
        System.Threading.Tasks.Task<RepositoryWebServiceTRH.AlmacenRepuestosContext.RegistrarEntrega_Result> RegistrarEntregaAsync(RepositoryWebServiceTRH.AlmacenRepuestosContext.RegistrarEntrega request);
        
        // CODEGEN: Se está generando un contrato de mensaje, ya que el nombre de contenedor (GetAlbaran_Result) del mensaje GetAlbaran_Result no coincide con el valor predeterminado (GetAlbaran)
        [System.ServiceModel.OperationContractAttribute(Action="urn:microsoft-dynamics-schemas/codeunit/AlmacenRepuestos:GetAlbaran", ReplyAction="*")]
        RepositoryWebServiceTRH.AlmacenRepuestosContext.GetAlbaran_Result GetAlbaran(RepositoryWebServiceTRH.AlmacenRepuestosContext.GetAlbaran request);
        
        [System.ServiceModel.OperationContractAttribute(Action="urn:microsoft-dynamics-schemas/codeunit/AlmacenRepuestos:GetAlbaran", ReplyAction="*")]
        System.Threading.Tasks.Task<RepositoryWebServiceTRH.AlmacenRepuestosContext.GetAlbaran_Result> GetAlbaranAsync(RepositoryWebServiceTRH.AlmacenRepuestosContext.GetAlbaran request);
        
        // CODEGEN: Se está generando un contrato de mensaje, ya que el nombre de contenedor (InsertRepuesto_Result) del mensaje InsertRepuesto_Result no coincide con el valor predeterminado (InsertRepuesto)
        [System.ServiceModel.OperationContractAttribute(Action="urn:microsoft-dynamics-schemas/codeunit/AlmacenRepuestos:InsertRepuesto", ReplyAction="*")]
        RepositoryWebServiceTRH.AlmacenRepuestosContext.InsertRepuesto_Result InsertRepuesto(RepositoryWebServiceTRH.AlmacenRepuestosContext.InsertRepuesto request);
        
        [System.ServiceModel.OperationContractAttribute(Action="urn:microsoft-dynamics-schemas/codeunit/AlmacenRepuestos:InsertRepuesto", ReplyAction="*")]
        System.Threading.Tasks.Task<RepositoryWebServiceTRH.AlmacenRepuestosContext.InsertRepuesto_Result> InsertRepuestoAsync(RepositoryWebServiceTRH.AlmacenRepuestosContext.InsertRepuesto request);
        
        // CODEGEN: Se está generando un contrato de mensaje, ya que el nombre de contenedor (UpdateRepuesto_Result) del mensaje UpdateRepuesto_Result no coincide con el valor predeterminado (UpdateRepuesto)
        [System.ServiceModel.OperationContractAttribute(Action="urn:microsoft-dynamics-schemas/codeunit/AlmacenRepuestos:UpdateRepuesto", ReplyAction="*")]
        RepositoryWebServiceTRH.AlmacenRepuestosContext.UpdateRepuesto_Result UpdateRepuesto(RepositoryWebServiceTRH.AlmacenRepuestosContext.UpdateRepuesto request);
        
        [System.ServiceModel.OperationContractAttribute(Action="urn:microsoft-dynamics-schemas/codeunit/AlmacenRepuestos:UpdateRepuesto", ReplyAction="*")]
        System.Threading.Tasks.Task<RepositoryWebServiceTRH.AlmacenRepuestosContext.UpdateRepuesto_Result> UpdateRepuestoAsync(RepositoryWebServiceTRH.AlmacenRepuestosContext.UpdateRepuesto request);
        
        // CODEGEN: Se está generando un contrato de mensaje, ya que el nombre de contenedor (DeleteRepuesto_Result) del mensaje DeleteRepuesto_Result no coincide con el valor predeterminado (DeleteRepuesto)
        [System.ServiceModel.OperationContractAttribute(Action="urn:microsoft-dynamics-schemas/codeunit/AlmacenRepuestos:DeleteRepuesto", ReplyAction="*")]
        RepositoryWebServiceTRH.AlmacenRepuestosContext.DeleteRepuesto_Result DeleteRepuesto(RepositoryWebServiceTRH.AlmacenRepuestosContext.DeleteRepuesto request);
        
        [System.ServiceModel.OperationContractAttribute(Action="urn:microsoft-dynamics-schemas/codeunit/AlmacenRepuestos:DeleteRepuesto", ReplyAction="*")]
        System.Threading.Tasks.Task<RepositoryWebServiceTRH.AlmacenRepuestosContext.DeleteRepuesto_Result> DeleteRepuestoAsync(RepositoryWebServiceTRH.AlmacenRepuestosContext.DeleteRepuesto request);
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="RegistrarEntrega", WrapperNamespace="urn:microsoft-dynamics-schemas/codeunit/AlmacenRepuestos", IsWrapped=true)]
    public partial class RegistrarEntrega {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="urn:microsoft-dynamics-schemas/codeunit/AlmacenRepuestos", Order=0)]
        public string codEmpleado;
        
        public RegistrarEntrega() {
        }
        
        public RegistrarEntrega(string codEmpleado) {
            this.codEmpleado = codEmpleado;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="RegistrarEntrega_Result", WrapperNamespace="urn:microsoft-dynamics-schemas/codeunit/AlmacenRepuestos", IsWrapped=true)]
    public partial class RegistrarEntrega_Result {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="urn:microsoft-dynamics-schemas/codeunit/AlmacenRepuestos", Order=0)]
        public string return_value;
        
        public RegistrarEntrega_Result() {
        }
        
        public RegistrarEntrega_Result(string return_value) {
            this.return_value = return_value;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="GetAlbaran", WrapperNamespace="urn:microsoft-dynamics-schemas/codeunit/AlmacenRepuestos", IsWrapped=true)]
    public partial class GetAlbaran {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="urn:microsoft-dynamics-schemas/codeunit/AlmacenRepuestos", Order=0)]
        public string codDocumento;
        
        public GetAlbaran() {
        }
        
        public GetAlbaran(string codDocumento) {
            this.codDocumento = codDocumento;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="GetAlbaran_Result", WrapperNamespace="urn:microsoft-dynamics-schemas/codeunit/AlmacenRepuestos", IsWrapped=true)]
    public partial class GetAlbaran_Result {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="urn:microsoft-dynamics-schemas/codeunit/AlmacenRepuestos", Order=0)]
        public string return_value;
        
        public GetAlbaran_Result() {
        }
        
        public GetAlbaran_Result(string return_value) {
            this.return_value = return_value;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="InsertRepuesto", WrapperNamespace="urn:microsoft-dynamics-schemas/codeunit/AlmacenRepuestos", IsWrapped=true)]
    public partial class InsertRepuesto {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="urn:microsoft-dynamics-schemas/codeunit/AlmacenRepuestos", Order=0)]
        public string codEmpleado;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="urn:microsoft-dynamics-schemas/codeunit/AlmacenRepuestos", Order=1)]
        public string codRepuesto;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="urn:microsoft-dynamics-schemas/codeunit/AlmacenRepuestos", Order=2)]
        public decimal cantidad;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="urn:microsoft-dynamics-schemas/codeunit/AlmacenRepuestos", Order=3)]
        public int maquina;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="urn:microsoft-dynamics-schemas/codeunit/AlmacenRepuestos", Order=4)]
        public int destino;
        
        public InsertRepuesto() {
        }
        
        public InsertRepuesto(string codEmpleado, string codRepuesto, decimal cantidad, int maquina, int destino) {
            this.codEmpleado = codEmpleado;
            this.codRepuesto = codRepuesto;
            this.cantidad = cantidad;
            this.maquina = maquina;
            this.destino = destino;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="InsertRepuesto_Result", WrapperNamespace="urn:microsoft-dynamics-schemas/codeunit/AlmacenRepuestos", IsWrapped=true)]
    public partial class InsertRepuesto_Result {
        
        public InsertRepuesto_Result() {
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="UpdateRepuesto", WrapperNamespace="urn:microsoft-dynamics-schemas/codeunit/AlmacenRepuestos", IsWrapped=true)]
    public partial class UpdateRepuesto {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="urn:microsoft-dynamics-schemas/codeunit/AlmacenRepuestos", Order=0)]
        public string codEmpleado;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="urn:microsoft-dynamics-schemas/codeunit/AlmacenRepuestos", Order=1)]
        public string codRepuesto;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="urn:microsoft-dynamics-schemas/codeunit/AlmacenRepuestos", Order=2)]
        public decimal cantidad;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="urn:microsoft-dynamics-schemas/codeunit/AlmacenRepuestos", Order=3)]
        public int maquina;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="urn:microsoft-dynamics-schemas/codeunit/AlmacenRepuestos", Order=4)]
        public int destino;
        
        public UpdateRepuesto() {
        }
        
        public UpdateRepuesto(string codEmpleado, string codRepuesto, decimal cantidad, int maquina, int destino) {
            this.codEmpleado = codEmpleado;
            this.codRepuesto = codRepuesto;
            this.cantidad = cantidad;
            this.maquina = maquina;
            this.destino = destino;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="UpdateRepuesto_Result", WrapperNamespace="urn:microsoft-dynamics-schemas/codeunit/AlmacenRepuestos", IsWrapped=true)]
    public partial class UpdateRepuesto_Result {
        
        public UpdateRepuesto_Result() {
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="DeleteRepuesto", WrapperNamespace="urn:microsoft-dynamics-schemas/codeunit/AlmacenRepuestos", IsWrapped=true)]
    public partial class DeleteRepuesto {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="urn:microsoft-dynamics-schemas/codeunit/AlmacenRepuestos", Order=0)]
        public string codProducto;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="urn:microsoft-dynamics-schemas/codeunit/AlmacenRepuestos", Order=1)]
        public string codEmpleado;
        
        public DeleteRepuesto() {
        }
        
        public DeleteRepuesto(string codProducto, string codEmpleado) {
            this.codProducto = codProducto;
            this.codEmpleado = codEmpleado;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="DeleteRepuesto_Result", WrapperNamespace="urn:microsoft-dynamics-schemas/codeunit/AlmacenRepuestos", IsWrapped=true)]
    public partial class DeleteRepuesto_Result {
        
        public DeleteRepuesto_Result() {
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface AlmacenRepuestos_PortChannel : RepositoryWebServiceTRH.AlmacenRepuestosContext.AlmacenRepuestos_Port, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class AlmacenRepuestos_PortClient : System.ServiceModel.ClientBase<RepositoryWebServiceTRH.AlmacenRepuestosContext.AlmacenRepuestos_Port>, RepositoryWebServiceTRH.AlmacenRepuestosContext.AlmacenRepuestos_Port {
        
        public AlmacenRepuestos_PortClient() {
        }
        
        public AlmacenRepuestos_PortClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public AlmacenRepuestos_PortClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public AlmacenRepuestos_PortClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public AlmacenRepuestos_PortClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        RepositoryWebServiceTRH.AlmacenRepuestosContext.RegistrarEntrega_Result RepositoryWebServiceTRH.AlmacenRepuestosContext.AlmacenRepuestos_Port.RegistrarEntrega(RepositoryWebServiceTRH.AlmacenRepuestosContext.RegistrarEntrega request) {
            return base.Channel.RegistrarEntrega(request);
        }
        
        public string RegistrarEntrega(string codEmpleado) {
            RepositoryWebServiceTRH.AlmacenRepuestosContext.RegistrarEntrega inValue = new RepositoryWebServiceTRH.AlmacenRepuestosContext.RegistrarEntrega();
            inValue.codEmpleado = codEmpleado;
            RepositoryWebServiceTRH.AlmacenRepuestosContext.RegistrarEntrega_Result retVal = ((RepositoryWebServiceTRH.AlmacenRepuestosContext.AlmacenRepuestos_Port)(this)).RegistrarEntrega(inValue);
            return retVal.return_value;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<RepositoryWebServiceTRH.AlmacenRepuestosContext.RegistrarEntrega_Result> RepositoryWebServiceTRH.AlmacenRepuestosContext.AlmacenRepuestos_Port.RegistrarEntregaAsync(RepositoryWebServiceTRH.AlmacenRepuestosContext.RegistrarEntrega request) {
            return base.Channel.RegistrarEntregaAsync(request);
        }
        
        public System.Threading.Tasks.Task<RepositoryWebServiceTRH.AlmacenRepuestosContext.RegistrarEntrega_Result> RegistrarEntregaAsync(string codEmpleado) {
            RepositoryWebServiceTRH.AlmacenRepuestosContext.RegistrarEntrega inValue = new RepositoryWebServiceTRH.AlmacenRepuestosContext.RegistrarEntrega();
            inValue.codEmpleado = codEmpleado;
            return ((RepositoryWebServiceTRH.AlmacenRepuestosContext.AlmacenRepuestos_Port)(this)).RegistrarEntregaAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        RepositoryWebServiceTRH.AlmacenRepuestosContext.GetAlbaran_Result RepositoryWebServiceTRH.AlmacenRepuestosContext.AlmacenRepuestos_Port.GetAlbaran(RepositoryWebServiceTRH.AlmacenRepuestosContext.GetAlbaran request) {
            return base.Channel.GetAlbaran(request);
        }
        
        public string GetAlbaran(string codDocumento) {
            RepositoryWebServiceTRH.AlmacenRepuestosContext.GetAlbaran inValue = new RepositoryWebServiceTRH.AlmacenRepuestosContext.GetAlbaran();
            inValue.codDocumento = codDocumento;
            RepositoryWebServiceTRH.AlmacenRepuestosContext.GetAlbaran_Result retVal = ((RepositoryWebServiceTRH.AlmacenRepuestosContext.AlmacenRepuestos_Port)(this)).GetAlbaran(inValue);
            return retVal.return_value;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<RepositoryWebServiceTRH.AlmacenRepuestosContext.GetAlbaran_Result> RepositoryWebServiceTRH.AlmacenRepuestosContext.AlmacenRepuestos_Port.GetAlbaranAsync(RepositoryWebServiceTRH.AlmacenRepuestosContext.GetAlbaran request) {
            return base.Channel.GetAlbaranAsync(request);
        }
        
        public System.Threading.Tasks.Task<RepositoryWebServiceTRH.AlmacenRepuestosContext.GetAlbaran_Result> GetAlbaranAsync(string codDocumento) {
            RepositoryWebServiceTRH.AlmacenRepuestosContext.GetAlbaran inValue = new RepositoryWebServiceTRH.AlmacenRepuestosContext.GetAlbaran();
            inValue.codDocumento = codDocumento;
            return ((RepositoryWebServiceTRH.AlmacenRepuestosContext.AlmacenRepuestos_Port)(this)).GetAlbaranAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        RepositoryWebServiceTRH.AlmacenRepuestosContext.InsertRepuesto_Result RepositoryWebServiceTRH.AlmacenRepuestosContext.AlmacenRepuestos_Port.InsertRepuesto(RepositoryWebServiceTRH.AlmacenRepuestosContext.InsertRepuesto request) {
            return base.Channel.InsertRepuesto(request);
        }
        
        public void InsertRepuesto(string codEmpleado, string codRepuesto, decimal cantidad, int maquina, int destino) {
            RepositoryWebServiceTRH.AlmacenRepuestosContext.InsertRepuesto inValue = new RepositoryWebServiceTRH.AlmacenRepuestosContext.InsertRepuesto();
            inValue.codEmpleado = codEmpleado;
            inValue.codRepuesto = codRepuesto;
            inValue.cantidad = cantidad;
            inValue.maquina = maquina;
            inValue.destino = destino;
            RepositoryWebServiceTRH.AlmacenRepuestosContext.InsertRepuesto_Result retVal = ((RepositoryWebServiceTRH.AlmacenRepuestosContext.AlmacenRepuestos_Port)(this)).InsertRepuesto(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<RepositoryWebServiceTRH.AlmacenRepuestosContext.InsertRepuesto_Result> RepositoryWebServiceTRH.AlmacenRepuestosContext.AlmacenRepuestos_Port.InsertRepuestoAsync(RepositoryWebServiceTRH.AlmacenRepuestosContext.InsertRepuesto request) {
            return base.Channel.InsertRepuestoAsync(request);
        }
        
        public System.Threading.Tasks.Task<RepositoryWebServiceTRH.AlmacenRepuestosContext.InsertRepuesto_Result> InsertRepuestoAsync(string codEmpleado, string codRepuesto, decimal cantidad, int maquina, int destino) {
            RepositoryWebServiceTRH.AlmacenRepuestosContext.InsertRepuesto inValue = new RepositoryWebServiceTRH.AlmacenRepuestosContext.InsertRepuesto();
            inValue.codEmpleado = codEmpleado;
            inValue.codRepuesto = codRepuesto;
            inValue.cantidad = cantidad;
            inValue.maquina = maquina;
            inValue.destino = destino;
            return ((RepositoryWebServiceTRH.AlmacenRepuestosContext.AlmacenRepuestos_Port)(this)).InsertRepuestoAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        RepositoryWebServiceTRH.AlmacenRepuestosContext.UpdateRepuesto_Result RepositoryWebServiceTRH.AlmacenRepuestosContext.AlmacenRepuestos_Port.UpdateRepuesto(RepositoryWebServiceTRH.AlmacenRepuestosContext.UpdateRepuesto request) {
            return base.Channel.UpdateRepuesto(request);
        }
        
        public void UpdateRepuesto(string codEmpleado, string codRepuesto, decimal cantidad, int maquina, int destino) {
            RepositoryWebServiceTRH.AlmacenRepuestosContext.UpdateRepuesto inValue = new RepositoryWebServiceTRH.AlmacenRepuestosContext.UpdateRepuesto();
            inValue.codEmpleado = codEmpleado;
            inValue.codRepuesto = codRepuesto;
            inValue.cantidad = cantidad;
            inValue.maquina = maquina;
            inValue.destino = destino;
            RepositoryWebServiceTRH.AlmacenRepuestosContext.UpdateRepuesto_Result retVal = ((RepositoryWebServiceTRH.AlmacenRepuestosContext.AlmacenRepuestos_Port)(this)).UpdateRepuesto(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<RepositoryWebServiceTRH.AlmacenRepuestosContext.UpdateRepuesto_Result> RepositoryWebServiceTRH.AlmacenRepuestosContext.AlmacenRepuestos_Port.UpdateRepuestoAsync(RepositoryWebServiceTRH.AlmacenRepuestosContext.UpdateRepuesto request) {
            return base.Channel.UpdateRepuestoAsync(request);
        }
        
        public System.Threading.Tasks.Task<RepositoryWebServiceTRH.AlmacenRepuestosContext.UpdateRepuesto_Result> UpdateRepuestoAsync(string codEmpleado, string codRepuesto, decimal cantidad, int maquina, int destino) {
            RepositoryWebServiceTRH.AlmacenRepuestosContext.UpdateRepuesto inValue = new RepositoryWebServiceTRH.AlmacenRepuestosContext.UpdateRepuesto();
            inValue.codEmpleado = codEmpleado;
            inValue.codRepuesto = codRepuesto;
            inValue.cantidad = cantidad;
            inValue.maquina = maquina;
            inValue.destino = destino;
            return ((RepositoryWebServiceTRH.AlmacenRepuestosContext.AlmacenRepuestos_Port)(this)).UpdateRepuestoAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        RepositoryWebServiceTRH.AlmacenRepuestosContext.DeleteRepuesto_Result RepositoryWebServiceTRH.AlmacenRepuestosContext.AlmacenRepuestos_Port.DeleteRepuesto(RepositoryWebServiceTRH.AlmacenRepuestosContext.DeleteRepuesto request) {
            return base.Channel.DeleteRepuesto(request);
        }
        
        public void DeleteRepuesto(string codProducto, string codEmpleado) {
            RepositoryWebServiceTRH.AlmacenRepuestosContext.DeleteRepuesto inValue = new RepositoryWebServiceTRH.AlmacenRepuestosContext.DeleteRepuesto();
            inValue.codProducto = codProducto;
            inValue.codEmpleado = codEmpleado;
            RepositoryWebServiceTRH.AlmacenRepuestosContext.DeleteRepuesto_Result retVal = ((RepositoryWebServiceTRH.AlmacenRepuestosContext.AlmacenRepuestos_Port)(this)).DeleteRepuesto(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<RepositoryWebServiceTRH.AlmacenRepuestosContext.DeleteRepuesto_Result> RepositoryWebServiceTRH.AlmacenRepuestosContext.AlmacenRepuestos_Port.DeleteRepuestoAsync(RepositoryWebServiceTRH.AlmacenRepuestosContext.DeleteRepuesto request) {
            return base.Channel.DeleteRepuestoAsync(request);
        }
        
        public System.Threading.Tasks.Task<RepositoryWebServiceTRH.AlmacenRepuestosContext.DeleteRepuesto_Result> DeleteRepuestoAsync(string codProducto, string codEmpleado) {
            RepositoryWebServiceTRH.AlmacenRepuestosContext.DeleteRepuesto inValue = new RepositoryWebServiceTRH.AlmacenRepuestosContext.DeleteRepuesto();
            inValue.codProducto = codProducto;
            inValue.codEmpleado = codEmpleado;
            return ((RepositoryWebServiceTRH.AlmacenRepuestosContext.AlmacenRepuestos_Port)(this)).DeleteRepuestoAsync(inValue);
        }
    }
}
